// Auto-generated by build/inspection.rs from ASN.1; do not edit.
use crate::inspect::{Form, Typed, ies, messages, transfers};
pub(crate) const PROTOCOL: &str = "S1AP";
pub(crate) const ROOT: &str = "s1ap";
messages! {
    InitiatingMessage 0 "HandoverRequired" crate::s1ap::HandoverRequired;
    InitiatingMessage 1 "HandoverRequest" crate::s1ap::HandoverRequest;
    InitiatingMessage 2 "HandoverNotify" crate::s1ap::HandoverNotify;
    InitiatingMessage 3 "PathSwitchRequest" crate::s1ap::PathSwitchRequest;
    InitiatingMessage 4 "HandoverCancel" crate::s1ap::HandoverCancel;
    InitiatingMessage 5 "E-RABSetupRequest" crate::s1ap::ERABSetupRequest;
    InitiatingMessage 6 "E-RABModifyRequest" crate::s1ap::ERABModifyRequest;
    InitiatingMessage 7 "E-RABReleaseCommand" crate::s1ap::ERABReleaseCommand;
    InitiatingMessage 8 "E-RABReleaseIndication" crate::s1ap::ERABReleaseIndication;
    InitiatingMessage 9 "InitialContextSetupRequest" crate::s1ap::InitialContextSetupRequest;
    InitiatingMessage 10 "Paging" crate::s1ap::Paging;
    InitiatingMessage 11 "DownlinkNASTransport" crate::s1ap::DownlinkNASTransport;
    InitiatingMessage 12 "InitialUEMessage" crate::s1ap::InitialUEMessage;
    InitiatingMessage 13 "UplinkNASTransport" crate::s1ap::UplinkNASTransport;
    InitiatingMessage 14 "Reset" crate::s1ap::Reset;
    InitiatingMessage 15 "ErrorIndication" crate::s1ap::ErrorIndication;
    InitiatingMessage 16 "NASNonDeliveryIndication" crate::s1ap::NASNonDeliveryIndication;
    InitiatingMessage 17 "S1SetupRequest" crate::s1ap::S1SetupRequest;
    InitiatingMessage 18 "UEContextReleaseRequest" crate::s1ap::UEContextReleaseRequest;
    InitiatingMessage 19 "DownlinkS1cdma2000tunnelling" crate::s1ap::DownlinkS1cdma2000tunnelling;
    InitiatingMessage 20 "UplinkS1cdma2000tunnelling" crate::s1ap::UplinkS1cdma2000tunnelling;
    InitiatingMessage 21 "UEContextModificationRequest" crate::s1ap::UEContextModificationRequest;
    InitiatingMessage 22 "UECapabilityInfoIndication" crate::s1ap::UECapabilityInfoIndication;
    InitiatingMessage 23 "UEContextReleaseCommand" crate::s1ap::UEContextReleaseCommand;
    InitiatingMessage 24 "ENBStatusTransfer" crate::s1ap::ENBStatusTransfer;
    InitiatingMessage 25 "MMEStatusTransfer" crate::s1ap::MMEStatusTransfer;
    InitiatingMessage 26 "DeactivateTrace" crate::s1ap::DeactivateTrace;
    InitiatingMessage 27 "TraceStart" crate::s1ap::TraceStart;
    InitiatingMessage 28 "TraceFailureIndication" crate::s1ap::TraceFailureIndication;
    InitiatingMessage 29 "ENBConfigurationUpdate" crate::s1ap::ENBConfigurationUpdate;
    InitiatingMessage 30 "MMEConfigurationUpdate" crate::s1ap::MMEConfigurationUpdate;
    InitiatingMessage 31 "LocationReportingControl" crate::s1ap::LocationReportingControl;
    InitiatingMessage 32 "LocationReportingFailureIndication" crate::s1ap::LocationReportingFailureIndication;
    InitiatingMessage 33 "LocationReport" crate::s1ap::LocationReport;
    InitiatingMessage 34 "OverloadStart" crate::s1ap::OverloadStart;
    InitiatingMessage 35 "OverloadStop" crate::s1ap::OverloadStop;
    InitiatingMessage 36 "WriteReplaceWarningRequest" crate::s1ap::WriteReplaceWarningRequest;
    InitiatingMessage 37 "ENBDirectInformationTransfer" crate::s1ap::ENBDirectInformationTransfer;
    InitiatingMessage 38 "MMEDirectInformationTransfer" crate::s1ap::MMEDirectInformationTransfer;
    InitiatingMessage 39 "PrivateMessage" crate::s1ap::PrivateMessage;
    InitiatingMessage 40 "ENBConfigurationTransfer" crate::s1ap::ENBConfigurationTransfer;
    InitiatingMessage 41 "MMEConfigurationTransfer" crate::s1ap::MMEConfigurationTransfer;
    InitiatingMessage 42 "CellTrafficTrace" crate::s1ap::CellTrafficTrace;
    InitiatingMessage 43 "KillRequest" crate::s1ap::KillRequest;
    InitiatingMessage 44 "DownlinkUEAssociatedLPPaTransport" crate::s1ap::DownlinkUEAssociatedLPPaTransport;
    InitiatingMessage 45 "UplinkUEAssociatedLPPaTransport" crate::s1ap::UplinkUEAssociatedLPPaTransport;
    InitiatingMessage 46 "DownlinkNonUEAssociatedLPPaTransport" crate::s1ap::DownlinkNonUEAssociatedLPPaTransport;
    InitiatingMessage 47 "UplinkNonUEAssociatedLPPaTransport" crate::s1ap::UplinkNonUEAssociatedLPPaTransport;
    InitiatingMessage 48 "UERadioCapabilityMatchRequest" crate::s1ap::UERadioCapabilityMatchRequest;
    InitiatingMessage 49 "PWSRestartIndication" crate::s1ap::PWSRestartIndication;
    InitiatingMessage 50 "E-RABModificationIndication" crate::s1ap::ERABModificationIndication;
    InitiatingMessage 51 "PWSFailureIndication" crate::s1ap::PWSFailureIndication;
    InitiatingMessage 52 "RerouteNASRequest" crate::s1ap::RerouteNASRequest;
    InitiatingMessage 53 "UEContextModificationIndication" crate::s1ap::UEContextModificationIndication;
    InitiatingMessage 54 "ConnectionEstablishmentIndication" crate::s1ap::ConnectionEstablishmentIndication;
    InitiatingMessage 55 "UEContextSuspendRequest" crate::s1ap::UEContextSuspendRequest;
    InitiatingMessage 56 "UEContextResumeRequest" crate::s1ap::UEContextResumeRequest;
    InitiatingMessage 57 "NASDeliveryIndication" crate::s1ap::NASDeliveryIndication;
    InitiatingMessage 58 "RetrieveUEInformation" crate::s1ap::RetrieveUEInformation;
    InitiatingMessage 59 "UEInformationTransfer" crate::s1ap::UEInformationTransfer;
    InitiatingMessage 60 "ENBCPRelocationIndication" crate::s1ap::ENBCPRelocationIndication;
    InitiatingMessage 61 "MMECPRelocationIndication" crate::s1ap::MMECPRelocationIndication;
    InitiatingMessage 62 "SecondaryRATDataUsageReport" crate::s1ap::SecondaryRATDataUsageReport;
    InitiatingMessage 63 "UERadioCapabilityIDMappingRequest" crate::s1ap::UERadioCapabilityIDMappingRequest;
    InitiatingMessage 64 "HandoverSuccess" crate::s1ap::HandoverSuccess;
    InitiatingMessage 65 "ENBEarlyStatusTransfer" crate::s1ap::ENBEarlyStatusTransfer;
    InitiatingMessage 66 "MMEEarlyStatusTransfer" crate::s1ap::MMEEarlyStatusTransfer;
    InitiatingMessage 67 "S1RemovalRequest" crate::s1ap::S1RemovalRequest;
    SuccessfulOutcome 0 "HandoverCommand" crate::s1ap::HandoverCommand;
    SuccessfulOutcome 1 "HandoverRequestAcknowledge" crate::s1ap::HandoverRequestAcknowledge;
    SuccessfulOutcome 3 "PathSwitchRequestAcknowledge" crate::s1ap::PathSwitchRequestAcknowledge;
    SuccessfulOutcome 4 "HandoverCancelAcknowledge" crate::s1ap::HandoverCancelAcknowledge;
    SuccessfulOutcome 5 "E-RABSetupResponse" crate::s1ap::ERABSetupResponse;
    SuccessfulOutcome 6 "E-RABModifyResponse" crate::s1ap::ERABModifyResponse;
    SuccessfulOutcome 7 "E-RABReleaseResponse" crate::s1ap::ERABReleaseResponse;
    SuccessfulOutcome 9 "InitialContextSetupResponse" crate::s1ap::InitialContextSetupResponse;
    SuccessfulOutcome 14 "ResetAcknowledge" crate::s1ap::ResetAcknowledge;
    SuccessfulOutcome 17 "S1SetupResponse" crate::s1ap::S1SetupResponse;
    SuccessfulOutcome 21 "UEContextModificationResponse" crate::s1ap::UEContextModificationResponse;
    SuccessfulOutcome 23 "UEContextReleaseComplete" crate::s1ap::UEContextReleaseComplete;
    SuccessfulOutcome 29 "ENBConfigurationUpdateAcknowledge" crate::s1ap::ENBConfigurationUpdateAcknowledge;
    SuccessfulOutcome 30 "MMEConfigurationUpdateAcknowledge" crate::s1ap::MMEConfigurationUpdateAcknowledge;
    SuccessfulOutcome 36 "WriteReplaceWarningResponse" crate::s1ap::WriteReplaceWarningResponse;
    SuccessfulOutcome 43 "KillResponse" crate::s1ap::KillResponse;
    SuccessfulOutcome 48 "UERadioCapabilityMatchResponse" crate::s1ap::UERadioCapabilityMatchResponse;
    SuccessfulOutcome 50 "E-RABModificationConfirm" crate::s1ap::ERABModificationConfirm;
    SuccessfulOutcome 53 "UEContextModificationConfirm" crate::s1ap::UEContextModificationConfirm;
    SuccessfulOutcome 55 "UEContextSuspendResponse" crate::s1ap::UEContextSuspendResponse;
    SuccessfulOutcome 56 "UEContextResumeResponse" crate::s1ap::UEContextResumeResponse;
    SuccessfulOutcome 63 "UERadioCapabilityIDMappingResponse" crate::s1ap::UERadioCapabilityIDMappingResponse;
    SuccessfulOutcome 67 "S1RemovalResponse" crate::s1ap::S1RemovalResponse;
    UnsuccessfulOutcome 0 "HandoverPreparationFailure" crate::s1ap::HandoverPreparationFailure;
    UnsuccessfulOutcome 1 "HandoverFailure" crate::s1ap::HandoverFailure;
    UnsuccessfulOutcome 3 "PathSwitchRequestFailure" crate::s1ap::PathSwitchRequestFailure;
    UnsuccessfulOutcome 9 "InitialContextSetupFailure" crate::s1ap::InitialContextSetupFailure;
    UnsuccessfulOutcome 17 "S1SetupFailure" crate::s1ap::S1SetupFailure;
    UnsuccessfulOutcome 21 "UEContextModificationFailure" crate::s1ap::UEContextModificationFailure;
    UnsuccessfulOutcome 29 "ENBConfigurationUpdateFailure" crate::s1ap::ENBConfigurationUpdateFailure;
    UnsuccessfulOutcome 30 "MMEConfigurationUpdateFailure" crate::s1ap::MMEConfigurationUpdateFailure;
    UnsuccessfulOutcome 56 "UEContextResumeFailure" crate::s1ap::UEContextResumeFailure;
    UnsuccessfulOutcome 67 "S1RemovalFailure" crate::s1ap::S1RemovalFailure;
}
ies! {
    0 "MME-UE-S1AP-ID" crate::s1ap::MMEUES1APID;
    1 "HandoverType" crate::s1ap::HandoverType;
    2 "Cause" crate::s1ap::Cause;
    4 "TargetID" crate::s1ap::TargetID;
    8 "eNB-UE-S1AP-ID" crate::s1ap::ENBUES1APID;
    12 "E-RABSubjecttoDataForwardingList" crate::s1ap::ERABSubjecttoDataForwardingList;
    13 "E-RABtoReleaseListHOCmd" crate::s1ap::ERABList;
    14 "E-RABDataForwardingItem" crate::s1ap::ERABDataForwardingItem;
    15 "E-RABReleaseItemBearerRelComp" crate::s1ap::ERABReleaseItemBearerRelComp;
    16 "E-RABToBeSetupListBearerSUReq" crate::s1ap::ERABToBeSetupListBearerSUReq;
    17 "E-RABToBeSetupItemBearerSUReq" crate::s1ap::ERABToBeSetupItemBearerSUReq;
    18 "E-RABAdmittedList" crate::s1ap::ERABAdmittedList;
    19 "E-RABFailedToSetupListHOReqAck" crate::s1ap::ERABFailedtoSetupListHOReqAck;
    20 "E-RABAdmittedItem" crate::s1ap::ERABAdmittedItem;
    21 "E-RABFailedtoSetupItemHOReqAck" crate::s1ap::ERABFailedToSetupItemHOReqAck;
    22 "E-RABToBeSwitchedDLList" crate::s1ap::ERABToBeSwitchedDLList;
    23 "E-RABToBeSwitchedDLItem" crate::s1ap::ERABToBeSwitchedDLItem;
    24 "E-RABToBeSetupListCtxtSUReq" crate::s1ap::ERABToBeSetupListCtxtSUReq;
    25 "TraceActivation" crate::s1ap::TraceActivation;
    26 "NAS-PDU" crate::s1ap::NASPDU;
    27 "E-RABToBeSetupItemHOReq" crate::s1ap::ERABToBeSetupItemHOReq;
    28 "E-RABSetupListBearerSURes" crate::s1ap::ERABSetupListBearerSURes;
    29 "E-RABFailedToSetupListBearerSURes" crate::s1ap::ERABList;
    30 "E-RABToBeModifiedListBearerModReq" crate::s1ap::ERABToBeModifiedListBearerModReq;
    31 "E-RABModifyListBearerModRes" crate::s1ap::ERABModifyListBearerModRes;
    32 "E-RABFailedToModifyList" crate::s1ap::ERABList;
    33 "E-RABToBeReleasedList" crate::s1ap::ERABList;
    34 "E-RABFailedToReleaseList" crate::s1ap::ERABList;
    35 "E-RABItem" crate::s1ap::ERABItem;
    36 "E-RABToBeModifiedItemBearerModReq" crate::s1ap::ERABToBeModifiedItemBearerModReq;
    37 "E-RABModifyItemBearerModRes" crate::s1ap::ERABModifyItemBearerModRes;
    39 "E-RABSetupItemBearerSURes" crate::s1ap::ERABSetupItemBearerSURes;
    40 "SecurityContext" crate::s1ap::SecurityContext;
    41 "HandoverRestrictionList" crate::s1ap::HandoverRestrictionList;
    43 "UEPagingID" crate::s1ap::UEPagingID;
    44 "pagingDRX" crate::s1ap::PagingDRX;
    46 "TAIList" crate::s1ap::TAIList;
    47 "TAIItem" crate::s1ap::TAIItem;
    48 "E-RABFailedToSetupListCtxtSURes" crate::s1ap::ERABList;
    50 "E-RABSetupItemCtxtSURes" crate::s1ap::ERABSetupItemCtxtSURes;
    51 "E-RABSetupListCtxtSURes" crate::s1ap::ERABSetupListCtxtSURes;
    52 "E-RABToBeSetupItemCtxtSUReq" crate::s1ap::ERABToBeSetupItemCtxtSUReq;
    53 "E-RABToBeSetupListHOReq" crate::s1ap::ERABToBeSetupListHOReq;
    58 "CriticalityDiagnostics" crate::s1ap::CriticalityDiagnostics;
    59 "Global-ENB-ID" crate::s1ap::GlobalENBID;
    60 "eNBname" crate::s1ap::ENBname;
    61 "MMEname" crate::s1ap::MMEname;
    64 "SupportedTAs" crate::s1ap::SupportedTAs;
    65 "TimeToWait" crate::s1ap::TimeToWait;
    66 "uEaggregateMaximumBitrate" crate::s1ap::UEAggregateMaximumBitrate;
    67 "TAI" crate::s1ap::TAI;
    69 "E-RABReleaseListBearerRelComp" crate::s1ap::ERABReleaseListBearerRelComp;
    70 "cdma2000PDU" crate::s1ap::Cdma2000PDU;
    71 "cdma2000RATType" crate::s1ap::Cdma2000RATType;
    72 "cdma2000SectorID" crate::s1ap::Cdma2000SectorID;
    73 "SecurityKey" crate::s1ap::SecurityKey;
    74 "UERadioCapability" crate::s1ap::UERadioCapability;
    75 "GUMMEI-ID" crate::s1ap::GUMMEI;
    78 "E-RABInformationListItem" crate::s1ap::ERABInformationListItem;
    79 "Direct-Forwarding-Path-Availability" crate::s1ap::DirectForwardingPathAvailability;
    80 "UEIdentityIndexValue" crate::s1ap::UEIdentityIndexValue;
    83 "cdma2000HOStatus" crate::s1ap::Cdma2000HOStatus;
    84 "cdma2000HORequiredIndication" crate::s1ap::Cdma2000HORequiredIndication;
    86 "E-UTRAN-Trace-ID" crate::s1ap::EUTRANTraceID;
    87 "RelativeMMECapacity" crate::s1ap::RelativeMMECapacity;
    88 "SourceMME-UE-S1AP-ID" crate::s1ap::MMEUES1APID;
    89 "Bearers-SubjectToStatusTransfer-Item" crate::s1ap::BearersSubjectToStatusTransferItem;
    90 "eNB-StatusTransfer-TransparentContainer" crate::s1ap::ENBStatusTransferTransparentContainer;
    91 "UE-associatedLogicalS1-ConnectionItem" crate::s1ap::UEAssociatedLogicalS1ConnectionItem;
    92 "ResetType" crate::s1ap::ResetType;
    93 "UE-associatedLogicalS1-ConnectionListResAck" crate::s1ap::UEAssociatedLogicalS1ConnectionListResAck;
    94 "E-RABToBeSwitchedULItem" crate::s1ap::ERABToBeSwitchedULItem;
    95 "E-RABToBeSwitchedULList" crate::s1ap::ERABToBeSwitchedULList;
    96 "S-TMSI" crate::s1ap::STMSI;
    97 "cdma2000OneXRAND" crate::s1ap::Cdma2000OneXRAND;
    98 "RequestType" crate::s1ap::RequestType;
    99 "UE-S1AP-IDs" crate::s1ap::UES1APIDs;
    100 "EUTRAN-CGI" crate::s1ap::EUTRANCGI;
    101 "OverloadResponse" crate::s1ap::OverloadResponse;
    102 "cdma2000OneXSRVCCInfo" crate::s1ap::Cdma2000OneXSRVCCInfo;
    104 "Source-ToTarget-TransparentContainer" crate::s1ap::SourceToTargetTransparentContainer;
    105 "ServedGUMMEIs" crate::s1ap::ServedGUMMEIs;
    106 "SubscriberProfileIDforRFP" crate::s1ap::SubscriberProfileIDforRFP;
    107 "UESecurityCapabilities" crate::s1ap::UESecurityCapabilities;
    108 "CSFallbackIndicator" crate::s1ap::CSFallbackIndicator;
    109 "CNDomain" crate::s1ap::CNDomain;
    110 "E-RABReleasedList" crate::s1ap::ERABList;
    111 "MessageIdentifier" crate::s1ap::MessageIdentifier;
    112 "SerialNumber" crate::s1ap::SerialNumber;
    113 "WarningAreaList" crate::s1ap::WarningAreaList;
    114 "RepetitionPeriod" crate::s1ap::RepetitionPeriod;
    115 "NumberofBroadcastRequest" crate::s1ap::NumberofBroadcastRequest;
    116 "WarningType" crate::s1ap::WarningType;
    117 "WarningSecurityInfo" crate::s1ap::WarningSecurityInfo;
    118 "DataCodingScheme" crate::s1ap::DataCodingScheme;
    119 "WarningMessageContents" crate::s1ap::WarningMessageContents;
    120 "BroadcastCompletedAreaList" crate::s1ap::BroadcastCompletedAreaList;
    121 "Inter-SystemInformationTransferTypeEDT" crate::s1ap::InterSystemInformationTransferType;
    122 "Inter-SystemInformationTransferTypeMDT" crate::s1ap::InterSystemInformationTransferType;
    123 "Target-ToSource-TransparentContainer" crate::s1ap::TargetToSourceTransparentContainer;
    124 "SRVCCOperationPossible" crate::s1ap::SRVCCOperationPossible;
    125 "SRVCCHOIndication" crate::s1ap::SRVCCHOIndication;
    127 "CSG-Id" crate::s1ap::CSGId;
    128 "CSG-IdList" crate::s1ap::CSGIdList;
    129 "SONConfigurationTransferECT" crate::s1ap::SONConfigurationTransfer;
    130 "SONConfigurationTransferMCT" crate::s1ap::SONConfigurationTransfer;
    131 "TraceCollectionEntityIPAddress" crate::s1ap::TransportLayerAddress;
    132 "MSClassmark2" crate::s1ap::MSClassmark2;
    133 "MSClassmark3" crate::s1ap::MSClassmark3;
    134 "RRC-Establishment-Cause" crate::s1ap::RRCEstablishmentCause;
    135 "NASSecurityParametersfromE-UTRAN" crate::s1ap::NASSecurityParametersfromEUTRAN;
    136 "NASSecurityParameterstoE-UTRAN" crate::s1ap::NASSecurityParameterstoEUTRAN;
    137 "DefaultPagingDRX" crate::s1ap::PagingDRX;
    138 "Source-ToTarget-TransparentContainer-Secondary" crate::s1ap::SourceToTargetTransparentContainer;
    139 "Target-ToSource-TransparentContainer-Secondary" crate::s1ap::TargetToSourceTransparentContainer;
    140 "EUTRANRoundTripDelayEstimationInfo" crate::s1ap::EUTRANRoundTripDelayEstimationInfo;
    141 "BroadcastCancelledAreaList" crate::s1ap::BroadcastCancelledAreaList;
    142 "ConcurrentWarningMessageIndicator" crate::s1ap::ConcurrentWarningMessageIndicator;
    143 "Data-Forwarding-Not-Possible" crate::s1ap::DataForwardingNotPossible;
    144 "ExtendedRepetitionPeriod" crate::s1ap::ExtendedRepetitionPeriod;
    145 "CellAccessMode" crate::s1ap::CellAccessMode;
    146 "CSGMembershipStatus" crate::s1ap::CSGMembershipStatus;
    147 "LPPa-PDU" crate::s1ap::LPPaPDU;
    148 "Routing-ID" crate::s1ap::RoutingID;
    149 "Time-Synchronisation-Info" crate::s1ap::TimeSynchronisationInfo;
    150 "PS-ServiceNotAvailable" crate::s1ap::PSServiceNotAvailable;
    151 "PagingPriority" crate::s1ap::PagingPriority;
    152 "x2TNLConfigurationInfo" crate::s1ap::X2TNLConfigurationInfo;
    153 "eNBX2ExtendedTransportLayerAddresses" crate::s1ap::ENBX2ExtTLAs;
    154 "GUMMEIList" crate::s1ap::GUMMEIList;
    155 "GW-TransportLayerAddress" crate::s1ap::TransportLayerAddress;
    156 "Correlation-ID" crate::s1ap::CorrelationID;
    157 "SourceMME-GUMMEI" crate::s1ap::GUMMEI;
    158 "MME-UE-S1AP-ID-2" crate::s1ap::MMEUES1APID;
    159 "RegisteredLAI" crate::s1ap::LAI;
    160 "RelayNode-Indicator" crate::s1ap::RelayNodeIndicator;
    161 "TrafficLoadReductionIndication" crate::s1ap::TrafficLoadReductionIndication;
    162 "MDTConfiguration" crate::s1ap::MDTConfiguration;
    163 "MMERelaySupportIndicator" crate::s1ap::MMERelaySupportIndicator;
    164 "GWContextReleaseIndication" crate::s1ap::GWContextReleaseIndication;
    165 "ManagementBasedMDTAllowed" crate::s1ap::ManagementBasedMDTAllowed;
    166 "PrivacyIndicator" crate::s1ap::PrivacyIndicator;
    167 "Time-UE-StayedInCell-EnhancedGranularity" crate::s1ap::TimeUEStayedInCellEnhancedGranularity;
    168 "HO-Cause" crate::s1ap::Cause;
    169 "VoiceSupportMatchIndicator" crate::s1ap::VoiceSupportMatchIndicator;
    170 "GUMMEIType" crate::s1ap::GUMMEIType;
    171 "M3Configuration" crate::s1ap::M3Configuration;
    172 "M4Configuration" crate::s1ap::M4Configuration;
    173 "M5Configuration" crate::s1ap::M5Configuration;
    174 "MDT-Location-Info" crate::s1ap::MDTLocationInfo;
    175 "MobilityInformation" crate::s1ap::MobilityInformation;
    176 "Tunnel-Information-for-BBF" crate::s1ap::TunnelInformation;
    177 "ManagementBasedMDTPLMNList" crate::s1ap::MDTPLMNList;
    178 "SignallingBasedMDTPLMNList" crate::s1ap::MDTPLMNList;
    179 "ULCOUNTValueExtended" crate::s1ap::COUNTValueExtended;
    180 "DLCOUNTValueExtended" crate::s1ap::COUNTValueExtended;
    181 "ReceiveStatusOfULPDCPSDUsExtended" crate::s1ap::ReceiveStatusOfULPDCPSDUsExtended;
    182 "ECGIListForRestart" crate::s1ap::ECGIListForRestart;
    183 "SIPTO-Correlation-ID" crate::s1ap::CorrelationID;
    184 "SIPTO-L-GW-TransportLayerAddress" crate::s1ap::TransportLayerAddress;
    185 "TransportInformation" crate::s1ap::TransportInformation;
    186 "LHN-ID" crate::s1ap::LHNID;
    187 "AdditionalCSFallbackIndicator" crate::s1ap::AdditionalCSFallbackIndicator;
    188 "TAIListForRestart" crate::s1ap::TAIListForRestart;
    189 "UserLocationInformation" crate::s1ap::UserLocationInformation;
    190 "EmergencyAreaIDListForRestart" crate::s1ap::EmergencyAreaIDListForRestart;
    191 "KillAllWarningMessages" crate::s1ap::KillAllWarningMessages;
    192 "Masked-IMEISV" crate::s1ap::MaskedIMEISV;
    193 "eNBIndirectX2TransportLayerAddresses" crate::s1ap::ENBIndirectX2TransportLayerAddresses;
    194 "uE-HistoryInformationFromTheUE" crate::s1ap::UEHistoryInformationFromTheUE;
    195 "ProSeAuthorized" crate::s1ap::ProSeAuthorized;
    196 "ExpectedUEBehaviour" crate::s1ap::ExpectedUEBehaviour;
    197 "LoggedMBSFNMDT" crate::s1ap::LoggedMBSFNMDT;
    198 "UERadioCapabilityForPaging" crate::s1ap::UERadioCapabilityForPaging;
    199 "E-RABToBeModifiedListBearerModInd" crate::s1ap::ERABToBeModifiedListBearerModInd;
    200 "E-RABToBeModifiedItemBearerModInd" crate::s1ap::ERABToBeModifiedItemBearerModInd;
    201 "E-RABNotToBeModifiedListBearerModInd" crate::s1ap::ERABNotToBeModifiedListBearerModInd;
    202 "E-RABNotToBeModifiedItemBearerModInd" crate::s1ap::ERABNotToBeModifiedItemBearerModInd;
    203 "E-RABModifyListBearerModConf" crate::s1ap::ERABModifyListBearerModConf;
    204 "E-RABModifyItemBearerModConf" crate::s1ap::ERABModifyItemBearerModConf;
    205 "E-RABFailedToModifyListBearerModConf" crate::s1ap::ERABList;
    206 "SON-Information-Report" crate::s1ap::SONInformationReport;
    207 "Muting-Availability-Indication" crate::s1ap::MutingAvailabilityIndication;
    208 "Muting-Pattern-Information" crate::s1ap::MutingPatternInformation;
    209 "Synchronisation-Information" crate::s1ap::SynchronisationInformation;
    210 "E-RABToBeReleasedListBearerModConf" crate::s1ap::ERABList;
    211 "AssistanceDataForPaging" crate::s1ap::AssistanceDataForPaging;
    212 "CellIdentifierAndCELevelForCECapableUEs" crate::s1ap::CellIdentifierAndCELevelForCECapableUEs;
    213 "InformationOnRecommendedCellsAndENBsForPaging" crate::s1ap::InformationOnRecommendedCellsAndENBsForPaging;
    214 "RecommendedCellItem" crate::s1ap::RecommendedCellItem;
    215 "RecommendedENBItem" crate::s1ap::RecommendedENBItem;
    216 "ProSeUEtoNetworkRelaying" crate::s1ap::ProSeUEtoNetworkRelaying;
    217 "ULCOUNTValuePDCP-SNlength18" crate::s1ap::COUNTvaluePDCPSNlength18;
    218 "DLCOUNTValuePDCP-SNlength18" crate::s1ap::COUNTvaluePDCPSNlength18;
    219 "ReceiveStatusOfULPDCPSDUsPDCP-SNlength18" crate::s1ap::ReceiveStatusOfULPDCPSDUsPDCPSNlength18;
    220 "M6Configuration" crate::s1ap::M6Configuration;
    221 "M7Configuration" crate::s1ap::M7Configuration;
    222 "PWSfailedECGIList" crate::s1ap::PWSfailedECGIList;
    223 "MME-Group-ID" crate::s1ap::MMEGroupID;
    224 "Additional-GUTI" crate::s1ap::AdditionalGUTI;
    225 "S1-Message" rasn::types::OctetString;
    226 "CSGMembershipInfo" crate::s1ap::CSGMembershipInfo;
    227 "Paging-eDRXInformation" crate::s1ap::PagingEDRXInformation;
    228 "UE-RetentionInformation" crate::s1ap::UERetentionInformation;
    230 "UE-Usage-Type" crate::s1ap::UEUsageType;
    231 "extended-UEIdentityIndexValue" crate::s1ap::ExtendedUEIdentityIndexValue;
    232 "RAT-Type" crate::s1ap::RATType;
    233 "BearerType" crate::s1ap::BearerType;
    234 "NB-IoT-DefaultPagingDRX" crate::s1ap::NBIoTDefaultPagingDRX;
    235 "E-RABFailedToResumeListResumeReq" crate::s1ap::ERABFailedToResumeListResumeReq;
    236 "E-RABFailedToResumeItemResumeReq" crate::s1ap::ERABFailedToResumeItemResumeReq;
    237 "E-RABFailedToResumeListResumeRes" crate::s1ap::ERABFailedToResumeListResumeRes;
    238 "E-RABFailedToResumeItemResumeRes" crate::s1ap::ERABFailedToResumeItemResumeRes;
    239 "NB-IoT-Paging-eDRXInformation" crate::s1ap::NBIoTPagingEDRXInformation;
    240 "V2XServicesAuthorized" crate::s1ap::V2XServicesAuthorized;
    241 "UEUserPlaneCIoTSupportIndicator" crate::s1ap::UEUserPlaneCIoTSupportIndicator;
    242 "CE-mode-B-SupportIndicator" crate::s1ap::CEModeBSupportIndicator;
    243 "SRVCCOperationNotPossible" crate::s1ap::SRVCCOperationNotPossible;
    244 "NB-IoT-UEIdentityIndexValue" crate::s1ap::NBIoTUEIdentityIndexValue;
    245 "RRC-Resume-Cause" crate::s1ap::RRCEstablishmentCause;
    246 "DCN-ID" crate::s1ap::DCNID;
    247 "ServedDCNs" crate::s1ap::ServedDCNs;
    248 "UESidelinkAggregateMaximumBitrate" crate::s1ap::UESidelinkAggregateMaximumBitrate;
    249 "DLNASPDUDeliveryAckRequest" crate::s1ap::DLNASPDUDeliveryAckRequest;
    250 "Coverage-Level" crate::s1ap::CoverageLevel;
    251 "EnhancedCoverageRestricted" crate::s1ap::EnhancedCoverageRestricted;
    252 "UE-Level-QoS-Parameters" crate::s1ap::ERABLevelQoSParameters;
    253 "DL-CP-SecurityInformation" crate::s1ap::DLCPSecurityInformation;
    254 "UL-CP-SecurityInformation" crate::s1ap::ULCPSecurityInformation;
    255 "extended-e-RAB-MaximumBitrateDL" crate::s1ap::ExtendedBitRate;
    256 "extended-e-RAB-MaximumBitrateUL" crate::s1ap::ExtendedBitRate;
    257 "extended-e-RAB-GuaranteedBitrateDL" crate::s1ap::ExtendedBitRate;
    258 "extended-e-RAB-GuaranteedBitrateUL" crate::s1ap::ExtendedBitRate;
    259 "extended-uEaggregateMaximumBitRateDL" crate::s1ap::ExtendedBitRate;
    260 "extended-uEaggregateMaximumBitRateUL" crate::s1ap::ExtendedBitRate;
    261 "NRrestrictioninEPSasSecondaryRAT" crate::s1ap::NRrestrictioninEPSasSecondaryRAT;
    262 "UEAppLayerMeasConfig" crate::s1ap::UEAppLayerMeasConfig;
    263 "UE-Application-Layer-Measurement-Capability" crate::s1ap::UEApplicationLayerMeasurementCapability;
    264 "SecondaryRATDataUsageReportList" crate::s1ap::SecondaryRATDataUsageReportList;
    265 "SecondaryRATDataUsageReportItem" crate::s1ap::SecondaryRATDataUsageReportItem;
    266 "HandoverFlag" crate::s1ap::HandoverFlag;
    267 "E-RABUsageReportItem" crate::s1ap::ERABUsageReportItem;
    268 "SecondaryRATDataUsageRequest" crate::s1ap::SecondaryRATDataUsageRequest;
    269 "NRUESecurityCapabilities" crate::s1ap::NRUESecurityCapabilities;
    270 "UnlicensedSpectrumRestriction" crate::s1ap::UnlicensedSpectrumRestriction;
    271 "CE-ModeBRestricted" crate::s1ap::CEModeBRestricted;
    272 "LTE-M-Indication" crate::s1ap::LTEMIndication;
    273 "DownlinkPacketLossRate" crate::s1ap::PacketLossRate;
    274 "UplinkPacketLossRate" crate::s1ap::PacketLossRate;
    275 "UECapabilityInfoRequest" crate::s1ap::UECapabilityInfoRequest;
    276 "serviceType" crate::s1ap::ServiceType;
    277 "AerialUEsubscriptionInformation" crate::s1ap::AerialUEsubscriptionInformation;
    278 "Subscription-Based-UE-DifferentiationInfo" crate::s1ap::SubscriptionBasedUEDifferentiationInfo;
    280 "EndIndication" crate::s1ap::EndIndication;
    281 "EDT-Session" crate::s1ap::EDTSession;
    282 "CNTypeRestrictions" crate::s1ap::CNTypeRestrictions;
    283 "PendingDataIndication" crate::s1ap::PendingDataIndication;
    284 "BluetoothMeasurementConfiguration" crate::s1ap::BluetoothMeasurementConfiguration;
    285 "WLANMeasurementConfiguration" crate::s1ap::WLANMeasurementConfiguration;
    286 "WarningAreaCoordinates" crate::s1ap::WarningAreaCoordinates;
    287 "NRrestrictionin5GS" crate::s1ap::NRrestrictionin5GS;
    288 "PSCellInformation" crate::s1ap::PSCellInformation;
    290 "LastNG-RANPLMNIdentity" crate::s1ap::PLMNidentity;
    291 "ConnectedengNBList" crate::s1ap::ConnectedengNBList;
    292 "ConnectedengNBToAddList" crate::s1ap::ConnectedengNBList;
    293 "ConnectedengNBToRemoveList" crate::s1ap::ConnectedengNBList;
    294 "EN-DCSONConfigurationTransfer-ECT" crate::s1ap::ENDCSONConfigurationTransfer;
    295 "EN-DCSONConfigurationTransfer-MCT" crate::s1ap::ENDCSONConfigurationTransfer;
    296 "IMSvoiceEPSfallbackfrom5G" crate::s1ap::IMSvoiceEPSfallbackfrom5G;
    297 "TimeSinceSecondaryNodeRelease" crate::s1ap::TimeSinceSecondaryNodeRelease;
    298 "RequestTypeAdditionalInfo" crate::s1ap::RequestTypeAdditionalInfo;
    299 "AdditionalRRMPriorityIndex" crate::s1ap::AdditionalRRMPriorityIndex;
    300 "ContextatSource" crate::s1ap::ContextatSource;
    301 "IAB-Authorized" crate::s1ap::IABAuthorized;
    302 "IAB-Node-Indication" crate::s1ap::IABNodeIndication;
    303 "IAB-Supported" crate::s1ap::IABSupported;
    304 "DataSize" crate::s1ap::DataSize;
    305 "Ethernet-Type" crate::s1ap::EthernetType;
    306 "NRV2XServicesAuthorized" crate::s1ap::NRV2XServicesAuthorized;
    307 "NRUESidelinkAggregateMaximumBitrate" crate::s1ap::NRUESidelinkAggregateMaximumBitrate;
    308 "PC5QoSParameters" crate::s1ap::PC5QoSParameters;
    309 "IntersystemSONConfigurationTransferMCT" crate::s1ap::IntersystemSONConfigurationTransfer;
    310 "IntersystemSONConfigurationTransferECT" crate::s1ap::IntersystemSONConfigurationTransfer;
    311 "IntersystemMeasurementConfiguration" crate::s1ap::IntersystemMeasurementConfiguration;
    312 "SourceNodeID" crate::s1ap::SourceNodeID;
    313 "NB-IoT-RLF-Report-Container" crate::s1ap::NBIoTRLFReportContainer;
    314 "UERadioCapabilityID" crate::s1ap::UERadioCapabilityID;
    315 "UERadioCapability-NR-Format" crate::s1ap::UERadioCapability;
    316 "MDTConfigurationNR" crate::s1ap::MDTConfigurationNR;
    317 "DAPSRequestInfo" crate::s1ap::DAPSRequestInfo;
    318 "DAPSResponseInfoList" crate::s1ap::DAPSResponseInfoList;
    319 "DAPSResponseInfoItem" crate::s1ap::DAPSResponseInfoItem;
    320 "NotifySourceeNB" crate::s1ap::NotifySourceeNB;
    321 "eNB-EarlyStatusTransfer-TransparentContainer" crate::s1ap::ENBEarlyStatusTransferTransparentContainer;
    322 "Bearers-SubjectToEarlyStatusTransfer-Item" crate::s1ap::BearersSubjectToEarlyStatusTransferItem;
    323 "WUS-Assistance-Information" crate::s1ap::WUSAssistanceInformation;
    324 "NB-IoT-PagingDRX" crate::s1ap::NBIoTPagingDRX;
    325 "TraceCollectionEntityURI" crate::s1ap::URIAddress;
    326 "EmergencyIndicator" crate::s1ap::EmergencyIndicator;
    327 "UERadioCapabilityForPaging-NR-Format" crate::s1ap::UERadioCapabilityForPaging;
    328 "SourceTransportLayerAddress" crate::s1ap::TransportLayerAddress;
    329 "lastVisitedPSCellList" crate::s1ap::LastVisitedPSCellList;
    330 "RACSIndication" crate::s1ap::RACSIndication;
    331 "PagingCause" crate::s1ap::PagingCause;
    332 "SecurityIndication" crate::s1ap::SecurityIndication;
    334 "E-RABSecurityResultItem" crate::s1ap::ERABSecurityResultItem;
    335 "E-RABSecurityResultList" crate::s1ap::ERABSecurityResultList;
    336 "RAT-Restrictions" crate::s1ap::RATRestrictions;
    337 "UEContextReferenceatSourceeNB" crate::s1ap::ENBUES1APID;
    339 "LTE-NTN-TAI-Information" crate::s1ap::LTENTNTAIInformation;
    340 "SourceNodeTransportLayerAddress" crate::s1ap::TransportLayerAddress;
    341 "E-RABToBeUpdatedList" crate::s1ap::ERABToBeUpdatedList;
    342 "E-RABToBeUpdatedItem" crate::s1ap::ERABToBeUpdatedItem;
    343 "SourceSNID" crate::s1ap::GlobalRANNODEID;
    344 "LoggedMDTTrigger" crate::s1ap::LoggedMDTTrigger;
    345 "SensorMeasurementConfiguration" crate::s1ap::SensorMeasurementConfiguration;
    346 "M4ReportAmount" crate::s1ap::M4ReportAmountMDT;
    347 "M5ReportAmount" crate::s1ap::M5ReportAmountMDT;
    348 "M6ReportAmount" crate::s1ap::M6ReportAmountMDT;
    349 "M7ReportAmount" crate::s1ap::M7ReportAmountMDT;
    350 "TimeBasedHandoverInformation" crate::s1ap::TimeBasedHandoverInformation;
    351 "Bearers-SubjectToDLDiscarding-Item" crate::s1ap::BearersSubjectToDLDiscardingItem;
    352 "Bearers-SubjectToDLDiscardingList" crate::s1ap::BearersSubjectToDLDiscardingList;
    353 "CoarseUELocationRequested" crate::s1ap::CoarseUELocationRequested;
    354 "CoarseUELocation" crate::s1ap::CoarseUELocation;
    355 "TimeRefDistribution" crate::s1ap::TimeRefDistribution;
    356 "RequestedTNLInfo" crate::s1ap::RequestedTNLInfo;
}
transfers! {}
pub(crate) fn member_form(name: &str) -> Option<Form> {
    Some(match name {
        // CI
        "cI" => Form::Number(16),
        // CellIdentity
        "cell-ID" => Form::Number(28),
        // FiveGSTAC
        "fiveGSTAC" => Form::Number(24),
        // GTP-TEID
        "dL-GTP-TEID" | "dL-gTP-TEID" | "gTP-TEID" | "uL-GTP-TEID" => Form::Number(32),
        // IMSI
        "iMSI" => Form::Digits,
        // LAC
        "forbiddenLACs" | "lAC" => Form::Number(16),
        // M-TMSI
        "m-TMSI" => Form::Number(32),
        // MME-Code
        "mME-Code" | "mMEC" | "servedMMECs" => Form::Number(8),
        // MME-Group-ID
        "mME-Group-ID" | "servedGroupIDs" => Form::Number(16),
        // NRCellIdentity
        "nRCellIdentity" => Form::Number(36),
        // PLMNidentity
        "broadcastPLMNs" | "equivalentPLMNs" | "pLMN-Identity" | "pLMNIdentity"
        | "pLMNidentity" | "plmnListforQMC" | "servedPLMNs" | "servingPLMN" => Form::Plmn,
        // Port-Number
        "uDP-Port-Number" => Form::Number(16),
        // RAC
        "rAC" => Form::Number(8),
        // TAC
        "forbiddenTACs"
        | "tAC"
        | "tACList-In-LTE-NTN"
        | "tAListforMDT"
        | "tAListforQMC"
        | "uE-Location-Derived-TAC" => Form::Number(16),
        // TransportLayerAddress
        "dL-transportLayerAddress"
        | "eNBX2TransportLayerAddresses"
        | "gTPTLAa"
        | "iPsecTLA"
        | "traceCollectionEntityIPAddress"
        | "transportLayerAddress"
        | "uL-TransportLayerAddress" => Form::Address,
        // UL-NAS-Count
        "ul-NAS-Count" => Form::Number(5),
        _ => return None,
    })
}
pub(crate) fn ie_form(id: u16) -> Option<Form> {
    Some(match id {
        // MME-Group-ID
        223 => Form::Number(16),
        // PLMNidentity
        177 | 178 | 290 => Form::Plmn,
        // TransportLayerAddress
        131 | 155 | 184 | 193 | 328 | 340 => Form::Address,
        _ => return None,
    })
}
pub(crate) const ENUMERATED: &[&str] = &[
    "a2eventtriggered",
    "a2eventtriggered-periodic",
    "abstract-syntax-error-falsely-constructed-message",
    "abstract-syntax-error-ignore-and-notify",
    "abstract-syntax-error-reject",
    "activate-Muting",
    "all",
    "allowed",
    "asynchronous",
    "authentication-failure",
    "authorized",
    "available",
    "battery-powered",
    "battery-powered-not-rechargeable-or-replaceable",
    "both-uplink-and-downlink",
    "cSonly",
    "cdma2000",
    "cdma2000andutran",
    "cell-not-available",
    "change-of-serve-cell",
    "changed",
    "conditional",
    "control-processing-overload",
    "cs",
    "cs-fallback-high-priority",
    "cs-fallback-required",
    "cs-fallback-triggered",
    "csg-subscription-expiry",
    "dAPS-HO-accepted",
    "dAPS-HO-not-accepted",
    "dAPS-HO-required",
    "dL-Forwarding-proposed",
    "data-Forwarding-not-Possible",
    "deactivate-Muting",
    "delay-TolerantAccess",
    "detach",
    "direct",
    "directPathAvailable",
    "downlink",
    "dual-packets",
    "ecgi",
    "emergency",
    "encryption-and-or-integrity-protection-algorithms-not-supported",
    "epc-Forbiddden",
    "eps-to-5gs",
    "eutran-geo",
    "eutran-leo",
    "eutran-meo",
    "eutran-othersat",
    "extendedcoverage",
    "failure-in-radio-interface-procedure",
    "fiveGCForbidden",
    "fivegs-to-eps",
    "further-data-exists",
    "geran",
    "geranandutran",
    "gerantolte",
    "hOFailure",
    "hOSuccess",
    "hRPD",
    "handover-cancelled",
    "handover-desirable-for-radio-reason",
    "handoverPreparation",
    "hardware-failure",
    "hf1",
    "hf10",
    "hf1024",
    "hf12",
    "hf128",
    "hf14",
    "hf16",
    "hf2",
    "hf256",
    "hf32",
    "hf4",
    "hf512",
    "hf6",
    "hf64",
    "hf8",
    "hfhalf",
    "highPriorityAccess",
    "ho-failure-in-target-EPC-eNB-or-target-system",
    "ho-target-not-allowed",
    "hybrid",
    "iab-not-authorized",
    "ignore",
    "immediate-MDT",
    "immediate-MDT-and-Trace",
    "immediate-MDT-only",
    "includePSCell",
    "infinity",
    "initiating-message",
    "insufficient-ue-capabilities",
    "interaction-with-other-procedure",
    "interrat-redirection",
    "intralte",
    "invalid-CSG-Id",
    "invalid-qos-combination",
    "kHz120",
    "kHz15",
    "kHz240",
    "kHz30",
    "kHz480",
    "kHz60",
    "kHz960",
    "large",
    "load-balancing-tau-required",
    "logged-MBSFN-MDT",
    "logged-MDT",
    "logged-MDT-only",
    "long-time",
    "lte-m",
    "ltetogeran",
    "ltetoutran",
    "m10",
    "m1000",
    "m120",
    "m180",
    "m20",
    "m200",
    "m350",
    "m40",
    "m400",
    "m50",
    "m500",
    "m60",
    "m700",
    "m80",
    "m90",
    "mandatory",
    "mapped",
    "mappedFrom5G",
    "maximum",
    "maximum-bearer-pre-emption-rate-exceeded",
    "maximumWithoutVendorSpecificExtension",
    "may-trigger-pre-emption",
    "medium",
    "mediumWithoutVendorSpecificExtension",
    "member",
    "message-not-compatible-with-receiver-state",
    "min1",
    "min12",
    "min30",
    "min6",
    "min60",
    "minimum",
    "minimumWithoutVendorSpecificExtension",
    "missing",
    "mo-Data",
    "mo-ExceptionData",
    "mo-Signalling",
    "mo-VoiceCall",
    "mobile",
    "ms0",
    "ms100",
    "ms1000",
    "ms10000",
    "ms1024",
    "ms10240",
    "ms120",
    "ms128",
    "ms1280",
    "ms150",
    "ms160",
    "ms2048",
    "ms20480",
    "ms240",
    "ms256",
    "ms2560",
    "ms30",
    "ms300",
    "ms30720",
    "ms320",
    "ms40",
    "ms40960",
    "ms480",
    "ms50",
    "ms500",
    "ms512",
    "ms5120",
    "ms60",
    "ms61440",
    "ms64",
    "ms640",
    "ms70",
    "ms750",
    "ms80",
    "ms90",
    "mt-Access",
    "multiple-E-RAB-ID-instances",
    "multiple-packets",
    "n26-interface-not-available",
    "nR",
    "nRrestrictedin5GS",
    "nRrestrictedinEPSasSecondaryRAT",
    "native",
    "nbiot",
    "nbiot-geo",
    "nbiot-leo",
    "nbiot-meo",
    "nbiot-othersat",
    "no-further-data",
    "no-radio-resources-available-in-target-cell",
    "no-restriction",
    "non-IP",
    "normal-release",
    "not-accept-mo-data-or-delay-tolerant-access-from-CP-CIoT",
    "not-allowed",
    "not-authorized",
    "not-battery-powered",
    "not-enough-user-plane-processing-resources",
    "not-member",
    "not-needed",
    "not-performed",
    "not-pre-emptable",
    "not-restricted",
    "not-supported",
    "not-supported-QCI-value",
    "not-understood",
    "notPossible",
    "notify",
    "notifySource",
    "om-intervention",
    "ondemand",
    "onexRTT",
    "optional",
    "p00",
    "p05",
    "p10",
    "p100",
    "p15",
    "p20",
    "p25",
    "p30",
    "p35",
    "p40",
    "p45",
    "p50",
    "p55",
    "p60",
    "p65",
    "p70",
    "p75",
    "p80",
    "p85",
    "p90",
    "p95",
    "pSandCS",
    "partial-handover",
    "performed",
    "periodic",
    "periodically",
    "permit-emergency-sessions-and-mobile-terminated-services-only",
    "permit-high-priority-sessions-and-exception-reporting-and-mobile-terminated-services-only",
    "permit-high-priority-sessions-and-mobile-terminated-services-only",
    "possible",
    "pre-emptable",
    "preferred",
    "priolevel1",
    "priolevel2",
    "priolevel3",
    "priolevel4",
    "priolevel5",
    "priolevel6",
    "priolevel7",
    "priolevel8",
    "ps",
    "ps-service-not-available",
    "qMC-for-MTSI-service",
    "qMC-for-streaming-service",
    "r1",
    "r16",
    "r2",
    "r32",
    "r4",
    "r64",
    "r8",
    "radio-connection-with-ue-lost",
    "radio-resources-not-available",
    "redirection-towards-1xRTT",
    "reduce-load-in-serving-cell",
    "reject",
    "reject-delay-tolerant-access",
    "reject-non-emergency-mo-dt",
    "reject-rrc-cr-signalling",
    "release-due-to-discontinuous-coverage",
    "release-due-to-eutran-generated-reason",
    "release-due-to-pre-emption",
    "requested",
    "required",
    "reset-all",
    "resource-optimisation-handover",
    "restricted",
    "restriction",
    "rinfinity",
    "s1",
    "s1-inter-system-handover-triggered",
    "s1-intra-system-handover-triggered",
    "s10",
    "s11",
    "s12",
    "s13",
    "s14",
    "s15",
    "s16",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "same",
    "sec120",
    "sec15",
    "sec180",
    "sec30",
    "sec60",
    "sec90",
    "semantic-error",
    "setup",
    "shall-not-trigger-pre-emption",
    "single-packet",
    "small",
    "stationary",
    "statistics",
    "stop-change-of-serve-cell",
    "subscription-information",
    "successful-handover",
    "successful-outcome",
    "supported",
    "synchronous",
    "tS1relocoverall-expiry",
    "tS1relocprep-expiry",
    "time-Synchronisation-Info",
    "time-critical-handover",
    "transfer-syntax-error",
    "transport-resource-unavailable",
    "true",
    "tx2relocoverall-expiry",
    "uE-not-in-PLMN-serving-area",
    "ue-not-available-for-ps-service",
    "ues-retained",
    "unavailable",
    "unknown-E-RAB-ID",
    "unknown-PLMN",
    "unknown-enb-ue-s1ap-id",
    "unknown-mme-ue-s1ap-id",
    "unknown-pair-ue-s1ap-id",
    "unknown-targetID",
    "unlicensed",
    "unlicensed-restricted",
    "unspecified",
    "unsuccessfull-outcome",
    "up-integrity-protection-not-possible",
    "uplink",
    "user-inactivity",
    "utran",
    "utrantolte",
    "v1024",
    "v10s",
    "v128",
    "v1s",
    "v20s",
    "v256",
    "v2s",
    "v32",
    "v512",
    "v5s",
    "v60s",
    "v64",
    "verysmall",
    "voice",
    "x2-handover-triggered",
    "x2TNL-Configuration-Info",
];
use crate::inspect::open_types;
open_types! { crate::s1ap::s1_ap_containers::ProtocolIEField { value } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolIEContainer { 0 } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolExtensionField { extension_value } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolExtensionContainer { 0 } }
open_types! { crate::s1ap::s1_ap_ies::AdditionalGUTI { g_ummei, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AdditionalCSFallbackIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::AdditionalRRMPriorityIndex {} }
open_types! { crate::s1ap::s1_ap_ies::AerialUEsubscriptionInformation {} }
open_types! { crate::s1ap::s1_ap_ies::AllocationAndRetentionPriority { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AreaScopeOfMDT { cellBased, tABased, tAIBased } else { pLMNWide } }
open_types! { crate::s1ap::s1_ap_ies::AreaScopeOfQMC { cellBased, tABased, tAIBased, pLMNAreaBased } else {} }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForCECapableUEs { cell_identifier_and_celevel_for_cecapable_ues, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForPaging { assistance_data_for_recommended_cells, assistance_data_for_cecapable_ues, paging_attempt_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForRecommendedCells { recommended_cells_for_paging, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearerType {} }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToDLDiscardingItem { d_l_discarding, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToDLDiscardingList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToEarlyStatusTransferItem { d_lcount_pdcp_snlength, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToEarlyStatusTransferList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToStatusTransferItem { u_l_countvalue, d_l_countvalue, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToStatusTransferList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BluetoothMeasurementConfiguration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BroadcastCancelledAreaList { cellID_Cancelled, tAI_Cancelled, emergencyAreaID_Cancelled } else {} }
open_types! { crate::s1ap::s1_ap_ies::BroadcastCompletedAreaList { cellID_Broadcast, tAI_Broadcast, emergencyAreaID_Broadcast } else {} }
open_types! { crate::s1ap::s1_ap_ies::CEModeBRestricted {} }
open_types! { crate::s1ap::s1_ap_ies::CEModeBSupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::CGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CNDomain {} }
open_types! { crate::s1ap::s1_ap_ies::CNTypeRestrictions { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CNTypeRestrictionsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTValueExtended { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTvalue { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTvaluePDCPSNlength18 { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CSFallbackIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::CSGId {} }
open_types! { crate::s1ap::s1_ap_ies::CSGIdList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CSGIdListItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CSGMembershipStatus {} }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinEAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinEAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinTAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinTAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::Cause {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000HORequiredIndication {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000HOStatus {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000OneXRAND {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000OneXSRVCCInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000PDU {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000RATType {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000SectorID {} }
open_types! { crate::s1ap::s1_ap_ies::CellAccessMode {} }
open_types! { crate::s1ap::s1_ap_ies::CellBasedMDT { cell_id_listfor_mdt, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellBasedQMC { cell_id_listfor_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIDBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIDBroadcastItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIDCancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIDCancelledItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIdListforMDT { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIdListforQMC { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIdentifierAndCELevelForCECapableUEs { global_cell_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellType { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CoarseUELocation {} }
open_types! { crate::s1ap::s1_ap_ies::CoarseUELocationRequested {} }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinEAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinEAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinTAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinTAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ConcurrentWarningMessageIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ConnectedengNBItem { supported_tas, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ConnectedengNBList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ContextatSource { source_ng_ran_node_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CorrelationID {} }
open_types! { crate::s1ap::s1_ap_ies::CoverageLevel {} }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnostics { i_es_criticality_diagnostics, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnosticsIEItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnosticsIEList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::DAPSRequestInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfoItem { d_apsresponse_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfoList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::DCNID {} }
open_types! { crate::s1ap::s1_ap_ies::DLCPSecurityInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DLCOUNTPDCPSNlength { dLCOUNTValuePDCP_SNlength12, dLCOUNTValuePDCP_SNlength15, dLCOUNTValuePDCP_SNlength18 } else {} }
open_types! { crate::s1ap::s1_ap_ies::DLDiscarding { discardDLCOUNTValuePDCP_SNlength12, discardDLCOUNTValuePDCP_SNlength15, discardDLCOUNTValuePDCP_SNlength18 } else {} }
open_types! { crate::s1ap::s1_ap_ies::DLNASPDUDeliveryAckRequest {} }
open_types! { crate::s1ap::s1_ap_ies::DataForwardingNotPossible {} }
open_types! { crate::s1ap::s1_ap_ies::DataCodingScheme {} }
open_types! { crate::s1ap::s1_ap_ies::DataSize {} }
open_types! { crate::s1ap::s1_ap_ies::DirectForwardingPathAvailability {} }
open_types! { crate::s1ap::s1_ap_ies::ERABInformationList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABInformationListItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABLevelQoSParameters { allocation_retention_priority, gbr_qos_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABSecurityResultItem { security_result, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABSecurityResultList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABUsageReportItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABUsageReportList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EUTRANTraceID {} }
open_types! { crate::s1ap::s1_ap_ies::ECGI_List { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ECGIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ECGIListForRestart { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EDTSession {} }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONConfigurationTransfer { transfertype, s_oninformation, x2_tnlconfig_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONTransferType { request, reply } else {} }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONeNBIdentification { globale_nbid, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONengNBIdentification { globaleng_nbid, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCTransferTypeReply { sourceeng_nb, targete_nb, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCTransferTypeRequest { sourcee_nb, targeteng_nb, targete_nb, associated_tai, broadcast5_gstai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBEarlyStatusTransferTransparentContainer { bearers_subject_to_early_status_transfer_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBStatusTransferTransparentContainer { bearers_subject_to_status_transfer_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBUES1APID {} }
open_types! { crate::s1ap::s1_ap_ies::ENBIndirectX2TransportLayerAddresses {} }
open_types! { crate::s1ap::s1_ap_ies::ENBX2ExtTLA { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBX2ExtTLAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ENBname {} }
open_types! { crate::s1ap::s1_ap_ies::EUTRANCGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EUTRANRoundTripDelayEstimationInfo {} }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDBroadcastItem { completed_cellin_eai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDCancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDCancelledItem { cancelled_cellin_eai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDListForRestart {} }
open_types! { crate::s1ap::s1_ap_ies::EmergencyIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::EndIndication {} }
open_types! { crate::s1ap::s1_ap_ies::EnhancedCoverageRestricted {} }
open_types! { crate::s1ap::s1_ap_ies::EthernetType {} }
open_types! { crate::s1ap::s1_ap_ies::EventL1LoggedMDTConfig { l1_threshold, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EventTrigger { eventL1LoggedMDTConfig, choice_Extensions } else { outOfCoverage } }
open_types! { crate::s1ap::s1_ap_ies::ExpectedUEActivityBehaviour { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ExpectedUEBehaviour { expected_activity, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ExtendedUEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::ExtendedBitRate {} }
open_types! { crate::s1ap::s1_ap_ies::ExtendedRepetitionPeriod {} }
open_types! { crate::s1ap::s1_ap_ies::FiveGSTAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenLAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenLAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenTAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenTAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GBRQosInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GERANCellID { l_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GNB { global_g_nb_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEIType {} }
open_types! { crate::s1ap::s1_ap_ies::GWContextReleaseIndication {} }
open_types! { crate::s1ap::s1_ap_ies::GlobalENBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GlobalGNBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GlobalRANNODEID { gNB, ng_eNB } else {} }
open_types! { crate::s1ap::s1_ap_ies::GlobalEnGNBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::HandoverFlag {} }
open_types! { crate::s1ap::s1_ap_ies::HandoverRestrictionList { forbidden_tas, forbidden_las, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::HandoverType {} }
open_types! { crate::s1ap::s1_ap_ies::IABAuthorized {} }
open_types! { crate::s1ap::s1_ap_ies::IABNodeIndication {} }
open_types! { crate::s1ap::s1_ap_ies::IABSupported {} }
open_types! { crate::s1ap::s1_ap_ies::IMSvoiceEPSfallbackfrom5G {} }
open_types! { crate::s1ap::s1_ap_ies::ImmediateMDT { m1thresholdevent_a2, m1periodic_reporting, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InformationOnRecommendedCellsAndENBsForPaging { recommended_cells_for_paging, recommend_enbs_for_paging, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementParameters { inter_system_measurement_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::IntersystemMeasurementConfiguration { inter_system_measurement_parameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::IntersystemSONConfigurationTransfer {} }
open_types! { crate::s1ap::s1_ap_ies::KillAllWarningMessages {} }
open_types! { crate::s1ap::s1_ap_ies::LAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LHNID {} }
open_types! { crate::s1ap::s1_ap_ies::LPPaPDU {} }
open_types! { crate::s1ap::s1_ap_ies::LTEMIndication {} }
open_types! { crate::s1ap::s1_ap_ies::LTENTNTAIInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedCellItem { e_UTRAN_Cell } else { uTRAN_Cell, gERAN_Cell, nG_RAN_Cell } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedEUTRANCellInformation { global_cell_id, cell_type, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedPSCellInformation { p_scell_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedPSCellList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ListeningSubframePattern { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMBSFNMDT { m_bsfn_result_to_log, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMDT { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMDTTrigger { eventTrigger } else { periodical } }
open_types! { crate::s1ap::s1_ap_ies::M1PeriodicReporting { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M1ThresholdEventA2 { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M3Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M4Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M4ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M5Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M5ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M6Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M6ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M7Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M7ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::MBSFNResultToLog { 0 } }
open_types! { crate::s1ap::s1_ap_ies::MBSFNResultToLogInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::MDTConfiguration { area_scope_of_mdt, m_dtmode, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::MDTConfigurationNR {} }
open_types! { crate::s1ap::s1_ap_ies::MDTLocationInfo {} }
open_types! { crate::s1ap::s1_ap_ies::MDTMode { immediateMDT, loggedMDT, mDTMode_Extension } else {} }
open_types! { crate::s1ap::s1_ap_ies::MDTPLMNList {} }
open_types! { crate::s1ap::s1_ap_ies::MMEGroupID {} }
open_types! { crate::s1ap::s1_ap_ies::MMEUES1APID {} }
open_types! { crate::s1ap::s1_ap_ies::MMEPagingTarget { global_ENB_ID, tAI } else {} }
open_types! { crate::s1ap::s1_ap_ies::MMERelaySupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::MMEname {} }
open_types! { crate::s1ap::s1_ap_ies::MSClassmark2 {} }
open_types! { crate::s1ap::s1_ap_ies::MSClassmark3 {} }
open_types! { crate::s1ap::s1_ap_ies::ManagementBasedMDTAllowed {} }
open_types! { crate::s1ap::s1_ap_ies::MaskedIMEISV {} }
open_types! { crate::s1ap::s1_ap_ies::MeasurementThresholdL1LoggedMDT { choice_Extensions } else { threshold_RSRP, threshold_RSRQ } }
open_types! { crate::s1ap::s1_ap_ies::MessageIdentifier {} }
open_types! { crate::s1ap::s1_ap_ies::MobilityInformation {} }
open_types! { crate::s1ap::s1_ap_ies::MutingAvailabilityIndication {} }
open_types! { crate::s1ap::s1_ap_ies::MutingPatternInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NASPDU {} }
open_types! { crate::s1ap::s1_ap_ies::NASSecurityParametersfromEUTRAN {} }
open_types! { crate::s1ap::s1_ap_ies::NASSecurityParameterstoEUTRAN {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTDefaultPagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTPagingEDRXInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NBIoTPagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTRLFReportContainer {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTUEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::NGENB { global_ng_e_nb_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRCGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRUESecurityCapabilities { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRUESidelinkAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRV2XServicesAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRrestrictionin5GS {} }
open_types! { crate::s1ap::s1_ap_ies::NRrestrictioninEPSasSecondaryRAT {} }
open_types! { crate::s1ap::s1_ap_ies::NotifySourceeNB {} }
open_types! { crate::s1ap::s1_ap_ies::NumberofBroadcastRequest {} }
open_types! { crate::s1ap::s1_ap_ies::OverloadResponse {} }
open_types! { crate::s1ap::s1_ap_ies::PC5FlowBitRates { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSFlowItem { pc5_flow_bit_rates, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSFlowList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSParameters { pc5_qo_sflow_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PLMNAreaBasedQMC { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PLMNidentity {} }
open_types! { crate::s1ap::s1_ap_ies::PSServiceNotAvailable {} }
open_types! { crate::s1ap::s1_ap_ies::PSCellInformation { n_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PWSfailedECGIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::PacketLossRate {} }
open_types! { crate::s1ap::s1_ap_ies::PagingEDRXInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PagingAttemptInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PagingCause {} }
open_types! { crate::s1ap::s1_ap_ies::PagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::PagingPriority {} }
open_types! { crate::s1ap::s1_ap_ies::PendingDataIndication {} }
open_types! { crate::s1ap::s1_ap_ies::PrivacyIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ProSeAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ProSeUEtoNetworkRelaying {} }
open_types! { crate::s1ap::s1_ap_ies::RACSIndication {} }
open_types! { crate::s1ap::s1_ap_ies::RATRestrictions { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RATRestrictionsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RATType {} }
open_types! { crate::s1ap::s1_ap_ies::RIMRoutingAddress { gERAN_Cell_ID, targetRNC_ID } else { eHRPD_Sector_ID } }
open_types! { crate::s1ap::s1_ap_ies::RIMTransfer { r_imrouting_address, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RLFReportInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RRCEstablishmentCause {} }
open_types! { crate::s1ap::s1_ap_ies::ReceiveStatusOfULPDCPSDUsExtended {} }
open_types! { crate::s1ap::s1_ap_ies::ReceiveStatusOfULPDCPSDUsPDCPSNlength18 {} }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellItem { e_utran_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellsForPaging { recommended_cell_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBItem { m_mepaging_target, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBsForPaging { recommended_enblist, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RelativeMMECapacity {} }
open_types! { crate::s1ap::s1_ap_ies::RelayNodeIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::RepetitionPeriod {} }
open_types! { crate::s1ap::s1_ap_ies::RequestType { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RequestTypeAdditionalInfo {} }
open_types! { crate::s1ap::s1_ap_ies::RequestedTNLInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RoutingID {} }
open_types! { crate::s1ap::s1_ap_ies::STMSI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONConfigurationTransfer { targete_nb_id, sourcee_nb_id, s_oninformation, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONInformation { sONInformationReply, sONInformation_Extension } else { sONInformationRequest } }
open_types! { crate::s1ap::s1_ap_ies::SONInformationReply { x2_tnlconfiguration_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONInformationReport { rLFReportInformation } else {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCHOIndication {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCOperationNotPossible {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCOperationPossible {} }
open_types! { crate::s1ap::s1_ap_ies::ScheduledCommunicationTime { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageReportItem { e_rabusage_report_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageReportList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageRequest {} }
open_types! { crate::s1ap::s1_ap_ies::SecurityContext { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecurityIndication { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecurityKey {} }
open_types! { crate::s1ap::s1_ap_ies::SecurityResult { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasConfigNameItem { sensor_name_config, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasConfigNameList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasurementConfiguration { sensor_meas_config_name_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorNameConfig { choice_Extensions } else { uncompensatedBarometricConfig } }
open_types! { crate::s1ap::s1_ap_ies::SerialNumber {} }
open_types! { crate::s1ap::s1_ap_ies::ServedDCNs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ServedDCNsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ServedGUMMEIs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ServedGUMMEIsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ServiceType {} }
open_types! { crate::s1ap::s1_ap_ies::SourceToTargetTransparentContainer {} }
open_types! { crate::s1ap::s1_ap_ies::SourceNgRanNodeID { global_ran_node_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SourceNodeID { sourceNgRanNode_ID, sourceNodeID_Extension } else {} }
open_types! { crate::s1ap::s1_ap_ies::SourceeNBID { global_enb_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SourceeNBToTargeteNBTransparentContainer { e_rabinformation_list, target_cell_id, u_e_history_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SubscriberProfileIDforRFP {} }
open_types! { crate::s1ap::s1_ap_ies::SubscriptionBasedUEDifferentiationInfo { scheduled_communication_time, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SupportedTAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SupportedTAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SynchronisationInformation { listening_subframe_pattern, aggressore_cgi_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TABasedMDT { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TABasedQMC { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIBroadcastItem { t_ai, completed_cellin_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAICancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAICancelledItem { t_ai, cancelled_cellin_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBasedMDT { t_ailistfor_mdt, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBasedQMC { t_ailistfor_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIListForRestart { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforMDT { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforQMC { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforWarning { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TargetToSourceTransparentContainer {} }
open_types! { crate::s1ap::s1_ap_ies::TargetID { targeteNB_ID, targetRNC_ID, cGI, targetgNgRanNode_ID } else {} }
open_types! { crate::s1ap::s1_ap_ies::TargetNgRanNodeID { global_ran_node_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargetRNCID { l_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargeteNBID { global_enb_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargeteNBToSourceeNBTransparentContainer { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeUEStayedInCellEnhancedGranularity {} }
open_types! { crate::s1ap::s1_ap_ies::TimeBasedHandoverInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeRefDistribution {} }
open_types! { crate::s1ap::s1_ap_ies::TimeSinceSecondaryNodeRelease {} }
open_types! { crate::s1ap::s1_ap_ies::TimeSynchronisationInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeToWait {} }
open_types! { crate::s1ap::s1_ap_ies::TraceActivation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TrafficLoadReductionIndication {} }
open_types! { crate::s1ap::s1_ap_ies::TransportInformation {} }
open_types! { crate::s1ap::s1_ap_ies::TransportLayerAddress {} }
open_types! { crate::s1ap::s1_ap_ies::TunnelInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEApplicationLayerMeasurementCapability {} }
open_types! { crate::s1ap::s1_ap_ies::UEHistoryInformation { 0 } }
open_types! { crate::s1ap::s1_ap_ies::UEHistoryInformationFromTheUE {} }
open_types! { crate::s1ap::s1_ap_ies::UERetentionInformation {} }
open_types! { crate::s1ap::s1_ap_ies::UES1APIDPair { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UES1APIDs { uE_S1AP_ID_pair } else { mME_UE_S1AP_ID } }
open_types! { crate::s1ap::s1_ap_ies::UEUsageType {} }
open_types! { crate::s1ap::s1_ap_ies::UEAssociatedLogicalS1ConnectionItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEAppLayerMeasConfig { area_scope_of_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UECapabilityInfoRequest {} }
open_types! { crate::s1ap::s1_ap_ies::UEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::UEPagingID { s_TMSI } else { iMSI } }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapability {} }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapabilityForPaging {} }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapabilityID {} }
open_types! { crate::s1ap::s1_ap_ies::UESecurityCapabilities { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UESidelinkAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEUserPlaneCIoTSupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ULCPSecurityInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::URIAddress {} }
open_types! { crate::s1ap::s1_ap_ies::UnlicensedSpectrumRestriction {} }
open_types! { crate::s1ap::s1_ap_ies::UserLocationInformation { eutran_cgi, tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::V2XServicesAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::VoiceSupportMatchIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::WLANMeasurementConfiguration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::WUSAssistanceInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::WarningAreaCoordinates {} }
open_types! { crate::s1ap::s1_ap_ies::WarningAreaList { cellIDList, trackingAreaListforWarning } else { emergencyAreaIDList } }
open_types! { crate::s1ap::s1_ap_ies::WarningMessageContents {} }
open_types! { crate::s1ap::s1_ap_ies::WarningSecurityInfo {} }
open_types! { crate::s1ap::s1_ap_ies::WarningType {} }
open_types! { crate::s1ap::s1_ap_ies::X2TNLConfigurationInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::CSGMembershipInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::CellTrafficTrace { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ConnectionEstablishmentIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DeactivateTrace { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkNASTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkNonUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkS1cdma2000tunnelling { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABAdmittedItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABAdmittedList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABDataForwardingItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeItemResumeReq { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeItemResumeRes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeListResumeReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeListResumeRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToSetupItemHOReqAck { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedtoSetupListHOReqAck { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModificationConfirm { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModificationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyItemBearerModConf { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyItemBearerModRes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyListBearerModConf { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyListBearerModRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABNotToBeModifiedItemBearerModInd { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABNotToBeModifiedListBearerModInd { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseItemBearerRelComp { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseListBearerRelComp { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupItemBearerSURes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupItemCtxtSURes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupListBearerSURes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupListCtxtSURes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSubjecttoDataForwardingList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedItemBearerModInd { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedItemBearerModReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedListBearerModInd { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedListBearerModReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemBearerSUReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemCtxtSUReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemHOReq { e_rablevel_qos_parameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListBearerSUReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListCtxtSUReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListHOReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedDLItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedDLList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedULItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedULList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeUpdatedItem { security_indication, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeUpdatedList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBCPRelocationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdate { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdateAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdateFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBDirectInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBEarlyStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ErrorIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCancel { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCancelAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverNotify { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverPreparationFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequestAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequired { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverSuccess { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialUEMessage { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InterSystemInformationTransferType { rIMTransfer } else {} }
open_types! { crate::s1ap::s1_ap_pdu_contents::KillRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::KillResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReportingControl { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReportingFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMECPRelocationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdate { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdateAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdateFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEDirectInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEEarlyStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::NASDeliveryIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::NASNonDeliveryIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::OverloadStart { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::OverloadStop { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PWSFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PWSRestartIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::Paging { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequestAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequestFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::AnonymousPrivateMessagePrivateIEs { value } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PrivateMessagePrivateIEs { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PrivateMessage { private_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::RerouteNASRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::Reset { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ResetAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ResetType { partOfS1_Interface } else { s1_Interface } }
open_types! { crate::s1ap::s1_ap_pdu_contents::RetrieveUEInformation { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::SecondaryRATDataUsageReport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TAIItem { t_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TAIList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TraceFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TraceStart { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEAssociatedLogicalS1ConnectionListRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEAssociatedLogicalS1ConnectionListResAck { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UECapabilityInfoIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationConfirm { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseComplete { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextSuspendRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextSuspendResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityIDMappingRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityIDMappingResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityMatchRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityMatchResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkNASTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkNonUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkS1cdma2000tunnelling { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::WriteReplaceWarningRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::WriteReplaceWarningResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::InitiatingMessage { value } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::S1APPDU { initiatingMessage, successfulOutcome, unsuccessfulOutcome } else {} }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::SuccessfulOutcome { value } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::UnsuccessfulOutcome { value } }
