// Auto-generated by build/inspection.rs from ASN.1; do not edit.
use crate::inspect::{Form, Typed, transfers};
pub(crate) use crate::registry::{IE_NAMES, MESSAGES, ie, ie_contents};
pub(crate) const PROTOCOL: &str = "S1AP";
pub(crate) const ROOT: &str = "s1ap";
transfers! {}
pub(crate) fn member_form(name: &str) -> Option<Form> {
    Some(match name {
        // CI
        "cI" => Form::Number(16),
        // CellIdentity
        "cell-ID" => Form::Number(28),
        // FiveGSTAC
        "fiveGSTAC" => Form::Number(24),
        // GTP-TEID
        "dL-GTP-TEID" | "dL-gTP-TEID" | "gTP-TEID" | "uL-GTP-TEID" => Form::Number(32),
        // IMSI
        "iMSI" => Form::Digits,
        // LAC
        "forbiddenLACs" | "lAC" => Form::Number(16),
        // M-TMSI
        "m-TMSI" => Form::Number(32),
        // MME-Code
        "mME-Code" | "mMEC" | "servedMMECs" => Form::Number(8),
        // MME-Group-ID
        "mME-Group-ID" | "servedGroupIDs" => Form::Number(16),
        // NRCellIdentity
        "nRCellIdentity" => Form::Number(36),
        // PLMNidentity
        "broadcastPLMNs" | "equivalentPLMNs" | "pLMN-Identity" | "pLMNIdentity"
        | "pLMNidentity" | "plmnListforQMC" | "servedPLMNs" | "servingPLMN" => Form::Plmn,
        // Port-Number
        "uDP-Port-Number" => Form::Number(16),
        // RAC
        "rAC" => Form::Number(8),
        // TAC
        "forbiddenTACs"
        | "tAC"
        | "tACList-In-LTE-NTN"
        | "tAListforMDT"
        | "tAListforQMC"
        | "uE-Location-Derived-TAC" => Form::Number(16),
        // TransportLayerAddress
        "dL-transportLayerAddress"
        | "eNBX2TransportLayerAddresses"
        | "gTPTLAa"
        | "iPsecTLA"
        | "traceCollectionEntityIPAddress"
        | "transportLayerAddress"
        | "uL-TransportLayerAddress" => Form::Address,
        // UL-NAS-Count
        "ul-NAS-Count" => Form::Number(5),
        _ => return None,
    })
}
pub(crate) fn ie_form(id: u16) -> Option<Form> {
    Some(match id {
        // MME-Group-ID
        223 => Form::Number(16),
        // PLMNidentity
        177 | 178 | 290 => Form::Plmn,
        // TransportLayerAddress
        131 | 155 | 184 | 193 | 328 | 340 => Form::Address,
        _ => return None,
    })
}
pub(crate) const ENUMERATED: &[&str] = &[
    "a2eventtriggered",
    "a2eventtriggered-periodic",
    "abstract-syntax-error-falsely-constructed-message",
    "abstract-syntax-error-ignore-and-notify",
    "abstract-syntax-error-reject",
    "activate-Muting",
    "all",
    "allowed",
    "asynchronous",
    "authentication-failure",
    "authorized",
    "available",
    "battery-powered",
    "battery-powered-not-rechargeable-or-replaceable",
    "both-uplink-and-downlink",
    "cSonly",
    "cdma2000",
    "cdma2000andutran",
    "cell-not-available",
    "change-of-serve-cell",
    "changed",
    "conditional",
    "control-processing-overload",
    "cs",
    "cs-fallback-high-priority",
    "cs-fallback-required",
    "cs-fallback-triggered",
    "csg-subscription-expiry",
    "dAPS-HO-accepted",
    "dAPS-HO-not-accepted",
    "dAPS-HO-required",
    "dL-Forwarding-proposed",
    "data-Forwarding-not-Possible",
    "deactivate-Muting",
    "delay-TolerantAccess",
    "detach",
    "direct",
    "directPathAvailable",
    "downlink",
    "dual-packets",
    "ecgi",
    "emergency",
    "encryption-and-or-integrity-protection-algorithms-not-supported",
    "epc-Forbiddden",
    "eps-to-5gs",
    "eutran-geo",
    "eutran-leo",
    "eutran-meo",
    "eutran-othersat",
    "extendedcoverage",
    "failure-in-radio-interface-procedure",
    "fiveGCForbidden",
    "fivegs-to-eps",
    "further-data-exists",
    "geran",
    "geranandutran",
    "gerantolte",
    "hOFailure",
    "hOSuccess",
    "hRPD",
    "handover-cancelled",
    "handover-desirable-for-radio-reason",
    "handoverPreparation",
    "hardware-failure",
    "hf1",
    "hf10",
    "hf1024",
    "hf12",
    "hf128",
    "hf14",
    "hf16",
    "hf2",
    "hf256",
    "hf32",
    "hf4",
    "hf512",
    "hf6",
    "hf64",
    "hf8",
    "hfhalf",
    "highPriorityAccess",
    "ho-failure-in-target-EPC-eNB-or-target-system",
    "ho-target-not-allowed",
    "hybrid",
    "iab-not-authorized",
    "ignore",
    "immediate-MDT",
    "immediate-MDT-and-Trace",
    "immediate-MDT-only",
    "includePSCell",
    "infinity",
    "initiating-message",
    "insufficient-ue-capabilities",
    "interaction-with-other-procedure",
    "interrat-redirection",
    "intralte",
    "invalid-CSG-Id",
    "invalid-qos-combination",
    "kHz120",
    "kHz15",
    "kHz240",
    "kHz30",
    "kHz480",
    "kHz60",
    "kHz960",
    "large",
    "load-balancing-tau-required",
    "logged-MBSFN-MDT",
    "logged-MDT",
    "logged-MDT-only",
    "long-time",
    "lte-m",
    "ltetogeran",
    "ltetoutran",
    "m10",
    "m1000",
    "m120",
    "m180",
    "m20",
    "m200",
    "m350",
    "m40",
    "m400",
    "m50",
    "m500",
    "m60",
    "m700",
    "m80",
    "m90",
    "mandatory",
    "mapped",
    "mappedFrom5G",
    "maximum",
    "maximum-bearer-pre-emption-rate-exceeded",
    "maximumWithoutVendorSpecificExtension",
    "may-trigger-pre-emption",
    "medium",
    "mediumWithoutVendorSpecificExtension",
    "member",
    "message-not-compatible-with-receiver-state",
    "min1",
    "min12",
    "min30",
    "min6",
    "min60",
    "minimum",
    "minimumWithoutVendorSpecificExtension",
    "missing",
    "mo-Data",
    "mo-ExceptionData",
    "mo-Signalling",
    "mo-VoiceCall",
    "mobile",
    "ms0",
    "ms100",
    "ms1000",
    "ms10000",
    "ms1024",
    "ms10240",
    "ms120",
    "ms128",
    "ms1280",
    "ms150",
    "ms160",
    "ms2048",
    "ms20480",
    "ms240",
    "ms256",
    "ms2560",
    "ms30",
    "ms300",
    "ms30720",
    "ms320",
    "ms40",
    "ms40960",
    "ms480",
    "ms50",
    "ms500",
    "ms512",
    "ms5120",
    "ms60",
    "ms61440",
    "ms64",
    "ms640",
    "ms70",
    "ms750",
    "ms80",
    "ms90",
    "mt-Access",
    "multiple-E-RAB-ID-instances",
    "multiple-packets",
    "n26-interface-not-available",
    "nR",
    "nRrestrictedin5GS",
    "nRrestrictedinEPSasSecondaryRAT",
    "native",
    "nbiot",
    "nbiot-geo",
    "nbiot-leo",
    "nbiot-meo",
    "nbiot-othersat",
    "no-further-data",
    "no-radio-resources-available-in-target-cell",
    "no-restriction",
    "non-IP",
    "normal-release",
    "not-accept-mo-data-or-delay-tolerant-access-from-CP-CIoT",
    "not-allowed",
    "not-authorized",
    "not-battery-powered",
    "not-enough-user-plane-processing-resources",
    "not-member",
    "not-needed",
    "not-performed",
    "not-pre-emptable",
    "not-restricted",
    "not-supported",
    "not-supported-QCI-value",
    "not-understood",
    "notPossible",
    "notify",
    "notifySource",
    "om-intervention",
    "ondemand",
    "onexRTT",
    "optional",
    "p00",
    "p05",
    "p10",
    "p100",
    "p15",
    "p20",
    "p25",
    "p30",
    "p35",
    "p40",
    "p45",
    "p50",
    "p55",
    "p60",
    "p65",
    "p70",
    "p75",
    "p80",
    "p85",
    "p90",
    "p95",
    "pSandCS",
    "partial-handover",
    "performed",
    "periodic",
    "periodically",
    "permit-emergency-sessions-and-mobile-terminated-services-only",
    "permit-high-priority-sessions-and-exception-reporting-and-mobile-terminated-services-only",
    "permit-high-priority-sessions-and-mobile-terminated-services-only",
    "possible",
    "pre-emptable",
    "preferred",
    "priolevel1",
    "priolevel2",
    "priolevel3",
    "priolevel4",
    "priolevel5",
    "priolevel6",
    "priolevel7",
    "priolevel8",
    "ps",
    "ps-service-not-available",
    "qMC-for-MTSI-service",
    "qMC-for-streaming-service",
    "r1",
    "r16",
    "r2",
    "r32",
    "r4",
    "r64",
    "r8",
    "radio-connection-with-ue-lost",
    "radio-resources-not-available",
    "redirection-towards-1xRTT",
    "reduce-load-in-serving-cell",
    "reject",
    "reject-delay-tolerant-access",
    "reject-non-emergency-mo-dt",
    "reject-rrc-cr-signalling",
    "release-due-to-discontinuous-coverage",
    "release-due-to-eutran-generated-reason",
    "release-due-to-pre-emption",
    "requested",
    "required",
    "reset-all",
    "resource-optimisation-handover",
    "restricted",
    "restriction",
    "rinfinity",
    "s1",
    "s1-inter-system-handover-triggered",
    "s1-intra-system-handover-triggered",
    "s10",
    "s11",
    "s12",
    "s13",
    "s14",
    "s15",
    "s16",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "same",
    "sec120",
    "sec15",
    "sec180",
    "sec30",
    "sec60",
    "sec90",
    "semantic-error",
    "setup",
    "shall-not-trigger-pre-emption",
    "single-packet",
    "small",
    "stationary",
    "statistics",
    "stop-change-of-serve-cell",
    "subscription-information",
    "successful-handover",
    "successful-outcome",
    "supported",
    "synchronous",
    "tS1relocoverall-expiry",
    "tS1relocprep-expiry",
    "time-Synchronisation-Info",
    "time-critical-handover",
    "transfer-syntax-error",
    "transport-resource-unavailable",
    "true",
    "tx2relocoverall-expiry",
    "uE-not-in-PLMN-serving-area",
    "ue-not-available-for-ps-service",
    "ues-retained",
    "unavailable",
    "unknown-E-RAB-ID",
    "unknown-PLMN",
    "unknown-enb-ue-s1ap-id",
    "unknown-mme-ue-s1ap-id",
    "unknown-pair-ue-s1ap-id",
    "unknown-targetID",
    "unlicensed",
    "unlicensed-restricted",
    "unspecified",
    "unsuccessfull-outcome",
    "up-integrity-protection-not-possible",
    "uplink",
    "user-inactivity",
    "utran",
    "utrantolte",
    "v1024",
    "v10s",
    "v128",
    "v1s",
    "v20s",
    "v256",
    "v2s",
    "v32",
    "v512",
    "v5s",
    "v60s",
    "v64",
    "verysmall",
    "voice",
    "x2-handover-triggered",
    "x2TNL-Configuration-Info",
];
use crate::inspect::open_types;
open_types! { crate::s1ap::s1_ap_containers::ProtocolIEField { value } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolIEContainer { 0 } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolExtensionField { extension_value } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolExtensionContainer { 0 } }
open_types! { crate::s1ap::s1_ap_ies::AdditionalGUTI { g_ummei, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AdditionalCSFallbackIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::AdditionalRRMPriorityIndex {} }
open_types! { crate::s1ap::s1_ap_ies::AerialUEsubscriptionInformation {} }
open_types! { crate::s1ap::s1_ap_ies::AllocationAndRetentionPriority { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AreaScopeOfMDT { cellBased, tABased, tAIBased } else { pLMNWide } }
open_types! { crate::s1ap::s1_ap_ies::AreaScopeOfQMC { cellBased, tABased, tAIBased, pLMNAreaBased } else {} }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForCECapableUEs { cell_identifier_and_celevel_for_cecapable_ues, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForPaging { assistance_data_for_recommended_cells, assistance_data_for_cecapable_ues, paging_attempt_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForRecommendedCells { recommended_cells_for_paging, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearerType {} }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToDLDiscardingItem { d_l_discarding, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToDLDiscardingList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToEarlyStatusTransferItem { d_lcount_pdcp_snlength, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToEarlyStatusTransferList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToStatusTransferItem { u_l_countvalue, d_l_countvalue, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToStatusTransferList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BluetoothMeasurementConfiguration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BroadcastCancelledAreaList { cellID_Cancelled, tAI_Cancelled, emergencyAreaID_Cancelled } else {} }
open_types! { crate::s1ap::s1_ap_ies::BroadcastCompletedAreaList { cellID_Broadcast, tAI_Broadcast, emergencyAreaID_Broadcast } else {} }
open_types! { crate::s1ap::s1_ap_ies::CEModeBRestricted {} }
open_types! { crate::s1ap::s1_ap_ies::CEModeBSupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::CGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CNDomain {} }
open_types! { crate::s1ap::s1_ap_ies::CNTypeRestrictions { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CNTypeRestrictionsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTValueExtended { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTvalue { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTvaluePDCPSNlength18 { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CSFallbackIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::CSGId {} }
open_types! { crate::s1ap::s1_ap_ies::CSGIdList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CSGIdListItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CSGMembershipStatus {} }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinEAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinEAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinTAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinTAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::Cause {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000HORequiredIndication {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000HOStatus {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000OneXRAND {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000OneXSRVCCInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000PDU {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000RATType {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000SectorID {} }
open_types! { crate::s1ap::s1_ap_ies::CellAccessMode {} }
open_types! { crate::s1ap::s1_ap_ies::CellBasedMDT { cell_id_listfor_mdt, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellBasedQMC { cell_id_listfor_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIDBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIDBroadcastItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIDCancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIDCancelledItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIdListforMDT { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIdListforQMC { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIdentifierAndCELevelForCECapableUEs { global_cell_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellType { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CoarseUELocation {} }
open_types! { crate::s1ap::s1_ap_ies::CoarseUELocationRequested {} }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinEAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinEAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinTAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinTAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ConcurrentWarningMessageIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ConnectedengNBItem { supported_tas, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ConnectedengNBList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ContextatSource { source_ng_ran_node_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CorrelationID {} }
open_types! { crate::s1ap::s1_ap_ies::CoverageLevel {} }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnostics { i_es_criticality_diagnostics, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnosticsIEItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnosticsIEList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::DAPSRequestInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfoItem { d_apsresponse_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfoList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::DCNID {} }
open_types! { crate::s1ap::s1_ap_ies::DLCPSecurityInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DLCOUNTPDCPSNlength { dLCOUNTValuePDCP_SNlength12, dLCOUNTValuePDCP_SNlength15, dLCOUNTValuePDCP_SNlength18 } else {} }
open_types! { crate::s1ap::s1_ap_ies::DLDiscarding { discardDLCOUNTValuePDCP_SNlength12, discardDLCOUNTValuePDCP_SNlength15, discardDLCOUNTValuePDCP_SNlength18 } else {} }
open_types! { crate::s1ap::s1_ap_ies::DLNASPDUDeliveryAckRequest {} }
open_types! { crate::s1ap::s1_ap_ies::DataForwardingNotPossible {} }
open_types! { crate::s1ap::s1_ap_ies::DataCodingScheme {} }
open_types! { crate::s1ap::s1_ap_ies::DataSize {} }
open_types! { crate::s1ap::s1_ap_ies::DirectForwardingPathAvailability {} }
open_types! { crate::s1ap::s1_ap_ies::ERABInformationList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABInformationListItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABLevelQoSParameters { allocation_retention_priority, gbr_qos_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABSecurityResultItem { security_result, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABSecurityResultList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABUsageReportItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABUsageReportList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EUTRANTraceID {} }
open_types! { crate::s1ap::s1_ap_ies::ECGI_List { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ECGIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ECGIListForRestart { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EDTSession {} }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONConfigurationTransfer { transfertype, s_oninformation, x2_tnlconfig_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONTransferType { request, reply } else {} }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONeNBIdentification { globale_nbid, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONengNBIdentification { globaleng_nbid, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCTransferTypeReply { sourceeng_nb, targete_nb, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCTransferTypeRequest { sourcee_nb, targeteng_nb, targete_nb, associated_tai, broadcast5_gstai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBEarlyStatusTransferTransparentContainer { bearers_subject_to_early_status_transfer_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBStatusTransferTransparentContainer { bearers_subject_to_status_transfer_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBUES1APID {} }
open_types! { crate::s1ap::s1_ap_ies::ENBIndirectX2TransportLayerAddresses {} }
open_types! { crate::s1ap::s1_ap_ies::ENBX2ExtTLA { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBX2ExtTLAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ENBname {} }
open_types! { crate::s1ap::s1_ap_ies::EUTRANCGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EUTRANRoundTripDelayEstimationInfo {} }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDBroadcastItem { completed_cellin_eai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDCancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDCancelledItem { cancelled_cellin_eai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDListForRestart {} }
open_types! { crate::s1ap::s1_ap_ies::EmergencyIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::EndIndication {} }
open_types! { crate::s1ap::s1_ap_ies::EnhancedCoverageRestricted {} }
open_types! { crate::s1ap::s1_ap_ies::EthernetType {} }
open_types! { crate::s1ap::s1_ap_ies::EventL1LoggedMDTConfig { l1_threshold, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EventTrigger { eventL1LoggedMDTConfig, choice_Extensions } else { outOfCoverage } }
open_types! { crate::s1ap::s1_ap_ies::ExpectedUEActivityBehaviour { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ExpectedUEBehaviour { expected_activity, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ExtendedUEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::ExtendedBitRate {} }
open_types! { crate::s1ap::s1_ap_ies::ExtendedRepetitionPeriod {} }
open_types! { crate::s1ap::s1_ap_ies::FiveGSTAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenLAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenLAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenTAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenTAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GBRQosInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GERANCellID { l_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GNB { global_g_nb_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEIType {} }
open_types! { crate::s1ap::s1_ap_ies::GWContextReleaseIndication {} }
open_types! { crate::s1ap::s1_ap_ies::GlobalENBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GlobalGNBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GlobalRANNODEID { gNB, ng_eNB } else {} }
open_types! { crate::s1ap::s1_ap_ies::GlobalEnGNBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::HandoverFlag {} }
open_types! { crate::s1ap::s1_ap_ies::HandoverRestrictionList { forbidden_tas, forbidden_las, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::HandoverType {} }
open_types! { crate::s1ap::s1_ap_ies::IABAuthorized {} }
open_types! { crate::s1ap::s1_ap_ies::IABNodeIndication {} }
open_types! { crate::s1ap::s1_ap_ies::IABSupported {} }
open_types! { crate::s1ap::s1_ap_ies::IMSvoiceEPSfallbackfrom5G {} }
open_types! { crate::s1ap::s1_ap_ies::ImmediateMDT { m1thresholdevent_a2, m1periodic_reporting, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InformationOnRecommendedCellsAndENBsForPaging { recommended_cells_for_paging, recommend_enbs_for_paging, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementParameters { inter_system_measurement_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::IntersystemMeasurementConfiguration { inter_system_measurement_parameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::IntersystemSONConfigurationTransfer {} }
open_types! { crate::s1ap::s1_ap_ies::KillAllWarningMessages {} }
open_types! { crate::s1ap::s1_ap_ies::LAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LHNID {} }
open_types! { crate::s1ap::s1_ap_ies::LPPaPDU {} }
open_types! { crate::s1ap::s1_ap_ies::LTEMIndication {} }
open_types! { crate::s1ap::s1_ap_ies::LTENTNTAIInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedCellItem { e_UTRAN_Cell } else { uTRAN_Cell, gERAN_Cell, nG_RAN_Cell } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedEUTRANCellInformation { global_cell_id, cell_type, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedPSCellInformation { p_scell_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedPSCellList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ListeningSubframePattern { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMBSFNMDT { m_bsfn_result_to_log, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMDT { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMDTTrigger { eventTrigger } else { periodical } }
open_types! { crate::s1ap::s1_ap_ies::M1PeriodicReporting { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M1ThresholdEventA2 { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M3Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M4Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M4ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M5Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M5ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M6Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M6ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M7Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M7ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::MBSFNResultToLog { 0 } }
open_types! { crate::s1ap::s1_ap_ies::MBSFNResultToLogInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::MDTConfiguration { area_scope_of_mdt, m_dtmode, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::MDTConfigurationNR {} }
open_types! { crate::s1ap::s1_ap_ies::MDTLocationInfo {} }
open_types! { crate::s1ap::s1_ap_ies::MDTMode { immediateMDT, loggedMDT, mDTMode_Extension } else {} }
open_types! { crate::s1ap::s1_ap_ies::MDTPLMNList {} }
open_types! { crate::s1ap::s1_ap_ies::MMEGroupID {} }
open_types! { crate::s1ap::s1_ap_ies::MMEUES1APID {} }
open_types! { crate::s1ap::s1_ap_ies::MMEPagingTarget { global_ENB_ID, tAI } else {} }
open_types! { crate::s1ap::s1_ap_ies::MMERelaySupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::MMEname {} }
open_types! { crate::s1ap::s1_ap_ies::MSClassmark2 {} }
open_types! { crate::s1ap::s1_ap_ies::MSClassmark3 {} }
open_types! { crate::s1ap::s1_ap_ies::ManagementBasedMDTAllowed {} }
open_types! { crate::s1ap::s1_ap_ies::MaskedIMEISV {} }
open_types! { crate::s1ap::s1_ap_ies::MeasurementThresholdL1LoggedMDT { choice_Extensions } else { threshold_RSRP, threshold_RSRQ } }
open_types! { crate::s1ap::s1_ap_ies::MessageIdentifier {} }
open_types! { crate::s1ap::s1_ap_ies::MobilityInformation {} }
open_types! { crate::s1ap::s1_ap_ies::MutingAvailabilityIndication {} }
open_types! { crate::s1ap::s1_ap_ies::MutingPatternInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NASPDU {} }
open_types! { crate::s1ap::s1_ap_ies::NASSecurityParametersfromEUTRAN {} }
open_types! { crate::s1ap::s1_ap_ies::NASSecurityParameterstoEUTRAN {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTDefaultPagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTPagingEDRXInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NBIoTPagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTRLFReportContainer {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTUEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::NGENB { global_ng_e_nb_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRCGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRUESecurityCapabilities { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRUESidelinkAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRV2XServicesAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRrestrictionin5GS {} }
open_types! { crate::s1ap::s1_ap_ies::NRrestrictioninEPSasSecondaryRAT {} }
open_types! { crate::s1ap::s1_ap_ies::NotifySourceeNB {} }
open_types! { crate::s1ap::s1_ap_ies::NumberofBroadcastRequest {} }
open_types! { crate::s1ap::s1_ap_ies::OverloadResponse {} }
open_types! { crate::s1ap::s1_ap_ies::PC5FlowBitRates { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSFlowItem { pc5_flow_bit_rates, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSFlowList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSParameters { pc5_qo_sflow_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PLMNAreaBasedQMC { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PLMNidentity {} }
open_types! { crate::s1ap::s1_ap_ies::PSServiceNotAvailable {} }
open_types! { crate::s1ap::s1_ap_ies::PSCellInformation { n_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PWSfailedECGIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::PacketLossRate {} }
open_types! { crate::s1ap::s1_ap_ies::PagingEDRXInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PagingAttemptInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PagingCause {} }
open_types! { crate::s1ap::s1_ap_ies::PagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::PagingPriority {} }
open_types! { crate::s1ap::s1_ap_ies::PendingDataIndication {} }
open_types! { crate::s1ap::s1_ap_ies::PrivacyIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ProSeAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ProSeUEtoNetworkRelaying {} }
open_types! { crate::s1ap::s1_ap_ies::RACSIndication {} }
open_types! { crate::s1ap::s1_ap_ies::RATRestrictions { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RATRestrictionsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RATType {} }
open_types! { crate::s1ap::s1_ap_ies::RIMRoutingAddress { gERAN_Cell_ID, targetRNC_ID } else { eHRPD_Sector_ID } }
open_types! { crate::s1ap::s1_ap_ies::RIMTransfer { r_imrouting_address, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RLFReportInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RRCEstablishmentCause {} }
open_types! { crate::s1ap::s1_ap_ies::ReceiveStatusOfULPDCPSDUsExtended {} }
open_types! { crate::s1ap::s1_ap_ies::ReceiveStatusOfULPDCPSDUsPDCPSNlength18 {} }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellItem { e_utran_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellsForPaging { recommended_cell_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBItem { m_mepaging_target, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBsForPaging { recommended_enblist, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RelativeMMECapacity {} }
open_types! { crate::s1ap::s1_ap_ies::RelayNodeIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::RepetitionPeriod {} }
open_types! { crate::s1ap::s1_ap_ies::RequestType { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RequestTypeAdditionalInfo {} }
open_types! { crate::s1ap::s1_ap_ies::RequestedTNLInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RoutingID {} }
open_types! { crate::s1ap::s1_ap_ies::STMSI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONConfigurationTransfer { targete_nb_id, sourcee_nb_id, s_oninformation, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONInformation { sONInformationReply, sONInformation_Extension } else { sONInformationRequest } }
open_types! { crate::s1ap::s1_ap_ies::SONInformationReply { x2_tnlconfiguration_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONInformationReport { rLFReportInformation } else {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCHOIndication {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCOperationNotPossible {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCOperationPossible {} }
open_types! { crate::s1ap::s1_ap_ies::ScheduledCommunicationTime { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageReportItem { e_rabusage_report_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageReportList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageRequest {} }
open_types! { crate::s1ap::s1_ap_ies::SecurityContext { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecurityIndication { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecurityKey {} }
open_types! { crate::s1ap::s1_ap_ies::SecurityResult { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasConfigNameItem { sensor_name_config, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasConfigNameList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasurementConfiguration { sensor_meas_config_name_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorNameConfig { choice_Extensions } else { uncompensatedBarometricConfig } }
open_types! { crate::s1ap::s1_ap_ies::SerialNumber {} }
open_types! { crate::s1ap::s1_ap_ies::ServedDCNs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ServedDCNsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ServedGUMMEIs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ServedGUMMEIsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ServiceType {} }
open_types! { crate::s1ap::s1_ap_ies::SourceToTargetTransparentContainer {} }
open_types! { crate::s1ap::s1_ap_ies::SourceNgRanNodeID { global_ran_node_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SourceNodeID { sourceNgRanNode_ID, sourceNodeID_Extension } else {} }
open_types! { crate::s1ap::s1_ap_ies::SourceeNBID { global_enb_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SourceeNBToTargeteNBTransparentContainer { e_rabinformation_list, target_cell_id, u_e_history_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SubscriberProfileIDforRFP {} }
open_types! { crate::s1ap::s1_ap_ies::SubscriptionBasedUEDifferentiationInfo { scheduled_communication_time, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SupportedTAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SupportedTAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SynchronisationInformation { listening_subframe_pattern, aggressore_cgi_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TABasedMDT { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TABasedQMC { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIBroadcastItem { t_ai, completed_cellin_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAICancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAICancelledItem { t_ai, cancelled_cellin_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBasedMDT { t_ailistfor_mdt, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBasedQMC { t_ailistfor_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIListForRestart { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforMDT { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforQMC { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforWarning { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TargetToSourceTransparentContainer {} }
open_types! { crate::s1ap::s1_ap_ies::TargetID { targeteNB_ID, targetRNC_ID, cGI, targetgNgRanNode_ID } else {} }
open_types! { crate::s1ap::s1_ap_ies::TargetNgRanNodeID { global_ran_node_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargetRNCID { l_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargeteNBID { global_enb_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargeteNBToSourceeNBTransparentContainer { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeUEStayedInCellEnhancedGranularity {} }
open_types! { crate::s1ap::s1_ap_ies::TimeBasedHandoverInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeRefDistribution {} }
open_types! { crate::s1ap::s1_ap_ies::TimeSinceSecondaryNodeRelease {} }
open_types! { crate::s1ap::s1_ap_ies::TimeSynchronisationInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeToWait {} }
open_types! { crate::s1ap::s1_ap_ies::TraceActivation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TrafficLoadReductionIndication {} }
open_types! { crate::s1ap::s1_ap_ies::TransportInformation {} }
open_types! { crate::s1ap::s1_ap_ies::TransportLayerAddress {} }
open_types! { crate::s1ap::s1_ap_ies::TunnelInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEApplicationLayerMeasurementCapability {} }
open_types! { crate::s1ap::s1_ap_ies::UEHistoryInformation { 0 } }
open_types! { crate::s1ap::s1_ap_ies::UEHistoryInformationFromTheUE {} }
open_types! { crate::s1ap::s1_ap_ies::UERetentionInformation {} }
open_types! { crate::s1ap::s1_ap_ies::UES1APIDPair { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UES1APIDs { uE_S1AP_ID_pair } else { mME_UE_S1AP_ID } }
open_types! { crate::s1ap::s1_ap_ies::UEUsageType {} }
open_types! { crate::s1ap::s1_ap_ies::UEAssociatedLogicalS1ConnectionItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEAppLayerMeasConfig { area_scope_of_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UECapabilityInfoRequest {} }
open_types! { crate::s1ap::s1_ap_ies::UEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::UEPagingID { s_TMSI } else { iMSI } }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapability {} }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapabilityForPaging {} }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapabilityID {} }
open_types! { crate::s1ap::s1_ap_ies::UESecurityCapabilities { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UESidelinkAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEUserPlaneCIoTSupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ULCPSecurityInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::URIAddress {} }
open_types! { crate::s1ap::s1_ap_ies::UnlicensedSpectrumRestriction {} }
open_types! { crate::s1ap::s1_ap_ies::UserLocationInformation { eutran_cgi, tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::V2XServicesAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::VoiceSupportMatchIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::WLANMeasurementConfiguration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::WUSAssistanceInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::WarningAreaCoordinates {} }
open_types! { crate::s1ap::s1_ap_ies::WarningAreaList { cellIDList, trackingAreaListforWarning } else { emergencyAreaIDList } }
open_types! { crate::s1ap::s1_ap_ies::WarningMessageContents {} }
open_types! { crate::s1ap::s1_ap_ies::WarningSecurityInfo {} }
open_types! { crate::s1ap::s1_ap_ies::WarningType {} }
open_types! { crate::s1ap::s1_ap_ies::X2TNLConfigurationInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::CSGMembershipInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::CellTrafficTrace { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ConnectionEstablishmentIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DeactivateTrace { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkNASTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkNonUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkS1cdma2000tunnelling { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABAdmittedItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABAdmittedList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABDataForwardingItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeItemResumeReq { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeItemResumeRes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeListResumeReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeListResumeRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToSetupItemHOReqAck { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedtoSetupListHOReqAck { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModificationConfirm { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModificationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyItemBearerModConf { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyItemBearerModRes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyListBearerModConf { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyListBearerModRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABNotToBeModifiedItemBearerModInd { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABNotToBeModifiedListBearerModInd { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseItemBearerRelComp { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseListBearerRelComp { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupItemBearerSURes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupItemCtxtSURes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupListBearerSURes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupListCtxtSURes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSubjecttoDataForwardingList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedItemBearerModInd { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedItemBearerModReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedListBearerModInd { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedListBearerModReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemBearerSUReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemCtxtSUReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemHOReq { e_rablevel_qos_parameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListBearerSUReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListCtxtSUReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListHOReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedDLItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedDLList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedULItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedULList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeUpdatedItem { security_indication, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeUpdatedList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBCPRelocationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdate { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdateAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdateFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBDirectInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBEarlyStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ErrorIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCancel { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCancelAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverNotify { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverPreparationFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequestAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequired { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverSuccess { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialUEMessage { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InterSystemInformationTransferType { rIMTransfer } else {} }
open_types! { crate::s1ap::s1_ap_pdu_contents::KillRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::KillResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReportingControl { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReportingFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMECPRelocationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdate { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdateAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdateFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEDirectInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEEarlyStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::NASDeliveryIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::NASNonDeliveryIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::OverloadStart { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::OverloadStop { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PWSFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PWSRestartIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::Paging { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequestAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequestFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::AnonymousPrivateMessagePrivateIEs { value } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PrivateMessagePrivateIEs { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PrivateMessage { private_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::RerouteNASRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::Reset { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ResetAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ResetType { partOfS1_Interface } else { s1_Interface } }
open_types! { crate::s1ap::s1_ap_pdu_contents::RetrieveUEInformation { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::SecondaryRATDataUsageReport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TAIItem { t_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TAIList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TraceFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TraceStart { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEAssociatedLogicalS1ConnectionListRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEAssociatedLogicalS1ConnectionListResAck { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UECapabilityInfoIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationConfirm { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseComplete { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextSuspendRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextSuspendResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityIDMappingRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityIDMappingResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityMatchRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityMatchResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkNASTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkNonUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkS1cdma2000tunnelling { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::WriteReplaceWarningRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::WriteReplaceWarningResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::InitiatingMessage { value } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::S1APPDU { initiatingMessage, successfulOutcome, unsuccessfulOutcome } else {} }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::SuccessfulOutcome { value } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::UnsuccessfulOutcome { value } }
