// Auto-generated by build/inspection.rs from ASN.1; do not edit.
use crate::inspect::{Form, Typed, transfers};
use crate::inspect_paths::types;
pub(crate) use crate::registry::{
    IE_NAMES, IE_TYPES, ITEM_CRITICALITIES, MESSAGE_IE_CRITICALITIES, MESSAGES,
    PROCEDURE_CRITICALITIES, ie, ie_contents,
};
pub(crate) const PROTOCOL: &str = "S1AP";
pub(crate) const ROOT: &str = "s1ap";
transfers! {}
pub(crate) fn member_form(name: &str) -> Option<Form> {
    Some(match name {
        // CI
        "cI" => Form::Number(16),
        // CellIdentity
        "cell-ID" => Form::Number(28),
        // FiveGSTAC
        "fiveGSTAC" => Form::Number(24),
        // GTP-TEID
        "dL-GTP-TEID" | "dL-gTP-TEID" | "gTP-TEID" | "uL-GTP-TEID" => Form::Number(32),
        // IMSI
        "iMSI" => Form::Digits,
        // LAC
        "forbiddenLACs" | "lAC" => Form::Number(16),
        // M-TMSI
        "m-TMSI" => Form::Number(32),
        // MME-Code
        "mME-Code" | "mMEC" | "servedMMECs" => Form::Number(8),
        // MME-Group-ID
        "mME-Group-ID" | "servedGroupIDs" => Form::Number(16),
        // NRCellIdentity
        "nRCellIdentity" => Form::Number(36),
        // PLMNidentity
        "broadcastPLMNs" | "equivalentPLMNs" | "pLMN-Identity" | "pLMNIdentity"
        | "pLMNidentity" | "plmnListforQMC" | "servedPLMNs" | "servingPLMN" => Form::Plmn,
        // Port-Number
        "uDP-Port-Number" => Form::Number(16),
        // RAC
        "rAC" => Form::Number(8),
        // TAC
        "forbiddenTACs"
        | "tAC"
        | "tACList-In-LTE-NTN"
        | "tAListforMDT"
        | "tAListforQMC"
        | "uE-Location-Derived-TAC" => Form::Number(16),
        // TransportLayerAddress
        "dL-transportLayerAddress"
        | "eNBX2TransportLayerAddresses"
        | "gTPTLAa"
        | "iPsecTLA"
        | "traceCollectionEntityIPAddress"
        | "transportLayerAddress"
        | "uL-TransportLayerAddress" => Form::Address,
        // UL-NAS-Count
        "ul-NAS-Count" => Form::Number(5),
        _ => return None,
    })
}
pub(crate) fn ie_form(id: u16) -> Option<Form> {
    Some(match id {
        // MME-Group-ID
        223 => Form::Number(16),
        // PLMNidentity
        177 | 178 | 290 => Form::Plmn,
        // TransportLayerAddress
        131 | 155 | 184 | 193 | 328 | 340 => Form::Address,
        _ => return None,
    })
}
pub(crate) const ENUMERATED: &[&str] = &[
    "a2eventtriggered",
    "a2eventtriggered-periodic",
    "abstract-syntax-error-falsely-constructed-message",
    "abstract-syntax-error-ignore-and-notify",
    "abstract-syntax-error-reject",
    "activate-Muting",
    "all",
    "allowed",
    "asynchronous",
    "authentication-failure",
    "authorized",
    "available",
    "battery-powered",
    "battery-powered-not-rechargeable-or-replaceable",
    "both-uplink-and-downlink",
    "cSonly",
    "cdma2000",
    "cdma2000andutran",
    "cell-not-available",
    "change-of-serve-cell",
    "changed",
    "conditional",
    "control-processing-overload",
    "cs",
    "cs-fallback-high-priority",
    "cs-fallback-required",
    "cs-fallback-triggered",
    "csg-subscription-expiry",
    "dAPS-HO-accepted",
    "dAPS-HO-not-accepted",
    "dAPS-HO-required",
    "dL-Forwarding-proposed",
    "data-Forwarding-not-Possible",
    "deactivate-Muting",
    "delay-TolerantAccess",
    "detach",
    "direct",
    "directPathAvailable",
    "downlink",
    "dual-packets",
    "ecgi",
    "emergency",
    "encryption-and-or-integrity-protection-algorithms-not-supported",
    "epc-Forbiddden",
    "eps-to-5gs",
    "eutran-geo",
    "eutran-leo",
    "eutran-meo",
    "eutran-othersat",
    "extendedcoverage",
    "failure-in-radio-interface-procedure",
    "fiveGCForbidden",
    "fivegs-to-eps",
    "further-data-exists",
    "geran",
    "geranandutran",
    "gerantolte",
    "hOFailure",
    "hOSuccess",
    "hRPD",
    "handover-cancelled",
    "handover-desirable-for-radio-reason",
    "handoverPreparation",
    "hardware-failure",
    "hf1",
    "hf10",
    "hf1024",
    "hf12",
    "hf128",
    "hf14",
    "hf16",
    "hf2",
    "hf256",
    "hf32",
    "hf4",
    "hf512",
    "hf6",
    "hf64",
    "hf8",
    "hfhalf",
    "highPriorityAccess",
    "ho-failure-in-target-EPC-eNB-or-target-system",
    "ho-target-not-allowed",
    "hybrid",
    "iab-not-authorized",
    "ignore",
    "immediate-MDT",
    "immediate-MDT-and-Trace",
    "immediate-MDT-only",
    "includePSCell",
    "infinity",
    "initiating-message",
    "insufficient-ue-capabilities",
    "interaction-with-other-procedure",
    "interrat-redirection",
    "intralte",
    "invalid-CSG-Id",
    "invalid-qos-combination",
    "kHz120",
    "kHz15",
    "kHz240",
    "kHz30",
    "kHz480",
    "kHz60",
    "kHz960",
    "large",
    "load-balancing-tau-required",
    "logged-MBSFN-MDT",
    "logged-MDT",
    "logged-MDT-only",
    "long-time",
    "lte-m",
    "ltetogeran",
    "ltetoutran",
    "m10",
    "m1000",
    "m120",
    "m180",
    "m20",
    "m200",
    "m350",
    "m40",
    "m400",
    "m50",
    "m500",
    "m60",
    "m700",
    "m80",
    "m90",
    "mandatory",
    "mapped",
    "mappedFrom5G",
    "maximum",
    "maximum-bearer-pre-emption-rate-exceeded",
    "maximumWithoutVendorSpecificExtension",
    "may-trigger-pre-emption",
    "medium",
    "mediumWithoutVendorSpecificExtension",
    "member",
    "message-not-compatible-with-receiver-state",
    "min1",
    "min12",
    "min30",
    "min6",
    "min60",
    "minimum",
    "minimumWithoutVendorSpecificExtension",
    "missing",
    "mo-Data",
    "mo-ExceptionData",
    "mo-Signalling",
    "mo-VoiceCall",
    "mobile",
    "ms0",
    "ms100",
    "ms1000",
    "ms10000",
    "ms1024",
    "ms10240",
    "ms120",
    "ms128",
    "ms1280",
    "ms150",
    "ms160",
    "ms2048",
    "ms20480",
    "ms240",
    "ms256",
    "ms2560",
    "ms30",
    "ms300",
    "ms30720",
    "ms320",
    "ms40",
    "ms40960",
    "ms480",
    "ms50",
    "ms500",
    "ms512",
    "ms5120",
    "ms60",
    "ms61440",
    "ms64",
    "ms640",
    "ms70",
    "ms750",
    "ms80",
    "ms90",
    "mt-Access",
    "multiple-E-RAB-ID-instances",
    "multiple-packets",
    "n26-interface-not-available",
    "nR",
    "nRrestrictedin5GS",
    "nRrestrictedinEPSasSecondaryRAT",
    "native",
    "nbiot",
    "nbiot-geo",
    "nbiot-leo",
    "nbiot-meo",
    "nbiot-othersat",
    "no-further-data",
    "no-radio-resources-available-in-target-cell",
    "no-restriction",
    "non-IP",
    "normal-release",
    "not-accept-mo-data-or-delay-tolerant-access-from-CP-CIoT",
    "not-allowed",
    "not-authorized",
    "not-battery-powered",
    "not-enough-user-plane-processing-resources",
    "not-member",
    "not-needed",
    "not-performed",
    "not-pre-emptable",
    "not-restricted",
    "not-supported",
    "not-supported-QCI-value",
    "not-understood",
    "notPossible",
    "notify",
    "notifySource",
    "om-intervention",
    "ondemand",
    "onexRTT",
    "optional",
    "p00",
    "p05",
    "p10",
    "p100",
    "p15",
    "p20",
    "p25",
    "p30",
    "p35",
    "p40",
    "p45",
    "p50",
    "p55",
    "p60",
    "p65",
    "p70",
    "p75",
    "p80",
    "p85",
    "p90",
    "p95",
    "pSandCS",
    "partial-handover",
    "performed",
    "periodic",
    "periodically",
    "permit-emergency-sessions-and-mobile-terminated-services-only",
    "permit-high-priority-sessions-and-exception-reporting-and-mobile-terminated-services-only",
    "permit-high-priority-sessions-and-mobile-terminated-services-only",
    "possible",
    "pre-emptable",
    "preferred",
    "priolevel1",
    "priolevel2",
    "priolevel3",
    "priolevel4",
    "priolevel5",
    "priolevel6",
    "priolevel7",
    "priolevel8",
    "ps",
    "ps-service-not-available",
    "qMC-for-MTSI-service",
    "qMC-for-streaming-service",
    "r1",
    "r16",
    "r2",
    "r32",
    "r4",
    "r64",
    "r8",
    "radio-connection-with-ue-lost",
    "radio-resources-not-available",
    "redirection-towards-1xRTT",
    "reduce-load-in-serving-cell",
    "reject",
    "reject-delay-tolerant-access",
    "reject-non-emergency-mo-dt",
    "reject-rrc-cr-signalling",
    "release-due-to-discontinuous-coverage",
    "release-due-to-eutran-generated-reason",
    "release-due-to-pre-emption",
    "requested",
    "required",
    "reset-all",
    "resource-optimisation-handover",
    "restricted",
    "restriction",
    "rinfinity",
    "s1",
    "s1-inter-system-handover-triggered",
    "s1-intra-system-handover-triggered",
    "s10",
    "s11",
    "s12",
    "s13",
    "s14",
    "s15",
    "s16",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "same",
    "sec120",
    "sec15",
    "sec180",
    "sec30",
    "sec60",
    "sec90",
    "semantic-error",
    "setup",
    "shall-not-trigger-pre-emption",
    "single-packet",
    "small",
    "stationary",
    "statistics",
    "stop-change-of-serve-cell",
    "subscription-information",
    "successful-handover",
    "successful-outcome",
    "supported",
    "synchronous",
    "tS1relocoverall-expiry",
    "tS1relocprep-expiry",
    "time-Synchronisation-Info",
    "time-critical-handover",
    "transfer-syntax-error",
    "transport-resource-unavailable",
    "true",
    "tx2relocoverall-expiry",
    "uE-not-in-PLMN-serving-area",
    "ue-not-available-for-ps-service",
    "ues-retained",
    "unavailable",
    "unknown-E-RAB-ID",
    "unknown-PLMN",
    "unknown-enb-ue-s1ap-id",
    "unknown-mme-ue-s1ap-id",
    "unknown-pair-ue-s1ap-id",
    "unknown-targetID",
    "unlicensed",
    "unlicensed-restricted",
    "unspecified",
    "unsuccessfull-outcome",
    "up-integrity-protection-not-possible",
    "uplink",
    "user-inactivity",
    "utran",
    "utrantolte",
    "v1024",
    "v10s",
    "v128",
    "v1s",
    "v20s",
    "v256",
    "v2s",
    "v32",
    "v512",
    "v5s",
    "v60s",
    "v64",
    "verysmall",
    "voice",
    "x2-handover-triggered",
    "x2TNL-Configuration-Info",
];
types! {
    AdditionalGUTI sequence { "gUMMEI": GUMMEI, "m-TMSI": _, "iE-Extensions"? extensions };
    AllocationAndRetentionPriority sequence { "priorityLevel": _, "pre-emptionCapability": _, "pre-emptionVulnerability": _, "iE-Extensions"? extensions };
    AnonymousPrivateMessagePrivateIEs sequence { "id": PrivateIEID, "criticality": _, "value": _ };
    AreaScopeOfMDT choice { "cellBased": CellBasedMDT, "tABased": TABasedMDT, "pLMNWide": _, "tAIBased": TAIBasedMDT };
    AreaScopeOfQMC choice { "cellBased": CellBasedQMC, "tABased": TABasedQMC, "tAIBased": TAIBasedQMC, "pLMNAreaBased": PLMNAreaBasedQMC };
    AssistanceDataForCECapableUEs sequence { "cellIdentifierAndCELevelForCECapableUEs": CellIdentifierAndCELevelForCECapableUEs, "iE-Extensions"? extensions };
    AssistanceDataForPaging sequence { "assistanceDataForRecommendedCells"? AssistanceDataForRecommendedCells, "assistanceDataForCECapableUEs"? AssistanceDataForCECapableUEs, "pagingAttemptInformation"? PagingAttemptInformation, "iE-Extensions"? extensions };
    AssistanceDataForRecommendedCells sequence { "recommendedCellsForPaging": RecommendedCellsForPaging, "iE-Extensions"? extensions };
    BPLMNs = [_];
    BearersSubjectToDLDiscardingItem sequence { "e-RAB-ID": _, "dL-Discarding": DLDiscarding, "iE-Extensions"? extensions };
    BearersSubjectToDLDiscardingList = [ie];
    BearersSubjectToEarlyStatusTransferItem sequence { "e-RAB-ID": _, "dLCOUNT-PDCP-SNlength": DLCOUNTPDCPSNlength, "iE-Extensions"? extensions };
    BearersSubjectToEarlyStatusTransferList = [ie];
    BearersSubjectToStatusTransferItem sequence { "e-RAB-ID": _, "uL-COUNTvalue": COUNTvalue, "dL-COUNTvalue": COUNTvalue, "receiveStatusofULPDCPSDUs"? _, "iE-Extensions"? extensions };
    BearersSubjectToStatusTransferList = [ie];
    BluetoothMeasConfigNameList = [_];
    BluetoothMeasurementConfiguration sequence { "bluetoothMeasConfig": _, "bluetoothMeasConfigNameList"? BluetoothMeasConfigNameList, "bt-rssi"? _, "iE-Extensions"? extensions };
    BroadcastCancelledAreaList choice { "cellID-Cancelled": CellIDCancelled, "tAI-Cancelled": TAICancelled, "emergencyAreaID-Cancelled": EmergencyAreaIDCancelled };
    BroadcastCompletedAreaList choice { "cellID-Broadcast": CellIDBroadcast, "tAI-Broadcast": TAIBroadcast, "emergencyAreaID-Broadcast": EmergencyAreaIDBroadcast };
    CGI sequence { "pLMNidentity": _, "lAC": _, "cI": _, "rAC"? _, "iE-Extensions"? extensions };
    CNTypeRestrictions = [CNTypeRestrictionsItem];
    CNTypeRestrictionsItem sequence { "pLMN-Identity": _, "cNType": _, "iE-Extensions"? extensions };
    COUNTValueExtended sequence { "pDCP-SNExtended": _, "hFNModified": _, "iE-Extensions"? extensions };
    COUNTvalue sequence { "pDCP-SN": _, "hFN": _, "iE-Extensions"? extensions };
    COUNTvaluePDCPSNlength18 sequence { "pDCP-SNlength18": _, "hFNforPDCP-SNlength18": _, "iE-Extensions"? extensions };
    CSGIdList = [CSGIdListItem];
    CSGIdListItem sequence { "cSG-Id": _, "iE-Extensions"? extensions };
    CSGMembershipInfo sequence { "cSGMembershipStatus": _, "cSG-Id": _, "cellAccessMode"? _, "pLMNidentity"? _, "iE-Extensions"? extensions };
    CancelledCellinEAI = [CancelledCellinEAIItem];
    CancelledCellinEAIItem sequence { "eCGI": EUTRANCGI, "numberOfBroadcasts": _, "iE-Extensions"? extensions };
    CancelledCellinTAI = [CancelledCellinTAIItem];
    CancelledCellinTAIItem sequence { "eCGI": EUTRANCGI, "numberOfBroadcasts": _, "iE-Extensions"? extensions };
    Cause choice { "radioNetwork": _, "transport": _, "nas": _, "protocol": _, "misc": _ };
    Cdma2000OneXSRVCCInfo sequence { "cdma2000OneXMEID": _, "cdma2000OneXMSI": _, "cdma2000OneXPilot": _, "iE-Extensions"? extensions };
    CellBasedMDT sequence { "cellIdListforMDT": CellIdListforMDT, "iE-Extensions"? extensions };
    CellBasedQMC sequence { "cellIdListforQMC": CellIdListforQMC, "iE-Extensions"? extensions };
    CellIDBroadcast = [CellIDBroadcastItem];
    CellIDBroadcastItem sequence { "eCGI": EUTRANCGI, "iE-Extensions"? extensions };
    CellIDCancelled = [CellIDCancelledItem];
    CellIDCancelledItem sequence { "eCGI": EUTRANCGI, "numberOfBroadcasts": _, "iE-Extensions"? extensions };
    CellIdListforMDT = [EUTRANCGI];
    CellIdListforQMC = [EUTRANCGI];
    CellIdentifierAndCELevelForCECapableUEs sequence { "global-Cell-ID": EUTRANCGI, "cELevel": _, "iE-Extensions"? extensions };
    CellTrafficTrace sequence { "protocolIEs": ies };
    CellType sequence { "cell-Size": _, "iE-Extensions"? extensions };
    CompletedCellinEAI = [CompletedCellinEAIItem];
    CompletedCellinEAIItem sequence { "eCGI": EUTRANCGI, "iE-Extensions"? extensions };
    CompletedCellinTAI = [CompletedCellinTAIItem];
    CompletedCellinTAIItem sequence { "eCGI": EUTRANCGI, "iE-Extensions"? extensions };
    ConnectedengNBItem sequence { "en-gNB-ID": EnGNBID, "supportedTAs": SupportedTAs, "iE-Extensions"? extensions };
    ConnectedengNBList = [ConnectedengNBItem];
    ConnectionEstablishmentIndication sequence { "protocolIEs": ies };
    ContextatSource sequence { "sourceNG-RAN-node-ID": GlobalRANNODEID, "rAN-UE-NGAP-ID": _, "iE-Extensions"? extensions };
    CriticalityDiagnostics sequence { "procedureCode"? _, "triggeringMessage"? _, "procedureCriticality"? _, "iEsCriticalityDiagnostics"? CriticalityDiagnosticsIEList, "iE-Extensions"? extensions };
    CriticalityDiagnosticsIEItem sequence { "iECriticality": _, "iE-ID": _, "typeOfError": _, "iE-Extensions"? extensions };
    CriticalityDiagnosticsIEList = [CriticalityDiagnosticsIEItem];
    DAPSRequestInfo sequence { "dAPSIndicator": _, "iE-Extensions"? extensions };
    DAPSResponseInfo sequence { "dapsresponseindicator": _, "iE-Extensions"? extensions };
    DAPSResponseInfoItem sequence { "e-RAB-ID": _, "dAPSResponseInfo": DAPSResponseInfo, "iE-Extensions"? extensions };
    DAPSResponseInfoList = [ie];
    DLCOUNTPDCPSNlength choice { "dLCOUNTValuePDCP-SNlength12": COUNTvalue, "dLCOUNTValuePDCP-SNlength15": COUNTValueExtended, "dLCOUNTValuePDCP-SNlength18": COUNTvaluePDCPSNlength18 };
    DLCPSecurityInformation sequence { "dl-NAS-MAC": _, "iE-Extensions"? extensions };
    DLDiscarding choice { "discardDLCOUNTValuePDCP-SNlength12": COUNTvalue, "discardDLCOUNTValuePDCP-SNlength15": COUNTValueExtended, "discardDLCOUNTValuePDCP-SNlength18": COUNTvaluePDCPSNlength18 };
    DeactivateTrace sequence { "protocolIEs": ies };
    DownlinkNASTransport sequence { "protocolIEs": ies };
    DownlinkNonUEAssociatedLPPaTransport sequence { "protocolIEs": ies };
    DownlinkS1cdma2000tunnelling sequence { "protocolIEs": ies };
    DownlinkUEAssociatedLPPaTransport sequence { "protocolIEs": ies };
    ECGIList = [EUTRANCGI];
    ECGIListForRestart = [EUTRANCGI];
    ECGI_List = [EUTRANCGI];
    ENBCPRelocationIndication sequence { "protocolIEs": ies };
    ENBConfigurationTransfer sequence { "protocolIEs": ies };
    ENBConfigurationUpdate sequence { "protocolIEs": ies };
    ENBConfigurationUpdateAcknowledge sequence { "protocolIEs": ies };
    ENBConfigurationUpdateFailure sequence { "protocolIEs": ies };
    ENBDirectInformationTransfer sequence { "protocolIEs": ies };
    ENBEarlyStatusTransfer sequence { "protocolIEs": ies };
    ENBEarlyStatusTransferTransparentContainer sequence { "bearers-SubjectToEarlyStatusTransferList": BearersSubjectToEarlyStatusTransferList, "iE-Extensions"? extensions };
    ENBID choice { "macroENB-ID": _, "homeENB-ID": _, "short-macroENB-ID": _, "long-macroENB-ID": _ };
    ENBIndirectX2TransportLayerAddresses = [TransportLayerAddress];
    ENBStatusTransfer sequence { "protocolIEs": ies };
    ENBStatusTransferTransparentContainer sequence { "bearers-SubjectToStatusTransferList": BearersSubjectToStatusTransferList, "iE-Extensions"? extensions };
    ENBX2ExtTLA sequence { "iPsecTLA"? TransportLayerAddress, "gTPTLAa"? ENBX2GTPTLAs, "iE-Extensions"? extensions };
    ENBX2ExtTLAs = [ENBX2ExtTLA];
    ENBX2GTPTLAs = [TransportLayerAddress];
    ENBX2TLAs = [TransportLayerAddress];
    ENDCSONConfigurationTransfer sequence { "transfertype": ENDCSONTransferType, "sONInformation": SONInformation, "x2TNLConfigInfo"? X2TNLConfigurationInfo, "iE-Extensions"? extensions };
    ENDCSONTransferType choice { "request": ENDCTransferTypeRequest, "reply": ENDCTransferTypeReply };
    ENDCSONeNBIdentification sequence { "globaleNBID": GlobalENBID, "selectedTAI": TAI, "iE-Extensions"? extensions };
    ENDCSONengNBIdentification sequence { "globalengNBID": GlobalEnGNBID, "selectedTAI": TAI, "iE-Extensions"? extensions };
    ENDCTransferTypeReply sequence { "sourceengNB": ENDCSONengNBIdentification, "targeteNB": ENDCSONeNBIdentification, "iE-Extensions"? extensions };
    ENDCTransferTypeRequest sequence { "sourceeNB": ENDCSONeNBIdentification, "targetengNB": ENDCSONengNBIdentification, "targeteNB"? ENDCSONeNBIdentification, "associatedTAI"? TAI, "broadcast5GSTAI"? FiveGSTAI, "iE-Extensions"? extensions };
    EPLMNs = [_];
    ERABAdmittedItem sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "dL-transportLayerAddress"? TransportLayerAddress, "dL-gTP-TEID"? _, "uL-TransportLayerAddress"? TransportLayerAddress, "uL-GTP-TEID"? _, "iE-Extensions"? extensions };
    ERABAdmittedList = [ie];
    ERABDataForwardingItem sequence { "e-RAB-ID": _, "dL-transportLayerAddress"? TransportLayerAddress, "dL-gTP-TEID"? _, "uL-TransportLayerAddress"? TransportLayerAddress, "uL-GTP-TEID"? _, "iE-Extensions"? extensions };
    ERABFailedToResumeItemResumeReq sequence { "e-RAB-ID": _, "cause": Cause, "iE-Extensions"? extensions };
    ERABFailedToResumeItemResumeRes sequence { "e-RAB-ID": _, "cause": Cause, "iE-Extensions"? extensions };
    ERABFailedToResumeListResumeReq = [ie];
    ERABFailedToResumeListResumeRes = [ie];
    ERABFailedToSetupItemHOReqAck sequence { "e-RAB-ID": _, "cause": Cause, "iE-Extensions"? extensions };
    ERABFailedtoSetupListHOReqAck = [ie];
    ERABInformationList = [ie];
    ERABInformationListItem sequence { "e-RAB-ID": _, "dL-Forwarding"? _, "iE-Extensions"? extensions };
    ERABItem sequence { "e-RAB-ID": _, "cause": Cause, "iE-Extensions"? extensions };
    ERABLevelQoSParameters sequence { "qCI": _, "allocationRetentionPriority": AllocationAndRetentionPriority, "gbrQosInformation"? GBRQosInformation, "iE-Extensions"? extensions };
    ERABList = [ie];
    ERABModificationConfirm sequence { "protocolIEs": ies };
    ERABModificationIndication sequence { "protocolIEs": ies };
    ERABModifyItemBearerModConf sequence { "e-RAB-ID": _, "iE-Extensions"? extensions };
    ERABModifyItemBearerModRes sequence { "e-RAB-ID": _, "iE-Extensions"? extensions };
    ERABModifyListBearerModConf = [ie];
    ERABModifyListBearerModRes = [ie];
    ERABModifyRequest sequence { "protocolIEs": ies };
    ERABModifyResponse sequence { "protocolIEs": ies };
    ERABNotToBeModifiedItemBearerModInd sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "dL-GTP-TEID": _, "iE-Extensions"? extensions };
    ERABNotToBeModifiedListBearerModInd = [ie];
    ERABReleaseCommand sequence { "protocolIEs": ies };
    ERABReleaseIndication sequence { "protocolIEs": ies };
    ERABReleaseItemBearerRelComp sequence { "e-RAB-ID": _, "iE-Extensions"? extensions };
    ERABReleaseListBearerRelComp = [ie];
    ERABReleaseResponse sequence { "protocolIEs": ies };
    ERABSecurityResultItem sequence { "e-RAB-ID": _, "securityResult": SecurityResult, "iE-Extensions"? extensions };
    ERABSecurityResultList = [ie];
    ERABSetupItemBearerSURes sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "iE-Extensions"? extensions };
    ERABSetupItemCtxtSURes sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "iE-Extensions"? extensions };
    ERABSetupListBearerSURes = [ie];
    ERABSetupListCtxtSURes = [ie];
    ERABSetupRequest sequence { "protocolIEs": ies };
    ERABSetupResponse sequence { "protocolIEs": ies };
    ERABSubjecttoDataForwardingList = [ie];
    ERABToBeModifiedItemBearerModInd sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "dL-GTP-TEID": _, "iE-Extensions"? extensions };
    ERABToBeModifiedItemBearerModReq sequence { "e-RAB-ID": _, "e-RABLevelQoSParameters": ERABLevelQoSParameters, "nAS-PDU": _, "iE-Extensions"? extensions };
    ERABToBeModifiedListBearerModInd = [ie];
    ERABToBeModifiedListBearerModReq = [ie];
    ERABToBeSetupItemBearerSUReq sequence { "e-RAB-ID": _, "e-RABlevelQoSParameters": ERABLevelQoSParameters, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "nAS-PDU": _, "iE-Extensions"? extensions };
    ERABToBeSetupItemCtxtSUReq sequence { "e-RAB-ID": _, "e-RABlevelQoSParameters": ERABLevelQoSParameters, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "nAS-PDU"? _, "iE-Extensions"? extensions };
    ERABToBeSetupItemHOReq sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "e-RABlevelQosParameters": ERABLevelQoSParameters, "iE-Extensions"? extensions };
    ERABToBeSetupListBearerSUReq = [ie];
    ERABToBeSetupListCtxtSUReq = [ie];
    ERABToBeSetupListHOReq = [ie];
    ERABToBeSwitchedDLItem sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "iE-Extensions"? extensions };
    ERABToBeSwitchedDLList = [ie];
    ERABToBeSwitchedULItem sequence { "e-RAB-ID": _, "transportLayerAddress": TransportLayerAddress, "gTP-TEID": _, "iE-Extensions"? extensions };
    ERABToBeSwitchedULList = [ie];
    ERABToBeUpdatedItem sequence { "e-RAB-ID": _, "securityIndication"? SecurityIndication, "iE-Extensions"? extensions };
    ERABToBeUpdatedList = [ie];
    ERABUsageReportItem sequence { "startTimestamp": _, "endTimestamp": _, "usageCountUL": _, "usageCountDL": _, "iE-Extensions"? extensions };
    ERABUsageReportList = [ie];
    EUTRANCGI sequence { "pLMNidentity": _, "cell-ID": _, "iE-Extensions"? extensions };
    EmergencyAreaIDBroadcast = [EmergencyAreaIDBroadcastItem];
    EmergencyAreaIDBroadcastItem sequence { "emergencyAreaID": _, "completedCellinEAI": CompletedCellinEAI, "iE-Extensions"? extensions };
    EmergencyAreaIDCancelled = [EmergencyAreaIDCancelledItem];
    EmergencyAreaIDCancelledItem sequence { "emergencyAreaID": _, "cancelledCellinEAI": CancelledCellinEAI, "iE-Extensions"? extensions };
    EmergencyAreaIDList = [_];
    EmergencyAreaIDListForRestart = [_];
    EnGNBID = bits;
    ErrorIndication sequence { "protocolIEs": ies };
    EventL1LoggedMDTConfig sequence { "l1Threshold": MeasurementThresholdL1LoggedMDT, "hysteresis": _, "timeToTrigger": _, "iE-Extensions"? extensions };
    EventTrigger choice { "outOfCoverage": _, "eventL1LoggedMDTConfig": EventL1LoggedMDTConfig, "choice-Extensions": ie };
    ExpectedUEActivityBehaviour sequence { "expectedActivityPeriod"? _, "expectedIdlePeriod"? _, "sourceofUEActivityBehaviourInformation"? _, "iE-Extensions"? extensions };
    ExpectedUEBehaviour sequence { "expectedActivity"? ExpectedUEActivityBehaviour, "expectedHOInterval"? _, "iE-Extensions"? extensions };
    FiveGSTAI sequence { "pLMNidentity": _, "fiveGSTAC": _, "iE-Extensions"? extensions };
    ForbiddenLACs = [_];
    ForbiddenLAs = [ForbiddenLAsItem];
    ForbiddenLAsItem sequence { "pLMN-Identity": _, "forbiddenLACs": ForbiddenLACs, "iE-Extensions"? extensions };
    ForbiddenTACs = [_];
    ForbiddenTAs = [ForbiddenTAsItem];
    ForbiddenTAsItem sequence { "pLMN-Identity": _, "forbiddenTACs": ForbiddenTACs, "iE-Extensions"? extensions };
    GBRQosInformation sequence { "e-RAB-MaximumBitrateDL": _, "e-RAB-MaximumBitrateUL": _, "e-RAB-GuaranteedBitrateDL": _, "e-RAB-GuaranteedBitrateUL": _, "iE-Extensions"? extensions };
    GERANCellID sequence { "lAI": LAI, "rAC": _, "cI": _, "iE-Extensions"? extensions };
    GNB sequence { "global-gNB-ID": GlobalGNBID, "iE-Extensions"? extensions };
    GNBID = bits;
    GNBIdentity choice { "gNB-ID": GNBID };
    GUMMEI sequence { "pLMN-Identity": _, "mME-Group-ID": _, "mME-Code": _, "iE-Extensions"? extensions };
    GUMMEIList = [GUMMEI];
    GlobalENBID sequence { "pLMNidentity": _, "eNB-ID": ENBID, "iE-Extensions"? extensions };
    GlobalEnGNBID sequence { "pLMNidentity": _, "en-gNB-ID": EnGNBID, "iE-Extensions"? extensions };
    GlobalGNBID sequence { "pLMN-Identity": _, "gNB-ID": GNBIdentity, "iE-Extensions"? extensions };
    GlobalRANNODEID choice { "gNB": GNB, "ng-eNB": NGENB };
    HandoverCancel sequence { "protocolIEs": ies };
    HandoverCancelAcknowledge sequence { "protocolIEs": ies };
    HandoverCommand sequence { "protocolIEs": ies };
    HandoverFailure sequence { "protocolIEs": ies };
    HandoverNotify sequence { "protocolIEs": ies };
    HandoverPreparationFailure sequence { "protocolIEs": ies };
    HandoverRequest sequence { "protocolIEs": ies };
    HandoverRequestAcknowledge sequence { "protocolIEs": ies };
    HandoverRequired sequence { "protocolIEs": ies };
    HandoverRestrictionList sequence { "servingPLMN": _, "equivalentPLMNs"? EPLMNs, "forbiddenTAs"? ForbiddenTAs, "forbiddenLAs"? ForbiddenLAs, "forbiddenInterRATs"? _, "iE-Extensions"? extensions };
    HandoverSuccess sequence { "protocolIEs": ies };
    ImmediateMDT sequence { "measurementsToActivate": _, "m1reportingTrigger": _, "m1thresholdeventA2"? M1ThresholdEventA2, "m1periodicReporting"? M1PeriodicReporting, "iE-Extensions"? extensions };
    InformationOnRecommendedCellsAndENBsForPaging sequence { "recommendedCellsForPaging": RecommendedCellsForPaging, "recommendENBsForPaging": RecommendedENBsForPaging, "iE-Extensions"? extensions };
    InitialContextSetupFailure sequence { "protocolIEs": ies };
    InitialContextSetupRequest sequence { "protocolIEs": ies };
    InitialContextSetupResponse sequence { "protocolIEs": ies };
    InitialUEMessage sequence { "protocolIEs": ies };
    InitiatingMessage sequence { "procedureCode": _, "criticality": _, "value": _ };
    InterSystemInformationTransferType choice { "rIMTransfer": RIMTransfer };
    InterSystemMeasurementItem sequence { "freqBandIndicatorNR": _, "sSBfrequencies": _, "subcarrierSpacingSSB": _, "maxRSIndexCellQual"? _, "sMTC"? _, "threshRS-Index-r15"? _, "sSBToMeasure"? _, "sSRSSIMeasurement"? _, "quantityConfigNR-R15"? _, "excludedCellsToAddModList"? _, "iE-Extensions"? extensions };
    InterSystemMeasurementList = [InterSystemMeasurementItem];
    InterSystemMeasurementParameters sequence { "measurementDuration": _, "interSystemMeasurementList"? InterSystemMeasurementList, "iE-Extensions"? extensions };
    IntersystemMeasurementConfiguration sequence { "rSRP"? _, "rSRQ"? _, "sINR"? _, "interSystemMeasurementParameters": InterSystemMeasurementParameters, "iE-Extensions"? extensions };
    KillRequest sequence { "protocolIEs": ies };
    KillResponse sequence { "protocolIEs": ies };
    LAI sequence { "pLMNidentity": _, "lAC": _, "iE-Extensions"? extensions };
    LTENTNTAIInformation sequence { "servingPLMN": _, "tACList-In-LTE-NTN": TACListInLTENTN, "uE-Location-Derived-TAC"? _, "iE-Extensions"? extensions };
    LastVisitedCellItem choice { "e-UTRAN-Cell": LastVisitedEUTRANCellInformation, "uTRAN-Cell": _, "gERAN-Cell": LastVisitedGERANCellInformation, "nG-RAN-Cell": _ };
    LastVisitedEUTRANCellInformation sequence { "global-Cell-ID": EUTRANCGI, "cellType": CellType, "time-UE-StayedInCell": _, "iE-Extensions"? extensions };
    LastVisitedGERANCellInformation choice { "undefined": _ };
    LastVisitedPSCellInformation sequence { "pSCellID"? PSCellInformation, "timeStay": _, "iE-Extensions"? extensions };
    LastVisitedPSCellList = [LastVisitedPSCellInformation];
    ListeningSubframePattern sequence { "pattern-period": _, "pattern-offset": _, "iE-Extensions"? extensions };
    LocationReport sequence { "protocolIEs": ies };
    LocationReportingControl sequence { "protocolIEs": ies };
    LocationReportingFailureIndication sequence { "protocolIEs": ies };
    LoggedMBSFNMDT sequence { "loggingInterval": _, "loggingDuration": _, "mBSFN-ResultToLog"? MBSFNResultToLog, "iE-Extensions"? extensions };
    LoggedMDT sequence { "loggingInterval": _, "loggingDuration": _, "iE-Extensions"? extensions };
    LoggedMDTTrigger choice { "periodical": _, "eventTrigger": EventTrigger };
    M1PeriodicReporting sequence { "reportInterval": _, "reportAmount": _, "iE-Extensions"? extensions };
    M1ThresholdEventA2 sequence { "measurementThreshold": MeasurementThresholdA2, "iE-Extensions"? extensions };
    M3Configuration sequence { "m3period": _, "iE-Extensions"? extensions };
    M4Configuration sequence { "m4period": _, "m4-links-to-log": _, "iE-Extensions"? extensions };
    M5Configuration sequence { "m5period": _, "m5-links-to-log": _, "iE-Extensions"? extensions };
    M6Configuration sequence { "m6report-Interval": _, "m6delay-threshold"? _, "m6-links-to-log": _, "iE-Extensions"? extensions };
    M7Configuration sequence { "m7period": _, "m7-links-to-log": _, "iE-Extensions"? extensions };
    MBSFNResultToLog = [MBSFNResultToLogInfo];
    MBSFNResultToLogInfo sequence { "mBSFN-AreaId"? _, "carrierFreq": _, "iE-Extensions"? extensions };
    MDTConfiguration sequence { "mdt-Activation": _, "areaScopeOfMDT": AreaScopeOfMDT, "mDTMode": MDTMode, "iE-Extensions"? extensions };
    MDTMode choice { "immediateMDT": ImmediateMDT, "loggedMDT": LoggedMDT, "mDTMode-Extension": ie };
    MDTPLMNList = [_];
    MMECPRelocationIndication sequence { "protocolIEs": ies };
    MMEConfigurationTransfer sequence { "protocolIEs": ies };
    MMEConfigurationUpdate sequence { "protocolIEs": ies };
    MMEConfigurationUpdateAcknowledge sequence { "protocolIEs": ies };
    MMEConfigurationUpdateFailure sequence { "protocolIEs": ies };
    MMEDirectInformationTransfer sequence { "protocolIEs": ies };
    MMEEarlyStatusTransfer sequence { "protocolIEs": ies };
    MMEPagingTarget choice { "global-ENB-ID": GlobalENBID, "tAI": TAI };
    MMEStatusTransfer sequence { "protocolIEs": ies };
    MeasurementThresholdA2 choice { "threshold-RSRP": _, "threshold-RSRQ": _ };
    MeasurementThresholdL1LoggedMDT choice { "threshold-RSRP": _, "threshold-RSRQ": _, "choice-Extensions": ie };
    MutingPatternInformation sequence { "muting-pattern-period": _, "muting-pattern-offset"? _, "iE-Extensions"? extensions };
    NASDeliveryIndication sequence { "protocolIEs": ies };
    NASNonDeliveryIndication sequence { "protocolIEs": ies };
    NBIoTPagingEDRXInformation sequence { "nB-IoT-paging-eDRX-Cycle": _, "nB-IoT-pagingTimeWindow"? _, "iE-Extensions"? extensions };
    NGENB sequence { "global-ng-eNB-ID": GlobalENBID, "iE-Extensions"? extensions };
    NRCGI sequence { "pLMNIdentity": _, "nRCellIdentity": _, "iE-Extensions"? extensions };
    NRUESecurityCapabilities sequence { "nRencryptionAlgorithms": _, "nRintegrityProtectionAlgorithms": _, "iE-Extensions"? extensions };
    NRUESidelinkAggregateMaximumBitrate sequence { "uEaggregateMaximumBitRate": _, "iE-Extensions"? extensions };
    NRV2XServicesAuthorized sequence { "vehicleUE"? _, "pedestrianUE"? _, "iE-Extensions"? extensions };
    OverloadResponse choice { "overloadAction": _ };
    OverloadStart sequence { "protocolIEs": ies };
    OverloadStop sequence { "protocolIEs": ies };
    PC5FlowBitRates sequence { "guaranteedFlowBitRate": _, "maximumFlowBitRate": _, "iE-Extensions"? extensions };
    PC5QoSFlowItem sequence { "pQI": _, "pc5FlowBitRates"? PC5FlowBitRates, "range"? _, "iE-Extensions"? extensions };
    PC5QoSFlowList = [PC5QoSFlowItem];
    PC5QoSParameters sequence { "pc5QoSFlowList": PC5QoSFlowList, "pc5LinkAggregatedBitRates"? _, "iE-Extensions"? extensions };
    PLMNAreaBasedQMC sequence { "plmnListforQMC": PLMNListforQMC, "iE-Extensions"? extensions };
    PLMNListforQMC = [_];
    PSCellInformation sequence { "nCGI": NRCGI, "iE-Extensions"? extensions };
    PWSFailureIndication sequence { "protocolIEs": ies };
    PWSRestartIndication sequence { "protocolIEs": ies };
    PWSfailedECGIList = [EUTRANCGI];
    Paging sequence { "protocolIEs": ies };
    PagingAttemptInformation sequence { "pagingAttemptCount": _, "intendedNumberOfPagingAttempts": _, "nextPagingAreaScope"? _, "iE-Extensions"? extensions };
    PagingEDRXInformation sequence { "paging-eDRX-Cycle": _, "pagingTimeWindow"? _, "iE-Extensions"? extensions };
    PathSwitchRequest sequence { "protocolIEs": ies };
    PathSwitchRequestAcknowledge sequence { "protocolIEs": ies };
    PathSwitchRequestFailure sequence { "protocolIEs": ies };
    PrivateIEID choice { "local": _, "global": _ };
    PrivateMessage sequence { "privateIEs": PrivateMessagePrivateIEs };
    PrivateMessagePrivateIEs = [AnonymousPrivateMessagePrivateIEs];
    ProSeAuthorized sequence { "proSeDirectDiscovery"? _, "proSeDirectCommunication"? _, "iE-Extensions"? extensions };
    RATRestrictions = [RATRestrictionsItem];
    RATRestrictionsItem sequence { "pLMNidentity": _, "rAT-RestrictionInformation": _, "iE-Extensions"? extensions };
    RIMRoutingAddress choice { "gERAN-Cell-ID": GERANCellID, "targetRNC-ID": TargetRNCID, "eHRPD-Sector-ID": _ };
    RIMTransfer sequence { "rIMInformation": _, "rIMRoutingAddress"? RIMRoutingAddress, "iE-Extensions"? extensions };
    RLFReportInformation sequence { "uE-RLF-Report-Container": _, "uE-RLF-Report-Container-for-extended-bands"? _, "iE-Extensions"? extensions };
    ReceiveStatusOfULPDCPSDUsExtended = bits;
    ReceiveStatusOfULPDCPSDUsPDCPSNlength18 = bits;
    RecommendedCellItem sequence { "eUTRAN-CGI": EUTRANCGI, "timeStayedInCell"? _, "iE-Extensions"? extensions };
    RecommendedCellList = [ie];
    RecommendedCellsForPaging sequence { "recommendedCellList": RecommendedCellList, "iE-Extensions"? extensions };
    RecommendedENBItem sequence { "mMEPagingTarget": MMEPagingTarget, "iE-Extensions"? extensions };
    RecommendedENBList = [ie];
    RecommendedENBsForPaging sequence { "recommendedENBList": RecommendedENBList, "iE-Extensions"? extensions };
    RequestType sequence { "eventType": _, "reportArea": _, "iE-Extensions"? extensions };
    RequestedTNLInfo sequence { "pLMNidentity": _, "iE-Extensions"? extensions };
    RerouteNASRequest sequence { "protocolIEs": ies };
    Reset sequence { "protocolIEs": ies };
    ResetAcknowledge sequence { "protocolIEs": ies };
    ResetType choice { "s1-Interface": _, "partOfS1-Interface": UEAssociatedLogicalS1ConnectionListRes };
    RetrieveUEInformation sequence { "protocolIEs": ies };
    S1APPDU choice { "initiatingMessage": InitiatingMessage, "successfulOutcome": SuccessfulOutcome, "unsuccessfulOutcome": UnsuccessfulOutcome };
    S1RemovalFailure sequence { "protocolIEs": ies };
    S1RemovalRequest sequence { "protocolIEs": ies };
    S1RemovalResponse sequence { "protocolIEs": ies };
    S1SetupFailure sequence { "protocolIEs": ies };
    S1SetupRequest sequence { "protocolIEs": ies };
    S1SetupResponse sequence { "protocolIEs": ies };
    SONConfigurationTransfer sequence { "targeteNB-ID": TargeteNBID, "sourceeNB-ID": SourceeNBID, "sONInformation": SONInformation, "iE-Extensions"? extensions };
    SONInformation choice { "sONInformationRequest": _, "sONInformationReply": SONInformationReply, "sONInformation-Extension": ie };
    SONInformationReply sequence { "x2TNLConfigurationInfo"? X2TNLConfigurationInfo, "iE-Extensions"? extensions };
    SONInformationReport choice { "rLFReportInformation": RLFReportInformation };
    STMSI sequence { "mMEC": _, "m-TMSI": _, "iE-Extensions"? extensions };
    ScheduledCommunicationTime sequence { "dayofWeek"? _, "timeofDayStart"? _, "timeofDayEnd"? _, "iE-Extensions"? extensions };
    SecondaryRATDataUsageReport sequence { "protocolIEs": ies };
    SecondaryRATDataUsageReportItem sequence { "e-RAB-ID": _, "secondaryRATType": _, "e-RABUsageReportList": ERABUsageReportList, "iE-Extensions"? extensions };
    SecondaryRATDataUsageReportList = [ie];
    SecurityContext sequence { "nextHopChainingCount": _, "nextHopParameter": _, "iE-Extensions"? extensions };
    SecurityIndication sequence { "integrityProtectionIndication": _, "iE-Extensions"? extensions };
    SecurityResult sequence { "integrityProtectionResult": _, "iE-Extensions"? extensions };
    SensorMeasConfigNameItem sequence { "sensorNameConfig": SensorNameConfig, "iE-Extensions"? extensions };
    SensorMeasConfigNameList = [SensorMeasConfigNameItem];
    SensorMeasurementConfiguration sequence { "sensorMeasConfig": _, "sensorMeasConfigNameList"? SensorMeasConfigNameList, "iE-Extensions"? extensions };
    SensorNameConfig choice { "uncompensatedBarometricConfig": _, "choice-Extensions": ie };
    ServedDCNs = [ServedDCNsItem];
    ServedDCNsItem sequence { "dCN-ID": _, "relativeDCNCapacity": _, "iE-Extensions"? extensions };
    ServedGUMMEIs = [ServedGUMMEIsItem];
    ServedGUMMEIsItem sequence { "servedPLMNs": ServedPLMNs, "servedGroupIDs": ServedGroupIDs, "servedMMECs": ServedMMECs, "iE-Extensions"? extensions };
    ServedGroupIDs = [_];
    ServedMMECs = [_];
    ServedPLMNs = [_];
    SourceNgRanNodeID sequence { "global-RAN-NODE-ID": GlobalRANNODEID, "selected-TAI": FiveGSTAI, "iE-Extensions"? extensions };
    SourceNodeID choice { "sourceNgRanNode-ID": SourceNgRanNodeID, "sourceNodeID-Extension": ie };
    SourceeNBID sequence { "global-ENB-ID": GlobalENBID, "selected-TAI": TAI, "iE-Extensions"? extensions };
    SourceeNBToTargeteNBTransparentContainer sequence { "rRC-Container": _, "e-RABInformationList"? ERABInformationList, "targetCell-ID": EUTRANCGI, "subscriberProfileIDforRFP"? _, "uE-HistoryInformation": UEHistoryInformation, "iE-Extensions"? extensions };
    SubscriptionBasedUEDifferentiationInfo sequence { "periodicCommunicationIndicator"? _, "periodicTime"? _, "scheduledCommunicationTime"? ScheduledCommunicationTime, "stationaryIndication"? _, "trafficProfile"? _, "batteryIndication"? _, "iE-Extensions"? extensions };
    SuccessfulOutcome sequence { "procedureCode": _, "criticality": _, "value": _ };
    SupportedTAs = [SupportedTAsItem];
    SupportedTAsItem sequence { "tAC": _, "broadcastPLMNs": BPLMNs, "iE-Extensions"? extensions };
    SynchronisationInformation sequence { "sourceStratumLevel"? _, "listeningSubframePattern"? ListeningSubframePattern, "aggressoreCGI-List"? ECGI_List, "iE-Extensions"? extensions };
    TABasedMDT sequence { "tAListforMDT": TAListforMDT, "iE-Extensions"? extensions };
    TABasedQMC sequence { "tAListforQMC": TAListforQMC, "iE-Extensions"? extensions };
    TACListInLTENTN = [_];
    TAI sequence { "pLMNidentity": _, "tAC": _, "iE-Extensions"? extensions };
    TAIBasedMDT sequence { "tAIListforMDT": TAIListforMDT, "iE-Extensions"? extensions };
    TAIBasedQMC sequence { "tAIListforQMC": TAIListforQMC, "iE-Extensions"? extensions };
    TAIBroadcast = [TAIBroadcastItem];
    TAIBroadcastItem sequence { "tAI": TAI, "completedCellinTAI": CompletedCellinTAI, "iE-Extensions"? extensions };
    TAICancelled = [TAICancelledItem];
    TAICancelledItem sequence { "tAI": TAI, "cancelledCellinTAI": CancelledCellinTAI, "iE-Extensions"? extensions };
    TAIItem sequence { "tAI": TAI, "iE-Extensions"? extensions };
    TAIList = [ie];
    TAIListForRestart = [TAI];
    TAIListforMDT = [TAI];
    TAIListforQMC = [TAI];
    TAIListforWarning = [TAI];
    TAListforMDT = [_];
    TAListforQMC = [_];
    TargetID choice { "targeteNB-ID": TargeteNBID, "targetRNC-ID": TargetRNCID, "cGI": CGI, "targetgNgRanNode-ID": TargetNgRanNodeID };
    TargetNgRanNodeID sequence { "global-RAN-NODE-ID": GlobalRANNODEID, "selected-TAI": FiveGSTAI, "iE-Extensions"? extensions };
    TargetRNCID sequence { "lAI": LAI, "rAC"? _, "rNC-ID": _, "extendedRNC-ID"? _, "iE-Extensions"? extensions };
    TargeteNBID sequence { "global-ENB-ID": GlobalENBID, "selected-TAI": TAI, "iE-Extensions"? extensions };
    TargeteNBToSourceeNBTransparentContainer sequence { "rRC-Container": _, "iE-Extensions"? extensions };
    TimeBasedHandoverInformation sequence { "hOWindowStart": _, "hOWindowDuration": _, "iE-Extensions"? extensions };
    TimeSynchronisationInfo sequence { "stratumLevel": _, "synchronisationStatus": _, "iE-Extensions"? extensions };
    TraceActivation sequence { "e-UTRAN-Trace-ID": _, "interfacesToTrace": _, "traceDepth": _, "traceCollectionEntityIPAddress": TransportLayerAddress, "iE-Extensions"? extensions };
    TraceFailureIndication sequence { "protocolIEs": ies };
    TraceStart sequence { "protocolIEs": ies };
    TransportInformation sequence { "transportLayerAddress": TransportLayerAddress, "uL-GTP-TEID": _ };
    TransportLayerAddress = bits;
    TunnelInformation sequence { "transportLayerAddress": TransportLayerAddress, "uDP-Port-Number"? _, "iE-Extensions"? extensions };
    UEAggregateMaximumBitrate sequence { "uEaggregateMaximumBitRateDL": _, "uEaggregateMaximumBitRateUL": _, "iE-Extensions"? extensions };
    UEAppLayerMeasConfig sequence { "containerForAppLayerMeasConfig": _, "areaScopeOfQMC": AreaScopeOfQMC, "iE-Extensions"? extensions };
    UEAssociatedLogicalS1ConnectionItem sequence { "mME-UE-S1AP-ID"? _, "eNB-UE-S1AP-ID"? _, "iE-Extensions"? extensions };
    UEAssociatedLogicalS1ConnectionListRes = [ie];
    UEAssociatedLogicalS1ConnectionListResAck = [ie];
    UECapabilityInfoIndication sequence { "protocolIEs": ies };
    UEContextModificationConfirm sequence { "protocolIEs": ies };
    UEContextModificationFailure sequence { "protocolIEs": ies };
    UEContextModificationIndication sequence { "protocolIEs": ies };
    UEContextModificationRequest sequence { "protocolIEs": ies };
    UEContextModificationResponse sequence { "protocolIEs": ies };
    UEContextReleaseCommand sequence { "protocolIEs": ies };
    UEContextReleaseComplete sequence { "protocolIEs": ies };
    UEContextReleaseRequest sequence { "protocolIEs": ies };
    UEContextResumeFailure sequence { "protocolIEs": ies };
    UEContextResumeRequest sequence { "protocolIEs": ies };
    UEContextResumeResponse sequence { "protocolIEs": ies };
    UEContextSuspendRequest sequence { "protocolIEs": ies };
    UEContextSuspendResponse sequence { "protocolIEs": ies };
    UEHistoryInformation = [LastVisitedCellItem];
    UEInformationTransfer sequence { "protocolIEs": ies };
    UEPagingID choice { "s-TMSI": STMSI, "iMSI": _ };
    UERadioCapabilityIDMappingRequest sequence { "protocolIEs": ies };
    UERadioCapabilityIDMappingResponse sequence { "protocolIEs": ies };
    UERadioCapabilityMatchRequest sequence { "protocolIEs": ies };
    UERadioCapabilityMatchResponse sequence { "protocolIEs": ies };
    UES1APIDPair sequence { "mME-UE-S1AP-ID": _, "eNB-UE-S1AP-ID": _, "iE-Extensions"? extensions };
    UES1APIDs choice { "uE-S1AP-ID-pair": UES1APIDPair, "mME-UE-S1AP-ID": _ };
    UESecurityCapabilities sequence { "encryptionAlgorithms": _, "integrityProtectionAlgorithms": _, "iE-Extensions"? extensions };
    UESidelinkAggregateMaximumBitrate sequence { "uESidelinkAggregateMaximumBitRate": _, "iE-Extensions"? extensions };
    ULCPSecurityInformation sequence { "ul-NAS-MAC": _, "ul-NAS-Count": _, "iE-Extensions"? extensions };
    UnsuccessfulOutcome sequence { "procedureCode": _, "criticality": _, "value": _ };
    UplinkNASTransport sequence { "protocolIEs": ies };
    UplinkNonUEAssociatedLPPaTransport sequence { "protocolIEs": ies };
    UplinkS1cdma2000tunnelling sequence { "protocolIEs": ies };
    UplinkUEAssociatedLPPaTransport sequence { "protocolIEs": ies };
    UserLocationInformation sequence { "eutran-cgi": EUTRANCGI, "tai": TAI, "iE-Extensions"? extensions };
    V2XServicesAuthorized sequence { "vehicleUE"? _, "pedestrianUE"? _, "iE-Extensions"? extensions };
    WLANMeasConfigNameList = [_];
    WLANMeasurementConfiguration sequence { "wlanMeasConfig": _, "wlanMeasConfigNameList"? WLANMeasConfigNameList, "wlan-rssi"? _, "wlan-rtt"? _, "iE-Extensions"? extensions };
    WUSAssistanceInformation sequence { "pagingProbabilityInformation": _, "iE-Extensions"? extensions };
    WarningAreaList choice { "cellIDList": ECGIList, "trackingAreaListforWarning": TAIListforWarning, "emergencyAreaIDList": EmergencyAreaIDList };
    WriteReplaceWarningRequest sequence { "protocolIEs": ies };
    WriteReplaceWarningResponse sequence { "protocolIEs": ies };
    X2TNLConfigurationInfo sequence { "eNBX2TransportLayerAddresses": ENBX2TLAs, "iE-Extensions"? extensions };
}
use crate::inspect::open_types;
open_types! { crate::s1ap::s1_ap_containers::ProtocolIEField { value } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolIEContainer { 0 } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolExtensionField { extension_value } }
open_types! { crate::s1ap::s1_ap_containers::ProtocolExtensionContainer { 0 } }
open_types! { crate::s1ap::s1_ap_ies::AdditionalGUTI { g_ummei, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AdditionalCSFallbackIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::AdditionalRRMPriorityIndex {} }
open_types! { crate::s1ap::s1_ap_ies::AerialUEsubscriptionInformation {} }
open_types! { crate::s1ap::s1_ap_ies::AllocationAndRetentionPriority { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AreaScopeOfMDT { cellBased, tABased, tAIBased } else { pLMNWide } }
open_types! { crate::s1ap::s1_ap_ies::AreaScopeOfQMC { cellBased, tABased, tAIBased, pLMNAreaBased } else {} }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForCECapableUEs { cell_identifier_and_celevel_for_cecapable_ues, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForPaging { assistance_data_for_recommended_cells, assistance_data_for_cecapable_ues, paging_attempt_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::AssistanceDataForRecommendedCells { recommended_cells_for_paging, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearerType {} }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToDLDiscardingItem { d_l_discarding, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToDLDiscardingList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToEarlyStatusTransferItem { d_lcount_pdcp_snlength, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToEarlyStatusTransferList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToStatusTransferItem { u_l_countvalue, d_l_countvalue, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BearersSubjectToStatusTransferList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::BluetoothMeasurementConfiguration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::BroadcastCancelledAreaList { cellID_Cancelled, tAI_Cancelled, emergencyAreaID_Cancelled } else {} }
open_types! { crate::s1ap::s1_ap_ies::BroadcastCompletedAreaList { cellID_Broadcast, tAI_Broadcast, emergencyAreaID_Broadcast } else {} }
open_types! { crate::s1ap::s1_ap_ies::CEModeBRestricted {} }
open_types! { crate::s1ap::s1_ap_ies::CEModeBSupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::CGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CNDomain {} }
open_types! { crate::s1ap::s1_ap_ies::CNTypeRestrictions { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CNTypeRestrictionsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTValueExtended { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTvalue { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::COUNTvaluePDCPSNlength18 { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CSFallbackIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::CSGId {} }
open_types! { crate::s1ap::s1_ap_ies::CSGIdList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CSGIdListItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CSGMembershipStatus {} }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinEAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinEAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinTAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CancelledCellinTAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::Cause {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000HORequiredIndication {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000HOStatus {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000OneXRAND {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000OneXSRVCCInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000PDU {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000RATType {} }
open_types! { crate::s1ap::s1_ap_ies::Cdma2000SectorID {} }
open_types! { crate::s1ap::s1_ap_ies::CellAccessMode {} }
open_types! { crate::s1ap::s1_ap_ies::CellBasedMDT { cell_id_listfor_mdt, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellBasedQMC { cell_id_listfor_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIDBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIDBroadcastItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIDCancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIDCancelledItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellIdListforMDT { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIdListforQMC { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CellIdentifierAndCELevelForCECapableUEs { global_cell_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CellType { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CoarseUELocation {} }
open_types! { crate::s1ap::s1_ap_ies::CoarseUELocationRequested {} }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinEAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinEAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinTAI { 0 } }
open_types! { crate::s1ap::s1_ap_ies::CompletedCellinTAIItem { e_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ConcurrentWarningMessageIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ConnectedengNBItem { supported_tas, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ConnectedengNBList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ContextatSource { source_ng_ran_node_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CorrelationID {} }
open_types! { crate::s1ap::s1_ap_ies::CoverageLevel {} }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnostics { i_es_criticality_diagnostics, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnosticsIEItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::CriticalityDiagnosticsIEList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::DAPSRequestInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfoItem { d_apsresponse_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DAPSResponseInfoList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::DCNID {} }
open_types! { crate::s1ap::s1_ap_ies::DLCPSecurityInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::DLCOUNTPDCPSNlength { dLCOUNTValuePDCP_SNlength12, dLCOUNTValuePDCP_SNlength15, dLCOUNTValuePDCP_SNlength18 } else {} }
open_types! { crate::s1ap::s1_ap_ies::DLDiscarding { discardDLCOUNTValuePDCP_SNlength12, discardDLCOUNTValuePDCP_SNlength15, discardDLCOUNTValuePDCP_SNlength18 } else {} }
open_types! { crate::s1ap::s1_ap_ies::DLNASPDUDeliveryAckRequest {} }
open_types! { crate::s1ap::s1_ap_ies::DataForwardingNotPossible {} }
open_types! { crate::s1ap::s1_ap_ies::DataCodingScheme {} }
open_types! { crate::s1ap::s1_ap_ies::DataSize {} }
open_types! { crate::s1ap::s1_ap_ies::DirectForwardingPathAvailability {} }
open_types! { crate::s1ap::s1_ap_ies::ERABInformationList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABInformationListItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABLevelQoSParameters { allocation_retention_priority, gbr_qos_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABSecurityResultItem { security_result, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABSecurityResultList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ERABUsageReportItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ERABUsageReportList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EUTRANTraceID {} }
open_types! { crate::s1ap::s1_ap_ies::ECGI_List { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ECGIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ECGIListForRestart { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EDTSession {} }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONConfigurationTransfer { transfertype, s_oninformation, x2_tnlconfig_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONTransferType { request, reply } else {} }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONeNBIdentification { globale_nbid, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCSONengNBIdentification { globaleng_nbid, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCTransferTypeReply { sourceeng_nb, targete_nb, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENDCTransferTypeRequest { sourcee_nb, targeteng_nb, targete_nb, associated_tai, broadcast5_gstai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBEarlyStatusTransferTransparentContainer { bearers_subject_to_early_status_transfer_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBStatusTransferTransparentContainer { bearers_subject_to_status_transfer_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBUES1APID {} }
open_types! { crate::s1ap::s1_ap_ies::ENBIndirectX2TransportLayerAddresses {} }
open_types! { crate::s1ap::s1_ap_ies::ENBX2ExtTLA { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ENBX2ExtTLAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ENBname {} }
open_types! { crate::s1ap::s1_ap_ies::EUTRANCGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EUTRANRoundTripDelayEstimationInfo {} }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDBroadcastItem { completed_cellin_eai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDCancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDCancelledItem { cancelled_cellin_eai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EmergencyAreaIDListForRestart {} }
open_types! { crate::s1ap::s1_ap_ies::EmergencyIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::EndIndication {} }
open_types! { crate::s1ap::s1_ap_ies::EnhancedCoverageRestricted {} }
open_types! { crate::s1ap::s1_ap_ies::EthernetType {} }
open_types! { crate::s1ap::s1_ap_ies::EventL1LoggedMDTConfig { l1_threshold, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::EventTrigger { eventL1LoggedMDTConfig, choice_Extensions } else { outOfCoverage } }
open_types! { crate::s1ap::s1_ap_ies::ExpectedUEActivityBehaviour { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ExpectedUEBehaviour { expected_activity, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ExtendedUEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::ExtendedBitRate {} }
open_types! { crate::s1ap::s1_ap_ies::ExtendedRepetitionPeriod {} }
open_types! { crate::s1ap::s1_ap_ies::FiveGSTAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenLAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenLAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenTAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ForbiddenTAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GBRQosInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GERANCellID { l_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GNB { global_g_nb_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::GUMMEIType {} }
open_types! { crate::s1ap::s1_ap_ies::GWContextReleaseIndication {} }
open_types! { crate::s1ap::s1_ap_ies::GlobalENBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GlobalGNBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::GlobalRANNODEID { gNB, ng_eNB } else {} }
open_types! { crate::s1ap::s1_ap_ies::GlobalEnGNBID { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::HandoverFlag {} }
open_types! { crate::s1ap::s1_ap_ies::HandoverRestrictionList { forbidden_tas, forbidden_las, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::HandoverType {} }
open_types! { crate::s1ap::s1_ap_ies::IABAuthorized {} }
open_types! { crate::s1ap::s1_ap_ies::IABNodeIndication {} }
open_types! { crate::s1ap::s1_ap_ies::IABSupported {} }
open_types! { crate::s1ap::s1_ap_ies::IMSvoiceEPSfallbackfrom5G {} }
open_types! { crate::s1ap::s1_ap_ies::ImmediateMDT { m1thresholdevent_a2, m1periodic_reporting, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InformationOnRecommendedCellsAndENBsForPaging { recommended_cells_for_paging, recommend_enbs_for_paging, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::InterSystemMeasurementParameters { inter_system_measurement_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::IntersystemMeasurementConfiguration { inter_system_measurement_parameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::IntersystemSONConfigurationTransfer {} }
open_types! { crate::s1ap::s1_ap_ies::KillAllWarningMessages {} }
open_types! { crate::s1ap::s1_ap_ies::LAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LHNID {} }
open_types! { crate::s1ap::s1_ap_ies::LPPaPDU {} }
open_types! { crate::s1ap::s1_ap_ies::LTEMIndication {} }
open_types! { crate::s1ap::s1_ap_ies::LTENTNTAIInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedCellItem { e_UTRAN_Cell } else { uTRAN_Cell, gERAN_Cell, nG_RAN_Cell } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedEUTRANCellInformation { global_cell_id, cell_type, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedPSCellInformation { p_scell_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LastVisitedPSCellList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ListeningSubframePattern { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMBSFNMDT { m_bsfn_result_to_log, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMDT { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::LoggedMDTTrigger { eventTrigger } else { periodical } }
open_types! { crate::s1ap::s1_ap_ies::M1PeriodicReporting { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M1ThresholdEventA2 { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M3Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M4Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M4ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M5Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M5ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M6Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M6ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::M7Configuration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::M7ReportAmountMDT {} }
open_types! { crate::s1ap::s1_ap_ies::MBSFNResultToLog { 0 } }
open_types! { crate::s1ap::s1_ap_ies::MBSFNResultToLogInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::MDTConfiguration { area_scope_of_mdt, m_dtmode, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::MDTConfigurationNR {} }
open_types! { crate::s1ap::s1_ap_ies::MDTLocationInfo {} }
open_types! { crate::s1ap::s1_ap_ies::MDTMode { immediateMDT, loggedMDT, mDTMode_Extension } else {} }
open_types! { crate::s1ap::s1_ap_ies::MDTPLMNList {} }
open_types! { crate::s1ap::s1_ap_ies::MMEGroupID {} }
open_types! { crate::s1ap::s1_ap_ies::MMEUES1APID {} }
open_types! { crate::s1ap::s1_ap_ies::MMEPagingTarget { global_ENB_ID, tAI } else {} }
open_types! { crate::s1ap::s1_ap_ies::MMERelaySupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::MMEname {} }
open_types! { crate::s1ap::s1_ap_ies::MSClassmark2 {} }
open_types! { crate::s1ap::s1_ap_ies::MSClassmark3 {} }
open_types! { crate::s1ap::s1_ap_ies::ManagementBasedMDTAllowed {} }
open_types! { crate::s1ap::s1_ap_ies::MaskedIMEISV {} }
open_types! { crate::s1ap::s1_ap_ies::MeasurementThresholdL1LoggedMDT { choice_Extensions } else { threshold_RSRP, threshold_RSRQ } }
open_types! { crate::s1ap::s1_ap_ies::MessageIdentifier {} }
open_types! { crate::s1ap::s1_ap_ies::MobilityInformation {} }
open_types! { crate::s1ap::s1_ap_ies::MutingAvailabilityIndication {} }
open_types! { crate::s1ap::s1_ap_ies::MutingPatternInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NASPDU {} }
open_types! { crate::s1ap::s1_ap_ies::NASSecurityParametersfromEUTRAN {} }
open_types! { crate::s1ap::s1_ap_ies::NASSecurityParameterstoEUTRAN {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTDefaultPagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTPagingEDRXInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NBIoTPagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTRLFReportContainer {} }
open_types! { crate::s1ap::s1_ap_ies::NBIoTUEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::NGENB { global_ng_e_nb_id, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRCGI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRUESecurityCapabilities { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRUESidelinkAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRV2XServicesAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::NRrestrictionin5GS {} }
open_types! { crate::s1ap::s1_ap_ies::NRrestrictioninEPSasSecondaryRAT {} }
open_types! { crate::s1ap::s1_ap_ies::NotifySourceeNB {} }
open_types! { crate::s1ap::s1_ap_ies::NumberofBroadcastRequest {} }
open_types! { crate::s1ap::s1_ap_ies::OverloadResponse {} }
open_types! { crate::s1ap::s1_ap_ies::PC5FlowBitRates { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSFlowItem { pc5_flow_bit_rates, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSFlowList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::PC5QoSParameters { pc5_qo_sflow_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PLMNAreaBasedQMC { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PLMNidentity {} }
open_types! { crate::s1ap::s1_ap_ies::PSServiceNotAvailable {} }
open_types! { crate::s1ap::s1_ap_ies::PSCellInformation { n_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PWSfailedECGIList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::PacketLossRate {} }
open_types! { crate::s1ap::s1_ap_ies::PagingEDRXInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PagingAttemptInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::PagingCause {} }
open_types! { crate::s1ap::s1_ap_ies::PagingDRX {} }
open_types! { crate::s1ap::s1_ap_ies::PagingPriority {} }
open_types! { crate::s1ap::s1_ap_ies::PendingDataIndication {} }
open_types! { crate::s1ap::s1_ap_ies::PrivacyIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ProSeAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ProSeUEtoNetworkRelaying {} }
open_types! { crate::s1ap::s1_ap_ies::RACSIndication {} }
open_types! { crate::s1ap::s1_ap_ies::RATRestrictions { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RATRestrictionsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RATType {} }
open_types! { crate::s1ap::s1_ap_ies::RIMRoutingAddress { gERAN_Cell_ID, targetRNC_ID } else { eHRPD_Sector_ID } }
open_types! { crate::s1ap::s1_ap_ies::RIMTransfer { r_imrouting_address, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RLFReportInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RRCEstablishmentCause {} }
open_types! { crate::s1ap::s1_ap_ies::ReceiveStatusOfULPDCPSDUsExtended {} }
open_types! { crate::s1ap::s1_ap_ies::ReceiveStatusOfULPDCPSDUsPDCPSNlength18 {} }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellItem { e_utran_cgi, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedCellsForPaging { recommended_cell_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBItem { m_mepaging_target, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::RecommendedENBsForPaging { recommended_enblist, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RelativeMMECapacity {} }
open_types! { crate::s1ap::s1_ap_ies::RelayNodeIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::RepetitionPeriod {} }
open_types! { crate::s1ap::s1_ap_ies::RequestType { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RequestTypeAdditionalInfo {} }
open_types! { crate::s1ap::s1_ap_ies::RequestedTNLInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::RoutingID {} }
open_types! { crate::s1ap::s1_ap_ies::STMSI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONConfigurationTransfer { targete_nb_id, sourcee_nb_id, s_oninformation, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONInformation { sONInformationReply, sONInformation_Extension } else { sONInformationRequest } }
open_types! { crate::s1ap::s1_ap_ies::SONInformationReply { x2_tnlconfiguration_info, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SONInformationReport { rLFReportInformation } else {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCHOIndication {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCOperationNotPossible {} }
open_types! { crate::s1ap::s1_ap_ies::SRVCCOperationPossible {} }
open_types! { crate::s1ap::s1_ap_ies::ScheduledCommunicationTime { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageReportItem { e_rabusage_report_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageReportList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SecondaryRATDataUsageRequest {} }
open_types! { crate::s1ap::s1_ap_ies::SecurityContext { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecurityIndication { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SecurityKey {} }
open_types! { crate::s1ap::s1_ap_ies::SecurityResult { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasConfigNameItem { sensor_name_config, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasConfigNameList { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SensorMeasurementConfiguration { sensor_meas_config_name_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SensorNameConfig { choice_Extensions } else { uncompensatedBarometricConfig } }
open_types! { crate::s1ap::s1_ap_ies::SerialNumber {} }
open_types! { crate::s1ap::s1_ap_ies::ServedDCNs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ServedDCNsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ServedGUMMEIs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::ServedGUMMEIsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::ServiceType {} }
open_types! { crate::s1ap::s1_ap_ies::SourceToTargetTransparentContainer {} }
open_types! { crate::s1ap::s1_ap_ies::SourceNgRanNodeID { global_ran_node_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SourceNodeID { sourceNgRanNode_ID, sourceNodeID_Extension } else {} }
open_types! { crate::s1ap::s1_ap_ies::SourceeNBID { global_enb_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SourceeNBToTargeteNBTransparentContainer { e_rabinformation_list, target_cell_id, u_e_history_information, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SubscriberProfileIDforRFP {} }
open_types! { crate::s1ap::s1_ap_ies::SubscriptionBasedUEDifferentiationInfo { scheduled_communication_time, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SupportedTAs { 0 } }
open_types! { crate::s1ap::s1_ap_ies::SupportedTAsItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::SynchronisationInformation { listening_subframe_pattern, aggressore_cgi_list, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TABasedMDT { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TABasedQMC { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAI { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBroadcast { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIBroadcastItem { t_ai, completed_cellin_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAICancelled { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAICancelledItem { t_ai, cancelled_cellin_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBasedMDT { t_ailistfor_mdt, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIBasedQMC { t_ailistfor_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TAIListForRestart { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforMDT { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforQMC { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TAIListforWarning { 0 } }
open_types! { crate::s1ap::s1_ap_ies::TargetToSourceTransparentContainer {} }
open_types! { crate::s1ap::s1_ap_ies::TargetID { targeteNB_ID, targetRNC_ID, cGI, targetgNgRanNode_ID } else {} }
open_types! { crate::s1ap::s1_ap_ies::TargetNgRanNodeID { global_ran_node_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargetRNCID { l_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargeteNBID { global_enb_id, selected_tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TargeteNBToSourceeNBTransparentContainer { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeUEStayedInCellEnhancedGranularity {} }
open_types! { crate::s1ap::s1_ap_ies::TimeBasedHandoverInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeRefDistribution {} }
open_types! { crate::s1ap::s1_ap_ies::TimeSinceSecondaryNodeRelease {} }
open_types! { crate::s1ap::s1_ap_ies::TimeSynchronisationInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TimeToWait {} }
open_types! { crate::s1ap::s1_ap_ies::TraceActivation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::TrafficLoadReductionIndication {} }
open_types! { crate::s1ap::s1_ap_ies::TransportInformation {} }
open_types! { crate::s1ap::s1_ap_ies::TransportLayerAddress {} }
open_types! { crate::s1ap::s1_ap_ies::TunnelInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEApplicationLayerMeasurementCapability {} }
open_types! { crate::s1ap::s1_ap_ies::UEHistoryInformation { 0 } }
open_types! { crate::s1ap::s1_ap_ies::UEHistoryInformationFromTheUE {} }
open_types! { crate::s1ap::s1_ap_ies::UERetentionInformation {} }
open_types! { crate::s1ap::s1_ap_ies::UES1APIDPair { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UES1APIDs { uE_S1AP_ID_pair } else { mME_UE_S1AP_ID } }
open_types! { crate::s1ap::s1_ap_ies::UEUsageType {} }
open_types! { crate::s1ap::s1_ap_ies::UEAssociatedLogicalS1ConnectionItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEAppLayerMeasConfig { area_scope_of_qmc, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UECapabilityInfoRequest {} }
open_types! { crate::s1ap::s1_ap_ies::UEIdentityIndexValue {} }
open_types! { crate::s1ap::s1_ap_ies::UEPagingID { s_TMSI } else { iMSI } }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapability {} }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapabilityForPaging {} }
open_types! { crate::s1ap::s1_ap_ies::UERadioCapabilityID {} }
open_types! { crate::s1ap::s1_ap_ies::UESecurityCapabilities { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UESidelinkAggregateMaximumBitrate { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::UEUserPlaneCIoTSupportIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::ULCPSecurityInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::URIAddress {} }
open_types! { crate::s1ap::s1_ap_ies::UnlicensedSpectrumRestriction {} }
open_types! { crate::s1ap::s1_ap_ies::UserLocationInformation { eutran_cgi, tai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::V2XServicesAuthorized { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::VoiceSupportMatchIndicator {} }
open_types! { crate::s1ap::s1_ap_ies::WLANMeasurementConfiguration { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::WUSAssistanceInformation { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_ies::WarningAreaCoordinates {} }
open_types! { crate::s1ap::s1_ap_ies::WarningAreaList { cellIDList, trackingAreaListforWarning } else { emergencyAreaIDList } }
open_types! { crate::s1ap::s1_ap_ies::WarningMessageContents {} }
open_types! { crate::s1ap::s1_ap_ies::WarningSecurityInfo {} }
open_types! { crate::s1ap::s1_ap_ies::WarningType {} }
open_types! { crate::s1ap::s1_ap_ies::X2TNLConfigurationInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::CSGMembershipInfo { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::CellTrafficTrace { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ConnectionEstablishmentIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DeactivateTrace { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkNASTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkNonUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkS1cdma2000tunnelling { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::DownlinkUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABAdmittedItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABAdmittedList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABDataForwardingItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeItemResumeReq { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeItemResumeRes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeListResumeReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToResumeListResumeRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedToSetupItemHOReqAck { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABFailedtoSetupListHOReqAck { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModificationConfirm { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModificationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyItemBearerModConf { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyItemBearerModRes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyListBearerModConf { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyListBearerModRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABModifyResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABNotToBeModifiedItemBearerModInd { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABNotToBeModifiedListBearerModInd { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseItemBearerRelComp { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseListBearerRelComp { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABReleaseResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupItemBearerSURes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupItemCtxtSURes { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupListBearerSURes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupListCtxtSURes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABSubjecttoDataForwardingList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedItemBearerModInd { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedItemBearerModReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedListBearerModInd { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeModifiedListBearerModReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemBearerSUReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemCtxtSUReq { e_rablevel_qo_sparameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupItemHOReq { e_rablevel_qos_parameters, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListBearerSUReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListCtxtSUReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSetupListHOReq { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedDLItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedDLList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedULItem { i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeSwitchedULList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeUpdatedItem { security_indication, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ERABToBeUpdatedList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBCPRelocationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdate { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdateAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBConfigurationUpdateFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBDirectInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBEarlyStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ENBStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ErrorIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCancel { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCancelAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverNotify { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverPreparationFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequestAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverRequired { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::HandoverSuccess { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialContextSetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InitialUEMessage { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::InterSystemInformationTransferType { rIMTransfer } else {} }
open_types! { crate::s1ap::s1_ap_pdu_contents::KillRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::KillResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReportingControl { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::LocationReportingFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMECPRelocationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdate { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdateAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEConfigurationUpdateFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEDirectInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEEarlyStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::MMEStatusTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::NASDeliveryIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::NASNonDeliveryIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::OverloadStart { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::OverloadStop { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PWSFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PWSRestartIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::Paging { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequestAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PathSwitchRequestFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::AnonymousPrivateMessagePrivateIEs { value } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PrivateMessagePrivateIEs { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::PrivateMessage { private_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::RerouteNASRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::Reset { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ResetAcknowledge { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::ResetType { partOfS1_Interface } else { s1_Interface } }
open_types! { crate::s1ap::s1_ap_pdu_contents::RetrieveUEInformation { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1RemovalResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::S1SetupResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::SecondaryRATDataUsageReport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TAIItem { t_ai, i_e_extensions } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TAIList { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TraceFailureIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::TraceStart { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEAssociatedLogicalS1ConnectionListRes { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEAssociatedLogicalS1ConnectionListResAck { 0 } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UECapabilityInfoIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationConfirm { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationIndication { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextModificationResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseCommand { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseComplete { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextReleaseRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeFailure { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextResumeResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextSuspendRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEContextSuspendResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UEInformationTransfer { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityIDMappingRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityIDMappingResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityMatchRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UERadioCapabilityMatchResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkNASTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkNonUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkS1cdma2000tunnelling { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::UplinkUEAssociatedLPPaTransport { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::WriteReplaceWarningRequest { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_contents::WriteReplaceWarningResponse { protocol_ies } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::InitiatingMessage { value } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::S1APPDU { initiatingMessage, successfulOutcome, unsuccessfulOutcome } else {} }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::SuccessfulOutcome { value } }
open_types! { crate::s1ap::s1_ap_pdu_descriptions::UnsuccessfulOutcome { value } }
