// Auto-generated by build/registry.rs from ASN.1; do not edit.
use crate::macros::{ies, procedures};
procedures! {
    0 HandoverPreparation { InitiatingMessage Initiating_HandoverPreparation "HandoverRequired" crate::s1ap::HandoverRequired; SuccessfulOutcome Successful_HandoverPreparation "HandoverCommand" crate::s1ap::HandoverCommand; UnsuccessfulOutcome Unsuccessful_HandoverPreparation "HandoverPreparationFailure" crate::s1ap::HandoverPreparationFailure; }
    1 HandoverResourceAllocation { InitiatingMessage Initiating_HandoverResourceAllocation "HandoverRequest" crate::s1ap::HandoverRequest; SuccessfulOutcome Successful_HandoverResourceAllocation "HandoverRequestAcknowledge" crate::s1ap::HandoverRequestAcknowledge; UnsuccessfulOutcome Unsuccessful_HandoverResourceAllocation "HandoverFailure" crate::s1ap::HandoverFailure; }
    2 HandoverNotification { InitiatingMessage Initiating_HandoverNotification "HandoverNotify" crate::s1ap::HandoverNotify; }
    3 PathSwitchRequest { InitiatingMessage Initiating_PathSwitchRequest "PathSwitchRequest" crate::s1ap::PathSwitchRequest; SuccessfulOutcome Successful_PathSwitchRequest "PathSwitchRequestAcknowledge" crate::s1ap::PathSwitchRequestAcknowledge; UnsuccessfulOutcome Unsuccessful_PathSwitchRequest "PathSwitchRequestFailure" crate::s1ap::PathSwitchRequestFailure; }
    4 HandoverCancel { InitiatingMessage Initiating_HandoverCancel "HandoverCancel" crate::s1ap::HandoverCancel; SuccessfulOutcome Successful_HandoverCancel "HandoverCancelAcknowledge" crate::s1ap::HandoverCancelAcknowledge; }
    5 E_RABSetup { InitiatingMessage Initiating_E_RABSetup "E-RABSetupRequest" crate::s1ap::ERABSetupRequest; SuccessfulOutcome Successful_E_RABSetup "E-RABSetupResponse" crate::s1ap::ERABSetupResponse; }
    6 E_RABModify { InitiatingMessage Initiating_E_RABModify "E-RABModifyRequest" crate::s1ap::ERABModifyRequest; SuccessfulOutcome Successful_E_RABModify "E-RABModifyResponse" crate::s1ap::ERABModifyResponse; }
    7 E_RABRelease { InitiatingMessage Initiating_E_RABRelease "E-RABReleaseCommand" crate::s1ap::ERABReleaseCommand; SuccessfulOutcome Successful_E_RABRelease "E-RABReleaseResponse" crate::s1ap::ERABReleaseResponse; }
    8 E_RABReleaseIndication { InitiatingMessage Initiating_E_RABReleaseIndication "E-RABReleaseIndication" crate::s1ap::ERABReleaseIndication; }
    9 InitialContextSetup { InitiatingMessage Initiating_InitialContextSetup "InitialContextSetupRequest" crate::s1ap::InitialContextSetupRequest; SuccessfulOutcome Successful_InitialContextSetup "InitialContextSetupResponse" crate::s1ap::InitialContextSetupResponse; UnsuccessfulOutcome Unsuccessful_InitialContextSetup "InitialContextSetupFailure" crate::s1ap::InitialContextSetupFailure; }
    10 Paging { InitiatingMessage Initiating_Paging "Paging" crate::s1ap::Paging; }
    11 downlinkNASTransport { InitiatingMessage Initiating_downlinkNASTransport "DownlinkNASTransport" crate::s1ap::DownlinkNASTransport; }
    12 initialUEMessage { InitiatingMessage Initiating_initialUEMessage "InitialUEMessage" crate::s1ap::InitialUEMessage; }
    13 uplinkNASTransport { InitiatingMessage Initiating_uplinkNASTransport "UplinkNASTransport" crate::s1ap::UplinkNASTransport; }
    14 Reset { InitiatingMessage Initiating_Reset "Reset" crate::s1ap::Reset; SuccessfulOutcome Successful_Reset "ResetAcknowledge" crate::s1ap::ResetAcknowledge; }
    15 ErrorIndication { InitiatingMessage Initiating_ErrorIndication "ErrorIndication" crate::s1ap::ErrorIndication; }
    16 NASNonDeliveryIndication { InitiatingMessage Initiating_NASNonDeliveryIndication "NASNonDeliveryIndication" crate::s1ap::NASNonDeliveryIndication; }
    17 S1Setup { InitiatingMessage Initiating_S1Setup "S1SetupRequest" crate::s1ap::S1SetupRequest; SuccessfulOutcome Successful_S1Setup "S1SetupResponse" crate::s1ap::S1SetupResponse; UnsuccessfulOutcome Unsuccessful_S1Setup "S1SetupFailure" crate::s1ap::S1SetupFailure; }
    18 UEContextReleaseRequest { InitiatingMessage Initiating_UEContextReleaseRequest "UEContextReleaseRequest" crate::s1ap::UEContextReleaseRequest; }
    19 DownlinkS1cdma2000tunnelling { InitiatingMessage Initiating_DownlinkS1cdma2000tunnelling "DownlinkS1cdma2000tunnelling" crate::s1ap::DownlinkS1cdma2000tunnelling; }
    20 UplinkS1cdma2000tunnelling { InitiatingMessage Initiating_UplinkS1cdma2000tunnelling "UplinkS1cdma2000tunnelling" crate::s1ap::UplinkS1cdma2000tunnelling; }
    21 UEContextModification { InitiatingMessage Initiating_UEContextModification "UEContextModificationRequest" crate::s1ap::UEContextModificationRequest; SuccessfulOutcome Successful_UEContextModification "UEContextModificationResponse" crate::s1ap::UEContextModificationResponse; UnsuccessfulOutcome Unsuccessful_UEContextModification "UEContextModificationFailure" crate::s1ap::UEContextModificationFailure; }
    22 UECapabilityInfoIndication { InitiatingMessage Initiating_UECapabilityInfoIndication "UECapabilityInfoIndication" crate::s1ap::UECapabilityInfoIndication; }
    23 UEContextRelease { InitiatingMessage Initiating_UEContextRelease "UEContextReleaseCommand" crate::s1ap::UEContextReleaseCommand; SuccessfulOutcome Successful_UEContextRelease "UEContextReleaseComplete" crate::s1ap::UEContextReleaseComplete; }
    24 eNBStatusTransfer { InitiatingMessage Initiating_eNBStatusTransfer "ENBStatusTransfer" crate::s1ap::ENBStatusTransfer; }
    25 MMEStatusTransfer { InitiatingMessage Initiating_MMEStatusTransfer "MMEStatusTransfer" crate::s1ap::MMEStatusTransfer; }
    26 DeactivateTrace { InitiatingMessage Initiating_DeactivateTrace "DeactivateTrace" crate::s1ap::DeactivateTrace; }
    27 TraceStart { InitiatingMessage Initiating_TraceStart "TraceStart" crate::s1ap::TraceStart; }
    28 TraceFailureIndication { InitiatingMessage Initiating_TraceFailureIndication "TraceFailureIndication" crate::s1ap::TraceFailureIndication; }
    29 ENBConfigurationUpdate { InitiatingMessage Initiating_ENBConfigurationUpdate "ENBConfigurationUpdate" crate::s1ap::ENBConfigurationUpdate; SuccessfulOutcome Successful_ENBConfigurationUpdate "ENBConfigurationUpdateAcknowledge" crate::s1ap::ENBConfigurationUpdateAcknowledge; UnsuccessfulOutcome Unsuccessful_ENBConfigurationUpdate "ENBConfigurationUpdateFailure" crate::s1ap::ENBConfigurationUpdateFailure; }
    30 MMEConfigurationUpdate { InitiatingMessage Initiating_MMEConfigurationUpdate "MMEConfigurationUpdate" crate::s1ap::MMEConfigurationUpdate; SuccessfulOutcome Successful_MMEConfigurationUpdate "MMEConfigurationUpdateAcknowledge" crate::s1ap::MMEConfigurationUpdateAcknowledge; UnsuccessfulOutcome Unsuccessful_MMEConfigurationUpdate "MMEConfigurationUpdateFailure" crate::s1ap::MMEConfigurationUpdateFailure; }
    31 LocationReportingControl { InitiatingMessage Initiating_LocationReportingControl "LocationReportingControl" crate::s1ap::LocationReportingControl; }
    32 LocationReportingFailureIndication { InitiatingMessage Initiating_LocationReportingFailureIndication "LocationReportingFailureIndication" crate::s1ap::LocationReportingFailureIndication; }
    33 LocationReport { InitiatingMessage Initiating_LocationReport "LocationReport" crate::s1ap::LocationReport; }
    34 OverloadStart { InitiatingMessage Initiating_OverloadStart "OverloadStart" crate::s1ap::OverloadStart; }
    35 OverloadStop { InitiatingMessage Initiating_OverloadStop "OverloadStop" crate::s1ap::OverloadStop; }
    36 WriteReplaceWarning { InitiatingMessage Initiating_WriteReplaceWarning "WriteReplaceWarningRequest" crate::s1ap::WriteReplaceWarningRequest; SuccessfulOutcome Successful_WriteReplaceWarning "WriteReplaceWarningResponse" crate::s1ap::WriteReplaceWarningResponse; }
    37 eNBDirectInformationTransfer { InitiatingMessage Initiating_eNBDirectInformationTransfer "ENBDirectInformationTransfer" crate::s1ap::ENBDirectInformationTransfer; }
    38 MMEDirectInformationTransfer { InitiatingMessage Initiating_MMEDirectInformationTransfer "MMEDirectInformationTransfer" crate::s1ap::MMEDirectInformationTransfer; }
    39 PrivateMessage { InitiatingMessage Initiating_PrivateMessage "PrivateMessage" crate::s1ap::PrivateMessage; }
    40 eNBConfigurationTransfer { InitiatingMessage Initiating_eNBConfigurationTransfer "ENBConfigurationTransfer" crate::s1ap::ENBConfigurationTransfer; }
    41 MMEConfigurationTransfer { InitiatingMessage Initiating_MMEConfigurationTransfer "MMEConfigurationTransfer" crate::s1ap::MMEConfigurationTransfer; }
    42 CellTrafficTrace { InitiatingMessage Initiating_CellTrafficTrace "CellTrafficTrace" crate::s1ap::CellTrafficTrace; }
    43 Kill { InitiatingMessage Initiating_Kill "KillRequest" crate::s1ap::KillRequest; SuccessfulOutcome Successful_Kill "KillResponse" crate::s1ap::KillResponse; }
    44 downlinkUEAssociatedLPPaTransport { InitiatingMessage Initiating_downlinkUEAssociatedLPPaTransport "DownlinkUEAssociatedLPPaTransport" crate::s1ap::DownlinkUEAssociatedLPPaTransport; }
    45 uplinkUEAssociatedLPPaTransport { InitiatingMessage Initiating_uplinkUEAssociatedLPPaTransport "UplinkUEAssociatedLPPaTransport" crate::s1ap::UplinkUEAssociatedLPPaTransport; }
    46 downlinkNonUEAssociatedLPPaTransport { InitiatingMessage Initiating_downlinkNonUEAssociatedLPPaTransport "DownlinkNonUEAssociatedLPPaTransport" crate::s1ap::DownlinkNonUEAssociatedLPPaTransport; }
    47 uplinkNonUEAssociatedLPPaTransport { InitiatingMessage Initiating_uplinkNonUEAssociatedLPPaTransport "UplinkNonUEAssociatedLPPaTransport" crate::s1ap::UplinkNonUEAssociatedLPPaTransport; }
    48 UERadioCapabilityMatch { InitiatingMessage Initiating_UERadioCapabilityMatch "UERadioCapabilityMatchRequest" crate::s1ap::UERadioCapabilityMatchRequest; SuccessfulOutcome Successful_UERadioCapabilityMatch "UERadioCapabilityMatchResponse" crate::s1ap::UERadioCapabilityMatchResponse; }
    49 PWSRestartIndication { InitiatingMessage Initiating_PWSRestartIndication "PWSRestartIndication" crate::s1ap::PWSRestartIndication; }
    50 E_RABModificationIndication { InitiatingMessage Initiating_E_RABModificationIndication "E-RABModificationIndication" crate::s1ap::ERABModificationIndication; SuccessfulOutcome Successful_E_RABModificationIndication "E-RABModificationConfirm" crate::s1ap::ERABModificationConfirm; }
    51 PWSFailureIndication { InitiatingMessage Initiating_PWSFailureIndication "PWSFailureIndication" crate::s1ap::PWSFailureIndication; }
    52 RerouteNASRequest { InitiatingMessage Initiating_RerouteNASRequest "RerouteNASRequest" crate::s1ap::RerouteNASRequest; }
    53 UEContextModificationIndication { InitiatingMessage Initiating_UEContextModificationIndication "UEContextModificationIndication" crate::s1ap::UEContextModificationIndication; SuccessfulOutcome Successful_UEContextModificationIndication "UEContextModificationConfirm" crate::s1ap::UEContextModificationConfirm; }
    54 ConnectionEstablishmentIndication { InitiatingMessage Initiating_ConnectionEstablishmentIndication "ConnectionEstablishmentIndication" crate::s1ap::ConnectionEstablishmentIndication; }
    55 UEContextSuspend { InitiatingMessage Initiating_UEContextSuspend "UEContextSuspendRequest" crate::s1ap::UEContextSuspendRequest; SuccessfulOutcome Successful_UEContextSuspend "UEContextSuspendResponse" crate::s1ap::UEContextSuspendResponse; }
    56 UEContextResume { InitiatingMessage Initiating_UEContextResume "UEContextResumeRequest" crate::s1ap::UEContextResumeRequest; SuccessfulOutcome Successful_UEContextResume "UEContextResumeResponse" crate::s1ap::UEContextResumeResponse; UnsuccessfulOutcome Unsuccessful_UEContextResume "UEContextResumeFailure" crate::s1ap::UEContextResumeFailure; }
    57 NASDeliveryIndication { InitiatingMessage Initiating_NASDeliveryIndication "NASDeliveryIndication" crate::s1ap::NASDeliveryIndication; }
    58 RetrieveUEInformation { InitiatingMessage Initiating_RetrieveUEInformation "RetrieveUEInformation" crate::s1ap::RetrieveUEInformation; }
    59 UEInformationTransfer { InitiatingMessage Initiating_UEInformationTransfer "UEInformationTransfer" crate::s1ap::UEInformationTransfer; }
    60 eNBCPRelocationIndication { InitiatingMessage Initiating_eNBCPRelocationIndication "ENBCPRelocationIndication" crate::s1ap::ENBCPRelocationIndication; }
    61 MMECPRelocationIndication { InitiatingMessage Initiating_MMECPRelocationIndication "MMECPRelocationIndication" crate::s1ap::MMECPRelocationIndication; }
    62 SecondaryRATDataUsageReport { InitiatingMessage Initiating_SecondaryRATDataUsageReport "SecondaryRATDataUsageReport" crate::s1ap::SecondaryRATDataUsageReport; }
    63 UERadioCapabilityIDMapping { InitiatingMessage Initiating_UERadioCapabilityIDMapping "UERadioCapabilityIDMappingRequest" crate::s1ap::UERadioCapabilityIDMappingRequest; SuccessfulOutcome Successful_UERadioCapabilityIDMapping "UERadioCapabilityIDMappingResponse" crate::s1ap::UERadioCapabilityIDMappingResponse; }
    64 HandoverSuccess { InitiatingMessage Initiating_HandoverSuccess "HandoverSuccess" crate::s1ap::HandoverSuccess; }
    65 eNBEarlyStatusTransfer { InitiatingMessage Initiating_eNBEarlyStatusTransfer "ENBEarlyStatusTransfer" crate::s1ap::ENBEarlyStatusTransfer; }
    66 MMEEarlyStatusTransfer { InitiatingMessage Initiating_MMEEarlyStatusTransfer "MMEEarlyStatusTransfer" crate::s1ap::MMEEarlyStatusTransfer; }
    67 S1Removal { InitiatingMessage Initiating_S1Removal "S1RemovalRequest" crate::s1ap::S1RemovalRequest; SuccessfulOutcome Successful_S1Removal "S1RemovalResponse" crate::s1ap::S1RemovalResponse; UnsuccessfulOutcome Unsuccessful_S1Removal "S1RemovalFailure" crate::s1ap::S1RemovalFailure; }
}
ies! {
    0 "MME-UE-S1AP-ID" crate::s1ap::MMEUES1APID => MME_UE_S1AP_ID;
    1 "HandoverType" crate::s1ap::HandoverType => HandoverType;
    2 "Cause" crate::s1ap::Cause => Cause;
    4 "TargetID" crate::s1ap::TargetID => TargetID;
    8 "eNB-UE-S1AP-ID" crate::s1ap::ENBUES1APID => eNB_UE_S1AP_ID ENBUES1APID;
    12 "E-RABSubjecttoDataForwardingList" crate::s1ap::ERABSubjecttoDataForwardingList => E_RABSubjecttoDataForwardingList ERABSubjecttoDataForwardingList;
    13 "E-RABtoReleaseListHOCmd" crate::s1ap::ERABList => E_RABtoReleaseListHOCmd;
    14 "E-RABDataForwardingItem" crate::s1ap::ERABDataForwardingItem => E_RABDataForwardingItem ERABDataForwardingItem;
    15 "E-RABReleaseItemBearerRelComp" crate::s1ap::ERABReleaseItemBearerRelComp => E_RABReleaseItemBearerRelComp ERABReleaseItemBearerRelComp;
    16 "E-RABToBeSetupListBearerSUReq" crate::s1ap::ERABToBeSetupListBearerSUReq => E_RABToBeSetupListBearerSUReq ERABToBeSetupListBearerSUReq;
    17 "E-RABToBeSetupItemBearerSUReq" crate::s1ap::ERABToBeSetupItemBearerSUReq => E_RABToBeSetupItemBearerSUReq ERABToBeSetupItemBearerSUReq;
    18 "E-RABAdmittedList" crate::s1ap::ERABAdmittedList => E_RABAdmittedList ERABAdmittedList;
    19 "E-RABFailedToSetupListHOReqAck" crate::s1ap::ERABFailedtoSetupListHOReqAck => E_RABFailedToSetupListHOReqAck ERABFailedtoSetupListHOReqAck;
    20 "E-RABAdmittedItem" crate::s1ap::ERABAdmittedItem => E_RABAdmittedItem ERABAdmittedItem;
    21 "E-RABFailedtoSetupItemHOReqAck" crate::s1ap::ERABFailedToSetupItemHOReqAck => E_RABFailedtoSetupItemHOReqAck ERABFailedToSetupItemHOReqAck;
    22 "E-RABToBeSwitchedDLList" crate::s1ap::ERABToBeSwitchedDLList => E_RABToBeSwitchedDLList ERABToBeSwitchedDLList;
    23 "E-RABToBeSwitchedDLItem" crate::s1ap::ERABToBeSwitchedDLItem => E_RABToBeSwitchedDLItem ERABToBeSwitchedDLItem;
    24 "E-RABToBeSetupListCtxtSUReq" crate::s1ap::ERABToBeSetupListCtxtSUReq => E_RABToBeSetupListCtxtSUReq ERABToBeSetupListCtxtSUReq;
    25 "TraceActivation" crate::s1ap::TraceActivation => TraceActivation;
    26 "NAS-PDU" crate::s1ap::NASPDU => NAS_PDU NASPDU;
    27 "E-RABToBeSetupItemHOReq" crate::s1ap::ERABToBeSetupItemHOReq => E_RABToBeSetupItemHOReq ERABToBeSetupItemHOReq;
    28 "E-RABSetupListBearerSURes" crate::s1ap::ERABSetupListBearerSURes => E_RABSetupListBearerSURes ERABSetupListBearerSURes;
    29 "E-RABFailedToSetupListBearerSURes" crate::s1ap::ERABList => E_RABFailedToSetupListBearerSURes;
    30 "E-RABToBeModifiedListBearerModReq" crate::s1ap::ERABToBeModifiedListBearerModReq => E_RABToBeModifiedListBearerModReq ERABToBeModifiedListBearerModReq;
    31 "E-RABModifyListBearerModRes" crate::s1ap::ERABModifyListBearerModRes => E_RABModifyListBearerModRes ERABModifyListBearerModRes;
    32 "E-RABFailedToModifyList" crate::s1ap::ERABList => E_RABFailedToModifyList;
    33 "E-RABToBeReleasedList" crate::s1ap::ERABList => E_RABToBeReleasedList;
    34 "E-RABFailedToReleaseList" crate::s1ap::ERABList => E_RABFailedToReleaseList;
    35 "E-RABItem" crate::s1ap::ERABItem => E_RABItem ERABItem;
    36 "E-RABToBeModifiedItemBearerModReq" crate::s1ap::ERABToBeModifiedItemBearerModReq => E_RABToBeModifiedItemBearerModReq ERABToBeModifiedItemBearerModReq;
    37 "E-RABModifyItemBearerModRes" crate::s1ap::ERABModifyItemBearerModRes => E_RABModifyItemBearerModRes ERABModifyItemBearerModRes;
    39 "E-RABSetupItemBearerSURes" crate::s1ap::ERABSetupItemBearerSURes => E_RABSetupItemBearerSURes ERABSetupItemBearerSURes;
    40 "SecurityContext" crate::s1ap::SecurityContext => SecurityContext;
    41 "HandoverRestrictionList" crate::s1ap::HandoverRestrictionList => HandoverRestrictionList;
    43 "UEPagingID" crate::s1ap::UEPagingID => UEPagingID;
    44 "pagingDRX" crate::s1ap::PagingDRX => pagingDRX;
    46 "TAIList" crate::s1ap::TAIList => TAIList;
    47 "TAIItem" crate::s1ap::TAIItem => TAIItem;
    48 "E-RABFailedToSetupListCtxtSURes" crate::s1ap::ERABList => E_RABFailedToSetupListCtxtSURes;
    50 "E-RABSetupItemCtxtSURes" crate::s1ap::ERABSetupItemCtxtSURes => E_RABSetupItemCtxtSURes ERABSetupItemCtxtSURes;
    51 "E-RABSetupListCtxtSURes" crate::s1ap::ERABSetupListCtxtSURes => E_RABSetupListCtxtSURes ERABSetupListCtxtSURes;
    52 "E-RABToBeSetupItemCtxtSUReq" crate::s1ap::ERABToBeSetupItemCtxtSUReq => E_RABToBeSetupItemCtxtSUReq ERABToBeSetupItemCtxtSUReq;
    53 "E-RABToBeSetupListHOReq" crate::s1ap::ERABToBeSetupListHOReq => E_RABToBeSetupListHOReq ERABToBeSetupListHOReq;
    58 "CriticalityDiagnostics" crate::s1ap::CriticalityDiagnostics => CriticalityDiagnostics;
    59 "Global-ENB-ID" crate::s1ap::GlobalENBID => Global_ENB_ID GlobalENBID;
    60 "eNBname" crate::s1ap::ENBname => eNBname ENBname;
    61 "MMEname" crate::s1ap::MMEname => MMEname;
    64 "SupportedTAs" crate::s1ap::SupportedTAs => SupportedTAs;
    65 "TimeToWait" crate::s1ap::TimeToWait => TimeToWait;
    66 "uEaggregateMaximumBitrate" crate::s1ap::UEAggregateMaximumBitrate => uEaggregateMaximumBitrate UEAggregateMaximumBitrate;
    67 "TAI" crate::s1ap::TAI => TAI;
    69 "E-RABReleaseListBearerRelComp" crate::s1ap::ERABReleaseListBearerRelComp => E_RABReleaseListBearerRelComp ERABReleaseListBearerRelComp;
    70 "cdma2000PDU" crate::s1ap::Cdma2000PDU => cdma2000PDU Cdma2000PDU;
    71 "cdma2000RATType" crate::s1ap::Cdma2000RATType => cdma2000RATType Cdma2000RATType;
    72 "cdma2000SectorID" crate::s1ap::Cdma2000SectorID => cdma2000SectorID Cdma2000SectorID;
    73 "SecurityKey" crate::s1ap::SecurityKey => SecurityKey;
    74 "UERadioCapability" crate::s1ap::UERadioCapability => UERadioCapability;
    75 "GUMMEI-ID" crate::s1ap::GUMMEI => GUMMEI_ID;
    78 "E-RABInformationListItem" crate::s1ap::ERABInformationListItem => E_RABInformationListItem ERABInformationListItem;
    79 "Direct-Forwarding-Path-Availability" crate::s1ap::DirectForwardingPathAvailability => Direct_Forwarding_Path_Availability DirectForwardingPathAvailability;
    80 "UEIdentityIndexValue" crate::s1ap::UEIdentityIndexValue => UEIdentityIndexValue;
    83 "cdma2000HOStatus" crate::s1ap::Cdma2000HOStatus => cdma2000HOStatus Cdma2000HOStatus;
    84 "cdma2000HORequiredIndication" crate::s1ap::Cdma2000HORequiredIndication => cdma2000HORequiredIndication Cdma2000HORequiredIndication;
    86 "E-UTRAN-Trace-ID" crate::s1ap::EUTRANTraceID => E_UTRAN_Trace_ID EUTRANTraceID;
    87 "RelativeMMECapacity" crate::s1ap::RelativeMMECapacity => RelativeMMECapacity;
    88 "SourceMME-UE-S1AP-ID" crate::s1ap::MMEUES1APID => SourceMME_UE_S1AP_ID;
    89 "Bearers-SubjectToStatusTransfer-Item" crate::s1ap::BearersSubjectToStatusTransferItem => Bearers_SubjectToStatusTransfer_Item BearersSubjectToStatusTransferItem;
    90 "eNB-StatusTransfer-TransparentContainer" crate::s1ap::ENBStatusTransferTransparentContainer => eNB_StatusTransfer_TransparentContainer ENBStatusTransferTransparentContainer;
    91 "UE-associatedLogicalS1-ConnectionItem" crate::s1ap::UEAssociatedLogicalS1ConnectionItem => UE_associatedLogicalS1_ConnectionItem UEAssociatedLogicalS1ConnectionItem;
    92 "ResetType" crate::s1ap::ResetType => ResetType;
    93 "UE-associatedLogicalS1-ConnectionListResAck" crate::s1ap::UEAssociatedLogicalS1ConnectionListResAck => UE_associatedLogicalS1_ConnectionListResAck UEAssociatedLogicalS1ConnectionListResAck;
    94 "E-RABToBeSwitchedULItem" crate::s1ap::ERABToBeSwitchedULItem => E_RABToBeSwitchedULItem ERABToBeSwitchedULItem;
    95 "E-RABToBeSwitchedULList" crate::s1ap::ERABToBeSwitchedULList => E_RABToBeSwitchedULList ERABToBeSwitchedULList;
    96 "S-TMSI" crate::s1ap::STMSI => S_TMSI STMSI;
    97 "cdma2000OneXRAND" crate::s1ap::Cdma2000OneXRAND => cdma2000OneXRAND Cdma2000OneXRAND;
    98 "RequestType" crate::s1ap::RequestType => RequestType;
    99 "UE-S1AP-IDs" crate::s1ap::UES1APIDs => UE_S1AP_IDs UES1APIDs;
    100 "EUTRAN-CGI" crate::s1ap::EUTRANCGI => EUTRAN_CGI EUTRANCGI;
    101 "OverloadResponse" crate::s1ap::OverloadResponse => OverloadResponse;
    102 "cdma2000OneXSRVCCInfo" crate::s1ap::Cdma2000OneXSRVCCInfo => cdma2000OneXSRVCCInfo Cdma2000OneXSRVCCInfo;
    104 "Source-ToTarget-TransparentContainer" crate::s1ap::SourceToTargetTransparentContainer => Source_ToTarget_TransparentContainer;
    105 "ServedGUMMEIs" crate::s1ap::ServedGUMMEIs => ServedGUMMEIs;
    106 "SubscriberProfileIDforRFP" crate::s1ap::SubscriberProfileIDforRFP => SubscriberProfileIDforRFP;
    107 "UESecurityCapabilities" crate::s1ap::UESecurityCapabilities => UESecurityCapabilities;
    108 "CSFallbackIndicator" crate::s1ap::CSFallbackIndicator => CSFallbackIndicator;
    109 "CNDomain" crate::s1ap::CNDomain => CNDomain;
    110 "E-RABReleasedList" crate::s1ap::ERABList => E_RABReleasedList;
    111 "MessageIdentifier" crate::s1ap::MessageIdentifier => MessageIdentifier;
    112 "SerialNumber" crate::s1ap::SerialNumber => SerialNumber;
    113 "WarningAreaList" crate::s1ap::WarningAreaList => WarningAreaList;
    114 "RepetitionPeriod" crate::s1ap::RepetitionPeriod => RepetitionPeriod;
    115 "NumberofBroadcastRequest" crate::s1ap::NumberofBroadcastRequest => NumberofBroadcastRequest;
    116 "WarningType" crate::s1ap::WarningType => WarningType;
    117 "WarningSecurityInfo" crate::s1ap::WarningSecurityInfo => WarningSecurityInfo;
    118 "DataCodingScheme" crate::s1ap::DataCodingScheme => DataCodingScheme;
    119 "WarningMessageContents" crate::s1ap::WarningMessageContents => WarningMessageContents;
    120 "BroadcastCompletedAreaList" crate::s1ap::BroadcastCompletedAreaList => BroadcastCompletedAreaList;
    121 "Inter-SystemInformationTransferTypeEDT" crate::s1ap::InterSystemInformationTransferType => Inter_SystemInformationTransferTypeEDT;
    122 "Inter-SystemInformationTransferTypeMDT" crate::s1ap::InterSystemInformationTransferType => Inter_SystemInformationTransferTypeMDT;
    123 "Target-ToSource-TransparentContainer" crate::s1ap::TargetToSourceTransparentContainer => Target_ToSource_TransparentContainer;
    124 "SRVCCOperationPossible" crate::s1ap::SRVCCOperationPossible => SRVCCOperationPossible;
    125 "SRVCCHOIndication" crate::s1ap::SRVCCHOIndication => SRVCCHOIndication;
    127 "CSG-Id" crate::s1ap::CSGId => CSG_Id CSGId;
    128 "CSG-IdList" crate::s1ap::CSGIdList => CSG_IdList CSGIdList;
    129 "SONConfigurationTransferECT" crate::s1ap::SONConfigurationTransfer => SONConfigurationTransferECT;
    130 "SONConfigurationTransferMCT" crate::s1ap::SONConfigurationTransfer => SONConfigurationTransferMCT;
    131 "TraceCollectionEntityIPAddress" crate::s1ap::TransportLayerAddress => TraceCollectionEntityIPAddress;
    132 "MSClassmark2" crate::s1ap::MSClassmark2 => MSClassmark2;
    133 "MSClassmark3" crate::s1ap::MSClassmark3 => MSClassmark3;
    134 "RRC-Establishment-Cause" crate::s1ap::RRCEstablishmentCause => RRC_Establishment_Cause;
    135 "NASSecurityParametersfromE-UTRAN" crate::s1ap::NASSecurityParametersfromEUTRAN => NASSecurityParametersfromE_UTRAN NASSecurityParametersfromEUTRAN;
    136 "NASSecurityParameterstoE-UTRAN" crate::s1ap::NASSecurityParameterstoEUTRAN => NASSecurityParameterstoE_UTRAN NASSecurityParameterstoEUTRAN;
    137 "DefaultPagingDRX" crate::s1ap::PagingDRX => DefaultPagingDRX;
    138 "Source-ToTarget-TransparentContainer-Secondary" crate::s1ap::SourceToTargetTransparentContainer => Source_ToTarget_TransparentContainer_Secondary;
    139 "Target-ToSource-TransparentContainer-Secondary" crate::s1ap::TargetToSourceTransparentContainer => Target_ToSource_TransparentContainer_Secondary;
    140 "EUTRANRoundTripDelayEstimationInfo" crate::s1ap::EUTRANRoundTripDelayEstimationInfo => EUTRANRoundTripDelayEstimationInfo;
    141 "BroadcastCancelledAreaList" crate::s1ap::BroadcastCancelledAreaList => BroadcastCancelledAreaList;
    142 "ConcurrentWarningMessageIndicator" crate::s1ap::ConcurrentWarningMessageIndicator => ConcurrentWarningMessageIndicator;
    143 "Data-Forwarding-Not-Possible" crate::s1ap::DataForwardingNotPossible;
    144 "ExtendedRepetitionPeriod" crate::s1ap::ExtendedRepetitionPeriod => ExtendedRepetitionPeriod;
    145 "CellAccessMode" crate::s1ap::CellAccessMode => CellAccessMode;
    146 "CSGMembershipStatus" crate::s1ap::CSGMembershipStatus => CSGMembershipStatus;
    147 "LPPa-PDU" crate::s1ap::LPPaPDU => LPPa_PDU LPPaPDU;
    148 "Routing-ID" crate::s1ap::RoutingID => Routing_ID RoutingID;
    149 "Time-Synchronisation-Info" crate::s1ap::TimeSynchronisationInfo;
    150 "PS-ServiceNotAvailable" crate::s1ap::PSServiceNotAvailable => PS_ServiceNotAvailable PSServiceNotAvailable;
    151 "PagingPriority" crate::s1ap::PagingPriority => PagingPriority;
    152 "x2TNLConfigurationInfo" crate::s1ap::X2TNLConfigurationInfo;
    153 "eNBX2ExtendedTransportLayerAddresses" crate::s1ap::ENBX2ExtTLAs;
    154 "GUMMEIList" crate::s1ap::GUMMEIList => GUMMEIList;
    155 "GW-TransportLayerAddress" crate::s1ap::TransportLayerAddress => GW_TransportLayerAddress;
    156 "Correlation-ID" crate::s1ap::CorrelationID;
    157 "SourceMME-GUMMEI" crate::s1ap::GUMMEI => SourceMME_GUMMEI;
    158 "MME-UE-S1AP-ID-2" crate::s1ap::MMEUES1APID => MME_UE_S1AP_ID_2;
    159 "RegisteredLAI" crate::s1ap::LAI => RegisteredLAI LAI;
    160 "RelayNode-Indicator" crate::s1ap::RelayNodeIndicator => RelayNode_Indicator RelayNodeIndicator;
    161 "TrafficLoadReductionIndication" crate::s1ap::TrafficLoadReductionIndication => TrafficLoadReductionIndication;
    162 "MDTConfiguration" crate::s1ap::MDTConfiguration;
    163 "MMERelaySupportIndicator" crate::s1ap::MMERelaySupportIndicator => MMERelaySupportIndicator;
    164 "GWContextReleaseIndication" crate::s1ap::GWContextReleaseIndication => GWContextReleaseIndication;
    165 "ManagementBasedMDTAllowed" crate::s1ap::ManagementBasedMDTAllowed => ManagementBasedMDTAllowed;
    166 "PrivacyIndicator" crate::s1ap::PrivacyIndicator => PrivacyIndicator;
    167 "Time-UE-StayedInCell-EnhancedGranularity" crate::s1ap::TimeUEStayedInCellEnhancedGranularity;
    168 "HO-Cause" crate::s1ap::Cause;
    169 "VoiceSupportMatchIndicator" crate::s1ap::VoiceSupportMatchIndicator => VoiceSupportMatchIndicator;
    170 "GUMMEIType" crate::s1ap::GUMMEIType => GUMMEIType;
    171 "M3Configuration" crate::s1ap::M3Configuration;
    172 "M4Configuration" crate::s1ap::M4Configuration;
    173 "M5Configuration" crate::s1ap::M5Configuration;
    174 "MDT-Location-Info" crate::s1ap::MDTLocationInfo;
    175 "MobilityInformation" crate::s1ap::MobilityInformation;
    176 "Tunnel-Information-for-BBF" crate::s1ap::TunnelInformation => Tunnel_Information_for_BBF TunnelInformation;
    177 "ManagementBasedMDTPLMNList" crate::s1ap::MDTPLMNList => ManagementBasedMDTPLMNList MDTPLMNList;
    178 "SignallingBasedMDTPLMNList" crate::s1ap::MDTPLMNList;
    179 "ULCOUNTValueExtended" crate::s1ap::COUNTValueExtended;
    180 "DLCOUNTValueExtended" crate::s1ap::COUNTValueExtended;
    181 "ReceiveStatusOfULPDCPSDUsExtended" crate::s1ap::ReceiveStatusOfULPDCPSDUsExtended;
    182 "ECGIListForRestart" crate::s1ap::ECGIListForRestart => ECGIListForRestart;
    183 "SIPTO-Correlation-ID" crate::s1ap::CorrelationID;
    184 "SIPTO-L-GW-TransportLayerAddress" crate::s1ap::TransportLayerAddress => SIPTO_L_GW_TransportLayerAddress;
    185 "TransportInformation" crate::s1ap::TransportInformation;
    186 "LHN-ID" crate::s1ap::LHNID => LHN_ID LHNID;
    187 "AdditionalCSFallbackIndicator" crate::s1ap::AdditionalCSFallbackIndicator => AdditionalCSFallbackIndicator;
    188 "TAIListForRestart" crate::s1ap::TAIListForRestart => TAIListForRestart;
    189 "UserLocationInformation" crate::s1ap::UserLocationInformation => UserLocationInformation;
    190 "EmergencyAreaIDListForRestart" crate::s1ap::EmergencyAreaIDListForRestart => EmergencyAreaIDListForRestart;
    191 "KillAllWarningMessages" crate::s1ap::KillAllWarningMessages => KillAllWarningMessages;
    192 "Masked-IMEISV" crate::s1ap::MaskedIMEISV => Masked_IMEISV MaskedIMEISV;
    193 "eNBIndirectX2TransportLayerAddresses" crate::s1ap::ENBIndirectX2TransportLayerAddresses;
    194 "uE-HistoryInformationFromTheUE" crate::s1ap::UEHistoryInformationFromTheUE;
    195 "ProSeAuthorized" crate::s1ap::ProSeAuthorized => ProSeAuthorized;
    196 "ExpectedUEBehaviour" crate::s1ap::ExpectedUEBehaviour => ExpectedUEBehaviour;
    197 "LoggedMBSFNMDT" crate::s1ap::LoggedMBSFNMDT => LoggedMBSFNMDT;
    198 "UERadioCapabilityForPaging" crate::s1ap::UERadioCapabilityForPaging => UERadioCapabilityForPaging;
    199 "E-RABToBeModifiedListBearerModInd" crate::s1ap::ERABToBeModifiedListBearerModInd => E_RABToBeModifiedListBearerModInd ERABToBeModifiedListBearerModInd;
    200 "E-RABToBeModifiedItemBearerModInd" crate::s1ap::ERABToBeModifiedItemBearerModInd => E_RABToBeModifiedItemBearerModInd ERABToBeModifiedItemBearerModInd;
    201 "E-RABNotToBeModifiedListBearerModInd" crate::s1ap::ERABNotToBeModifiedListBearerModInd => E_RABNotToBeModifiedListBearerModInd ERABNotToBeModifiedListBearerModInd;
    202 "E-RABNotToBeModifiedItemBearerModInd" crate::s1ap::ERABNotToBeModifiedItemBearerModInd => E_RABNotToBeModifiedItemBearerModInd ERABNotToBeModifiedItemBearerModInd;
    203 "E-RABModifyListBearerModConf" crate::s1ap::ERABModifyListBearerModConf => E_RABModifyListBearerModConf ERABModifyListBearerModConf;
    204 "E-RABModifyItemBearerModConf" crate::s1ap::ERABModifyItemBearerModConf => E_RABModifyItemBearerModConf ERABModifyItemBearerModConf;
    205 "E-RABFailedToModifyListBearerModConf" crate::s1ap::ERABList => E_RABFailedToModifyListBearerModConf;
    206 "SON-Information-Report" crate::s1ap::SONInformationReport => SON_Information_Report SONInformationReport;
    207 "Muting-Availability-Indication" crate::s1ap::MutingAvailabilityIndication;
    208 "Muting-Pattern-Information" crate::s1ap::MutingPatternInformation;
    209 "Synchronisation-Information" crate::s1ap::SynchronisationInformation;
    210 "E-RABToBeReleasedListBearerModConf" crate::s1ap::ERABList => E_RABToBeReleasedListBearerModConf;
    211 "AssistanceDataForPaging" crate::s1ap::AssistanceDataForPaging => AssistanceDataForPaging;
    212 "CellIdentifierAndCELevelForCECapableUEs" crate::s1ap::CellIdentifierAndCELevelForCECapableUEs => CellIdentifierAndCELevelForCECapableUEs;
    213 "InformationOnRecommendedCellsAndENBsForPaging" crate::s1ap::InformationOnRecommendedCellsAndENBsForPaging => InformationOnRecommendedCellsAndENBsForPaging;
    214 "RecommendedCellItem" crate::s1ap::RecommendedCellItem => RecommendedCellItem;
    215 "RecommendedENBItem" crate::s1ap::RecommendedENBItem => RecommendedENBItem;
    216 "ProSeUEtoNetworkRelaying" crate::s1ap::ProSeUEtoNetworkRelaying;
    217 "ULCOUNTValuePDCP-SNlength18" crate::s1ap::COUNTvaluePDCPSNlength18;
    218 "DLCOUNTValuePDCP-SNlength18" crate::s1ap::COUNTvaluePDCPSNlength18;
    219 "ReceiveStatusOfULPDCPSDUsPDCP-SNlength18" crate::s1ap::ReceiveStatusOfULPDCPSDUsPDCPSNlength18;
    220 "M6Configuration" crate::s1ap::M6Configuration;
    221 "M7Configuration" crate::s1ap::M7Configuration;
    222 "PWSfailedECGIList" crate::s1ap::PWSfailedECGIList => PWSfailedECGIList;
    223 "MME-Group-ID" crate::s1ap::MMEGroupID => MME_Group_ID MMEGroupID;
    224 "Additional-GUTI" crate::s1ap::AdditionalGUTI => Additional_GUTI AdditionalGUTI;
    225 "S1-Message" rasn::types::OctetString => S1_Message;
    226 "CSGMembershipInfo" crate::s1ap::CSGMembershipInfo => CSGMembershipInfo;
    227 "Paging-eDRXInformation" crate::s1ap::PagingEDRXInformation => Paging_eDRXInformation PagingEDRXInformation;
    228 "UE-RetentionInformation" crate::s1ap::UERetentionInformation => UE_RetentionInformation UERetentionInformation;
    230 "UE-Usage-Type" crate::s1ap::UEUsageType => UE_Usage_Type UEUsageType;
    231 "extended-UEIdentityIndexValue" crate::s1ap::ExtendedUEIdentityIndexValue => extended_UEIdentityIndexValue ExtendedUEIdentityIndexValue;
    232 "RAT-Type" crate::s1ap::RATType;
    233 "BearerType" crate::s1ap::BearerType;
    234 "NB-IoT-DefaultPagingDRX" crate::s1ap::NBIoTDefaultPagingDRX => NB_IoT_DefaultPagingDRX NBIoTDefaultPagingDRX;
    235 "E-RABFailedToResumeListResumeReq" crate::s1ap::ERABFailedToResumeListResumeReq => E_RABFailedToResumeListResumeReq ERABFailedToResumeListResumeReq;
    236 "E-RABFailedToResumeItemResumeReq" crate::s1ap::ERABFailedToResumeItemResumeReq => E_RABFailedToResumeItemResumeReq ERABFailedToResumeItemResumeReq;
    237 "E-RABFailedToResumeListResumeRes" crate::s1ap::ERABFailedToResumeListResumeRes => E_RABFailedToResumeListResumeRes ERABFailedToResumeListResumeRes;
    238 "E-RABFailedToResumeItemResumeRes" crate::s1ap::ERABFailedToResumeItemResumeRes => E_RABFailedToResumeItemResumeRes ERABFailedToResumeItemResumeRes;
    239 "NB-IoT-Paging-eDRXInformation" crate::s1ap::NBIoTPagingEDRXInformation => NB_IoT_Paging_eDRXInformation NBIoTPagingEDRXInformation;
    240 "V2XServicesAuthorized" crate::s1ap::V2XServicesAuthorized => V2XServicesAuthorized;
    241 "UEUserPlaneCIoTSupportIndicator" crate::s1ap::UEUserPlaneCIoTSupportIndicator => UEUserPlaneCIoTSupportIndicator;
    242 "CE-mode-B-SupportIndicator" crate::s1ap::CEModeBSupportIndicator => CE_mode_B_SupportIndicator CEModeBSupportIndicator;
    243 "SRVCCOperationNotPossible" crate::s1ap::SRVCCOperationNotPossible => SRVCCOperationNotPossible;
    244 "NB-IoT-UEIdentityIndexValue" crate::s1ap::NBIoTUEIdentityIndexValue => NB_IoT_UEIdentityIndexValue NBIoTUEIdentityIndexValue;
    245 "RRC-Resume-Cause" crate::s1ap::RRCEstablishmentCause => RRC_Resume_Cause;
    246 "DCN-ID" crate::s1ap::DCNID => DCN_ID DCNID;
    247 "ServedDCNs" crate::s1ap::ServedDCNs => ServedDCNs;
    248 "UESidelinkAggregateMaximumBitrate" crate::s1ap::UESidelinkAggregateMaximumBitrate => UESidelinkAggregateMaximumBitrate;
    249 "DLNASPDUDeliveryAckRequest" crate::s1ap::DLNASPDUDeliveryAckRequest => DLNASPDUDeliveryAckRequest;
    250 "Coverage-Level" crate::s1ap::CoverageLevel => Coverage_Level CoverageLevel;
    251 "EnhancedCoverageRestricted" crate::s1ap::EnhancedCoverageRestricted => EnhancedCoverageRestricted;
    252 "UE-Level-QoS-Parameters" crate::s1ap::ERABLevelQoSParameters => UE_Level_QoS_Parameters ERABLevelQoSParameters;
    253 "DL-CP-SecurityInformation" crate::s1ap::DLCPSecurityInformation => DL_CP_SecurityInformation DLCPSecurityInformation;
    254 "UL-CP-SecurityInformation" crate::s1ap::ULCPSecurityInformation => UL_CP_SecurityInformation ULCPSecurityInformation;
    255 "extended-e-RAB-MaximumBitrateDL" crate::s1ap::ExtendedBitRate;
    256 "extended-e-RAB-MaximumBitrateUL" crate::s1ap::ExtendedBitRate;
    257 "extended-e-RAB-GuaranteedBitrateDL" crate::s1ap::ExtendedBitRate;
    258 "extended-e-RAB-GuaranteedBitrateUL" crate::s1ap::ExtendedBitRate;
    259 "extended-uEaggregateMaximumBitRateDL" crate::s1ap::ExtendedBitRate;
    260 "extended-uEaggregateMaximumBitRateUL" crate::s1ap::ExtendedBitRate;
    261 "NRrestrictioninEPSasSecondaryRAT" crate::s1ap::NRrestrictioninEPSasSecondaryRAT;
    262 "UEAppLayerMeasConfig" crate::s1ap::UEAppLayerMeasConfig;
    263 "UE-Application-Layer-Measurement-Capability" crate::s1ap::UEApplicationLayerMeasurementCapability => UE_Application_Layer_Measurement_Capability UEApplicationLayerMeasurementCapability;
    264 "SecondaryRATDataUsageReportList" crate::s1ap::SecondaryRATDataUsageReportList => SecondaryRATDataUsageReportList;
    265 "SecondaryRATDataUsageReportItem" crate::s1ap::SecondaryRATDataUsageReportItem => SecondaryRATDataUsageReportItem;
    266 "HandoverFlag" crate::s1ap::HandoverFlag => HandoverFlag;
    267 "E-RABUsageReportItem" crate::s1ap::ERABUsageReportItem => E_RABUsageReportItem ERABUsageReportItem;
    268 "SecondaryRATDataUsageRequest" crate::s1ap::SecondaryRATDataUsageRequest => SecondaryRATDataUsageRequest;
    269 "NRUESecurityCapabilities" crate::s1ap::NRUESecurityCapabilities => NRUESecurityCapabilities;
    270 "UnlicensedSpectrumRestriction" crate::s1ap::UnlicensedSpectrumRestriction;
    271 "CE-ModeBRestricted" crate::s1ap::CEModeBRestricted => CE_ModeBRestricted CEModeBRestricted;
    272 "LTE-M-Indication" crate::s1ap::LTEMIndication => LTE_M_Indication LTEMIndication;
    273 "DownlinkPacketLossRate" crate::s1ap::PacketLossRate;
    274 "UplinkPacketLossRate" crate::s1ap::PacketLossRate;
    275 "UECapabilityInfoRequest" crate::s1ap::UECapabilityInfoRequest => UECapabilityInfoRequest;
    276 "serviceType" crate::s1ap::ServiceType;
    277 "AerialUEsubscriptionInformation" crate::s1ap::AerialUEsubscriptionInformation => AerialUEsubscriptionInformation;
    278 "Subscription-Based-UE-DifferentiationInfo" crate::s1ap::SubscriptionBasedUEDifferentiationInfo => Subscription_Based_UE_DifferentiationInfo SubscriptionBasedUEDifferentiationInfo;
    280 "EndIndication" crate::s1ap::EndIndication => EndIndication;
    281 "EDT-Session" crate::s1ap::EDTSession => EDT_Session EDTSession;
    282 "CNTypeRestrictions" crate::s1ap::CNTypeRestrictions;
    283 "PendingDataIndication" crate::s1ap::PendingDataIndication => PendingDataIndication;
    284 "BluetoothMeasurementConfiguration" crate::s1ap::BluetoothMeasurementConfiguration;
    285 "WLANMeasurementConfiguration" crate::s1ap::WLANMeasurementConfiguration;
    286 "WarningAreaCoordinates" crate::s1ap::WarningAreaCoordinates => WarningAreaCoordinates;
    287 "NRrestrictionin5GS" crate::s1ap::NRrestrictionin5GS;
    288 "PSCellInformation" crate::s1ap::PSCellInformation => PSCellInformation;
    290 "LastNG-RANPLMNIdentity" crate::s1ap::PLMNidentity;
    291 "ConnectedengNBList" crate::s1ap::ConnectedengNBList => ConnectedengNBList;
    292 "ConnectedengNBToAddList" crate::s1ap::ConnectedengNBList => ConnectedengNBToAddList;
    293 "ConnectedengNBToRemoveList" crate::s1ap::ConnectedengNBList => ConnectedengNBToRemoveList;
    294 "EN-DCSONConfigurationTransfer-ECT" crate::s1ap::ENDCSONConfigurationTransfer => EN_DCSONConfigurationTransfer_ECT;
    295 "EN-DCSONConfigurationTransfer-MCT" crate::s1ap::ENDCSONConfigurationTransfer => EN_DCSONConfigurationTransfer_MCT;
    296 "IMSvoiceEPSfallbackfrom5G" crate::s1ap::IMSvoiceEPSfallbackfrom5G;
    297 "TimeSinceSecondaryNodeRelease" crate::s1ap::TimeSinceSecondaryNodeRelease => TimeSinceSecondaryNodeRelease;
    298 "RequestTypeAdditionalInfo" crate::s1ap::RequestTypeAdditionalInfo;
    299 "AdditionalRRMPriorityIndex" crate::s1ap::AdditionalRRMPriorityIndex => AdditionalRRMPriorityIndex;
    300 "ContextatSource" crate::s1ap::ContextatSource;
    301 "IAB-Authorized" crate::s1ap::IABAuthorized => IAB_Authorized IABAuthorized;
    302 "IAB-Node-Indication" crate::s1ap::IABNodeIndication => IAB_Node_Indication IABNodeIndication;
    303 "IAB-Supported" crate::s1ap::IABSupported => IAB_Supported IABSupported;
    304 "DataSize" crate::s1ap::DataSize => DataSize;
    305 "Ethernet-Type" crate::s1ap::EthernetType;
    306 "NRV2XServicesAuthorized" crate::s1ap::NRV2XServicesAuthorized => NRV2XServicesAuthorized;
    307 "NRUESidelinkAggregateMaximumBitrate" crate::s1ap::NRUESidelinkAggregateMaximumBitrate => NRUESidelinkAggregateMaximumBitrate;
    308 "PC5QoSParameters" crate::s1ap::PC5QoSParameters => PC5QoSParameters;
    309 "IntersystemSONConfigurationTransferMCT" crate::s1ap::IntersystemSONConfigurationTransfer => IntersystemSONConfigurationTransferMCT;
    310 "IntersystemSONConfigurationTransferECT" crate::s1ap::IntersystemSONConfigurationTransfer => IntersystemSONConfigurationTransferECT;
    311 "IntersystemMeasurementConfiguration" crate::s1ap::IntersystemMeasurementConfiguration;
    312 "SourceNodeID" crate::s1ap::SourceNodeID;
    313 "NB-IoT-RLF-Report-Container" crate::s1ap::NBIoTRLFReportContainer;
    314 "UERadioCapabilityID" crate::s1ap::UERadioCapabilityID => UERadioCapabilityID;
    315 "UERadioCapability-NR-Format" crate::s1ap::UERadioCapability => UERadioCapability_NR_Format;
    316 "MDTConfigurationNR" crate::s1ap::MDTConfigurationNR;
    317 "DAPSRequestInfo" crate::s1ap::DAPSRequestInfo;
    318 "DAPSResponseInfoList" crate::s1ap::DAPSResponseInfoList;
    319 "DAPSResponseInfoItem" crate::s1ap::DAPSResponseInfoItem => DAPSResponseInfoItem;
    320 "NotifySourceeNB" crate::s1ap::NotifySourceeNB => NotifySourceeNB;
    321 "eNB-EarlyStatusTransfer-TransparentContainer" crate::s1ap::ENBEarlyStatusTransferTransparentContainer => eNB_EarlyStatusTransfer_TransparentContainer ENBEarlyStatusTransferTransparentContainer;
    322 "Bearers-SubjectToEarlyStatusTransfer-Item" crate::s1ap::BearersSubjectToEarlyStatusTransferItem => Bearers_SubjectToEarlyStatusTransfer_Item BearersSubjectToEarlyStatusTransferItem;
    323 "WUS-Assistance-Information" crate::s1ap::WUSAssistanceInformation => WUS_Assistance_Information WUSAssistanceInformation;
    324 "NB-IoT-PagingDRX" crate::s1ap::NBIoTPagingDRX => NB_IoT_PagingDRX NBIoTPagingDRX;
    325 "TraceCollectionEntityURI" crate::s1ap::URIAddress;
    326 "EmergencyIndicator" crate::s1ap::EmergencyIndicator;
    327 "UERadioCapabilityForPaging-NR-Format" crate::s1ap::UERadioCapabilityForPaging => UERadioCapabilityForPaging_NR_Format;
    328 "SourceTransportLayerAddress" crate::s1ap::TransportLayerAddress;
    329 "lastVisitedPSCellList" crate::s1ap::LastVisitedPSCellList;
    330 "RACSIndication" crate::s1ap::RACSIndication;
    331 "PagingCause" crate::s1ap::PagingCause => PagingCause;
    332 "SecurityIndication" crate::s1ap::SecurityIndication;
    334 "E-RABSecurityResultItem" crate::s1ap::ERABSecurityResultItem => E_RABSecurityResultItem ERABSecurityResultItem;
    335 "E-RABSecurityResultList" crate::s1ap::ERABSecurityResultList;
    336 "RAT-Restrictions" crate::s1ap::RATRestrictions;
    337 "UEContextReferenceatSourceeNB" crate::s1ap::ENBUES1APID;
    339 "LTE-NTN-TAI-Information" crate::s1ap::LTENTNTAIInformation => LTE_NTN_TAI_Information LTENTNTAIInformation;
    340 "SourceNodeTransportLayerAddress" crate::s1ap::TransportLayerAddress;
    341 "E-RABToBeUpdatedList" crate::s1ap::ERABToBeUpdatedList => E_RABToBeUpdatedList ERABToBeUpdatedList;
    342 "E-RABToBeUpdatedItem" crate::s1ap::ERABToBeUpdatedItem => E_RABToBeUpdatedItem ERABToBeUpdatedItem;
    343 "SourceSNID" crate::s1ap::GlobalRANNODEID;
    344 "LoggedMDTTrigger" crate::s1ap::LoggedMDTTrigger;
    345 "SensorMeasurementConfiguration" crate::s1ap::SensorMeasurementConfiguration;
    346 "M4ReportAmount" crate::s1ap::M4ReportAmountMDT;
    347 "M5ReportAmount" crate::s1ap::M5ReportAmountMDT;
    348 "M6ReportAmount" crate::s1ap::M6ReportAmountMDT;
    349 "M7ReportAmount" crate::s1ap::M7ReportAmountMDT;
    350 "TimeBasedHandoverInformation" crate::s1ap::TimeBasedHandoverInformation;
    351 "Bearers-SubjectToDLDiscarding-Item" crate::s1ap::BearersSubjectToDLDiscardingItem => Bearers_SubjectToDLDiscarding_Item BearersSubjectToDLDiscardingItem;
    352 "Bearers-SubjectToDLDiscardingList" crate::s1ap::BearersSubjectToDLDiscardingList;
    353 "CoarseUELocationRequested" crate::s1ap::CoarseUELocationRequested => CoarseUELocationRequested;
    354 "CoarseUELocation" crate::s1ap::CoarseUELocation => CoarseUELocation;
    355 "TimeRefDistribution" crate::s1ap::TimeRefDistribution => TimeRefDistribution;
    356 "RequestedTNLInfo" crate::s1ap::RequestedTNLInfo;
}
